### PR TITLE
Fix wrong date format for Windows Server 2004

### PR DESCRIPTION
**Pull request by Belphemur**
Hello,

I realized the date format for 2004 wasn't following the same as the other.
Date format used is mm/dd/yyyy for the other entries. This one had mm/dd/yy.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Belphemur : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Good update, thank you. Well spotted and resolved.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@illfated: I'm sorry - only the author of this article, @jasongerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My previous comment is in accordance with a previous agreement.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
