### PR TITLE
Updates Ubuntu commands to configure repositories

### PR DESCRIPTION
**Pull request by schultetwin1**
* Changes the commands to use apt-get and apt-add-repository
* Adds more recent versions of Ubuntu

### CODE REVIEW

**Comment by schultetwin1** [comment]
@lizap I'm trying to figure out the correct person to assign to this PR. I see that you are one of the original contributors. Would you be the right one to review this?

**Comment by szarkos** [comment]
I no longer work on packages.microsoft.com, but I am the listed author. However, I'm not able to merge anyway as I think someone from the doc team has to do that.

My 2 cents, I think it would be better to just remove Ubuntu 16.10, 17.04 and 17.10 as those versions are EOL.  It would help unclutter the doc and only focus on the supported versions.

Thanks!

**Comment by schultetwin1** [comment]
> My 2 cents, I think it would be better to just remove Ubuntu 16.10, 17.04 and 17.10 as those versions are EOL. It would help unclutter the doc and only focus on the supported versions.

Good idea, I'll definitely do that.

> I no longer work on packages.microsoft.com, but I am the listed author. However, I'm not able to merge anyway as I think someone from the doc team has to do that.

Good to know. I'll figure out who is the right person to get to review this.

**Comment by schultetwin1** [comment]
#sign-off

**Comment by schultetwin1** [comment]
Closing and moving to windowsserverdocs-pr as an internal contributor.

**Pull request closed without merging**
