### PR TITLE
Included some additional features of windows server 2019

### PR DESCRIPTION
**Pull request by ramabadran**
Contents included
1 .EnterPrise Hyper-Converged Infrastructure
2.Project Honolulu

### CODE REVIEW

**Comment by ramabadran** [comment]
C

**Comment by ramabadran** [comment]
Reopening so that it can be verified and published by Microsoft. Please assist.

**Comment by daveba** [comment]
@JasonGerend Please review and if you agree with the proposed changes, please sign off so I can merge.  Thanks!

**Comment by JasonGerend** [comment]
Thanks for your contributions! The added content is a little dated - Windows Server 2019 and Windows Admin Center both have shipped - so I'm going to suggest that we close this PR. However, you make good points that the current topic doesn't discuss HCI or Windows Admin Center explicitly, so I'm going to try to add those to this topic in a coming publishing cycle. 

Thanks again - we appreciate you input and help!

Jason Gerend - Writer for Windows Server

**Pull request closed without merging**
