### PR TITLE
Update pktmon-syntax.md

### PR DESCRIPTION
**Pull request by george-guirguis**
fixed a small typo

### CODE REVIEW

**Comment by PRMerger9** [comment]
@george-guirguis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Nice typo correction (slightly funny 😄 typo too). Good catch.

**Comment by khdownie** [comment]
Good catch @george-guirguis and thanks @illfated - I took care of this in a separate PR that just automerged, so this PR can be deleted now. The change should go live within the hour.

**Comment by illfated** [comment]
Very good, thank you for sharing the information about related internal PR content (since we others don't have access to the private repo).

@george-guirguis : As previously, I will proceed to close this PR, since this content is already in the pipeline. Feel free to delete this PR branch, if you want to.

**Comment by illfated** [comment]
#please-close

**Pull request closed without merging**
