### PR TITLE
replaced screenshot dls1.1 to dls1.2

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #4731 , so replaced invalid image to correct image

### CODE REVIEW

**Comment by PRMerger12** [comment]
@RAJU2529 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
(ref. #4632, #4627, #4731, #4737 )

**Comment by illfated** [comment]
There you go. PR #4988 is available for viewing, comments and suggestions. Take care of yourself and those near you.

**Comment by PRMerger7** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
I can't merge this PR as the image pointed to is not in an approved location (https://user-images.githubusercontent.com). Please open a new PR with a corrected image location.

**Pull request closed without merging**
