### PR TITLE
adjusted the log guidance

### PR DESCRIPTION
**Pull request by nedpyle**
Added more explanation around sizing

### CODE REVIEW

**Comment by lizap** [comment]
Hi, Ned - little typo in the last sentence of your changes: +Again: Microsoft strongly recommends that the log storage be faster than the data storage and **thatl og** volumes must never be used for other workloads.

Can you fix? Then I'll get this merged and published.

Thanks, Liza

**Comment by nedpyle** [comment]
Done – I think. 😊

NP | PM

**Comment by lizap** [comment]
Beautiful - thanks! I'll get this merged and published today.

**Comment by nedpyle** [comment]
Thank you!

NP | PM

**Pull request merged**
