### PR TITLE
Update deploy-cloud-witness.md

### PR DESCRIPTION
**Pull request by yupsez**
Checked with PG PM under 2105140040003541

### CODE REVIEW

**Comment by PRMerger10** [comment]
@yupsez : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@yupsez : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kaushika-msft** [comment]
Sign-Off

**Comment by JohnCobb1** [comment]
Hi @kaushika-msft To sign off this PR, please place a "#" before the term sign-off in the comment field.

**Comment by PRMerger14** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
