### PR TITLE
Update Forest-Wide-Updates.md

### PR DESCRIPTION
**Pull request by Thameur-BOURBITA**
I think that's still important to mention in the schema update documentation that rollback is only possible through a entire restoration of the forest.
Regarding the automatic preparation of the forest during the installation of the first domain controller, it is important to indicate that with a account membre of Domain Admin group , the preparation of the forest will fail, it needs other privileges at the forest level .

### CODE REVIEW

**Comment by Thameur-BOURBITA** [comment]
Concerning the link https://technet.microsoft.com/library/dd464018(v=ws.10).aspx , it doesn't talk about Windows 2012 ,Windows 2012 R2 and Windows 2016, I suggest to replace it by this one : https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/what-s-new-in-active-directory-domain-services-installation-and-removal

**Comment by lizap** [comment]
Thanks, Thameur - I'm sending this over to the AD writing team to take a look. Thanks, Liza

**Comment by MicrosoftGuyJFlo** [comment]
@Thameur-BOURBITA Thanks for your contribution but this article is not about adprep. While it is important to know what happens when something goes wrong this is not the article to do that in. 

I will keep this info in mind as we work on updating the rest of the AD content so that it is brought out where it needs to be.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Pull request closed without merging**
