### PR TITLE
Update change-listening-port.md as per #5580

### PR DESCRIPTION
**Pull request by IonutDanNica**
Update code for adding rule for RDP UDP protocol in the powershell commands list

### CODE REVIEW

**Comment by PRMerger9** [comment]
@IonutDanNica : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks reasonable and good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@illfated: I'm sorry - only the author of this article, @lizap, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on a previous agreement with the team.

**Comment by illfated** [comment]
( also: ref. #5580 )

**Pull request merged**
