### PR TITLE
Update nslookup.md

### PR DESCRIPTION
**Pull request by kind03**
Add a link for manual on how to use nslookup on noninteractive mode. The previous document does not illustrate enough on the noninteractive mode.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@kind03 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JohnCobb1** [comment]
Hi @kind03 Thanks for your contribution. This link addition needs to be poitioned at the end of the option list in the article in a Note format. Here is the format:

>[!NOTE]
> For more information on how to use noninteractive mode, see the Remarks section of [Nslookup](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc725991(v=ws.11). 

Thanks

**Comment by kind03** [comment]
Thanks!

**Comment by sethmanheim** [comment]
Hello @kind03, are you going to make this change? Please let us know so we can merge this PR. Thank you!

**Comment by sethmanheim** [comment]
Closing, please reopen if this is still an issue.

**Pull request closed without merging**
