### PR TITLE
Update AD-FS-Rapid-Restore-Tool.md

### PR DESCRIPTION
**Pull request by hatakemu**
corrected .NET framework version.

### CODE REVIEW

**Comment by hatakemu** [comment]
Corrected .NET framework version.
The latest version of this tool requires .NET framework 4.6+

**Comment by Court72** [comment]
@robinharwood, @Xelu86

Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
#sign-off

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
#sign-off

**Comment by billmath** [comment]
@Jak-MS  can you merge this?  Thanks!

**Comment by Court72** [comment]
Hi @billmath,

The PR review team doesn't merge PRs in this repo.

@robinharwood, @Xelu86,

Can you review and merge this PR if you approve the proposed changes?

**Pull request merged**
