### PR TITLE
Update certutil.md

### PR DESCRIPTION
**Pull request by p-mx**
Add missing backticks for code blocks.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@p-mx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Good contribution. Coherent with current codestyle used in the document.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@illfated: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. I just added that comment to give it some more attention.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
