### PR TITLE
Remove references to lost KB article 2742970

### LINKED ISSUE #3577: Microsoft KB article link doesn't work
Microsoft KB article link doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081e4892-c7cd-e02a-5251-64cc2655bc8c
* Version Independent ID: b9ebb826-7bb8-168a-062a-825d5910fcd0
* Content: [Virtualized Domain Controller Architecture](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/virtualized-domain-controller-architecture)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Virtualized-Domain-Controller-Architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Virtualized-Domain-Controller-Architecture.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #3577 (**Microsoft KB article link doesn't work**), the URL https://support.microsoft.com/kb/2742970 returns error 404 "Sorry, page not found / Try searching Microsoft Support to find a solution".

Even when using the WayBack Machine (https://web.archive.org/), the page content appears to be lost and gone, so there is hardly anything to look up.

Thanks to Ramu Venkitaramanan (@ramuvr) for reporting this issue.

Based on this lack of information, removing the dead links is a better option.

**Ticket closure or reference:**

Closes #3577

### CODE REVIEW

**Comment by PRMerger15** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
This PR contains the removal of 2 sentences referencing Microsoft KB article 2742970.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
