### PR TITLE
Special Identities: fix (Enterprise) Read-only domain controllers mistakes

### PR DESCRIPTION
**Pull request by cnotin**
Proof that Enterprise Read-only Domain Controllers is a special identity was described in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10035
However, technically, Read-only Domain Controllers is not really a special identity because the membership is explicit: RODCs are really members of this group in AD contrary to Enterprise Read-only Domain Controllers.

### CODE REVIEW

**Comment by jborsecnik** [comment]
@Xelu86, @robinharwood, 

Can you review the proposed changes? **Note: There are conflicts that must also be resolved before this PR can be merged.**

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86

**Comment by cnotin** [comment]
I've fixed the conflicts while maintaining my changes. I hope it can be reviewed soon so it won't be necessary again.

**Comment by Xelu86** [comment]
Hey @cnotin, thank you for your contribution. Minor edits were made, and we'll be merging shortly.

**Comment by cnotin** [comment]
Thanks @Xelu86 for merging and the changes (indeed the conventions used in the page have changed since the beginning of the PR 😉)!
However, are you certain about this addition?
> An Enterprise RODC can replicate a larger subset of the Active Directory database, including the global catalog and read-only domain partitions for all domains in the forest

I don't think that "Enterprise RODC" exist per se, i.e. not as a specific type of RODC.

**Pull request merged**
