### PR TITLE
ADDS/Deploy: Azure Virtual Network supports IPv6

### LINKED ISSUE #4512: IPv6 statement no longer true
The statement "Because Azure virtual networks do not support IPv6" is no longer true as VNETs do now support IPv6.  In fact the link you have on the page gets directed to this page https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#do-vnets-support-ipv6 where it's clearly stated it's now supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0097c-668e-1d37-22b0-89d0bf649f8a
* Version Independent ID: 49ccfef6-05bb-9c93-5a05-a2e2fe632b3c
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #4512 (**IPv6 statement no longer true**), there are 2 occurrences of the same statement that "Azure virtual networks do not support IPv6" linked to a FAQ page answer stating that Azure virtual networks do in fact support IPv6.

Thanks to @aqasrawi (Adiy Qasrawi) for pointing this out to us.

***

**Changes proposed:**
- Modify the affected sentences to correctly say that IPv6 is supported
- Adjust the same sentences to keep the next page link useful
- Whitespace adjustment: add blank line between metadata and page title
- Various grammar and readability improvements:
    - Add commas where needed, to show the sentence logic
    - Add missing words to make the sentence structure clear
    - Change lowercase "ok" to uppercase OK
    - Add parentheses around suggested optional action
    - Add parentheses around example name reference
    - Split one sentence into 2 standalone sentences (logic)

***

**Additional note:** Feel free to request additional grammar or readability
improvements. I might have missed some, or added imprecise corrections.

***

**Ticket closure or reference:**

Closes #4512

### CODE REVIEW

**Comment by illfated** [comment]
#sign-off

**Comment by eross-msft** [comment]
@iainfoulds  Please review and let me know when it's okay to merge.

Thanks, Trond!

**Comment by iainfoulds** [comment]
@eross-msft This can merge, thanks

#sign-off

**Comment by eross-msft** [comment]
Thank you, all!

**Pull request merged**
