### PR TITLE
Delete wsus-tools.md

### LINKED ISSUE #4782: Outdated page/tools/docs need to be removed.
Hi,

the tools mentioned in this article are no longer available (error 404 on download) and no longer maintained. Could you please help remove this page? As some customers are asking about the broken downloads. There is an internal thread on this with WSUS PM Paul Reed.

An alternative would be:
The alternative is to use the WSUS API and build customer reports yourself:

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc720459(v=ws.10)?redirectedfrom=MSDN#use-wsus-apis-to-create-custom-reports

Thanks,
Andrei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21e853-8fa2-24d0-9806-75345cc12fd3
* Version Independent ID: 5397b0db-f1b5-fa63-df9c-112fb9672833
* Content: [Windows Server Update Services tools and utilities](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-tools?source=docs)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### LINKED ISSUE #4957: WSUS client diagnostic tools links to Forbidden page.
Page links to broken pages. ClientDiag.exe is nowhere to be found anymore.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21e853-8fa2-24d0-9806-75345cc12fd3
* Version Independent ID: 5397b0db-f1b5-fa63-df9c-112fb9672833
* Content: [Windows Server Update Services tools and utilities](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-tools)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

### LINKED ISSUE #5105: Client diagnostics tool: link not working
Client diagnostics tool: link not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21e853-8fa2-24d0-9806-75345cc12fd3
* Version Independent ID: 5397b0db-f1b5-fa63-df9c-112fb9672833
* Content: [Windows Server Update Services tools and utilities](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-tools)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in the following 3 issue tickets

- #4782 **Outdated page/tools/docs need to be removed.**
- #4957 **WSUS client diagnostic tools links to Forbidden page.**
- #5105 **Client diagnostics tool: link not working**

, the 2 linked tools on this page have been removed from public access since at least the beginning of September 2020, if not earlier.

The only 2 files still available are the Readme.htm files, but those are of no practical use at all without their installer .EXE files, seeing that they are descriptions of how to use the file contents (the .EXE files are apparently archive files containing client & server versions of the installers for those 2 software solutions).

**Suggested solution:**

- Remove the entire page, since it serves no practical purpose anymore. It is more like a historical relic and continues to be a source of additional frustrated users.

Quote from the first ticket (#4782) by @andreiztm :

> @vpaulreed has confirmed that we need to delete this page, as the tools are deprecated. Thank you.

**Additional notes:**

Andrei-George Stoica (@andreiztm) mentioned the following:
> An alternative would be:
> The alternative is to use the WSUS API and build customer reports yourself:
>
> https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc720459(v=ws.10)?redirectedfrom=MSDN#use-wsus-apis-to-create-custom-reports

To me, that does not appear to be a good replacement for the current content, so I would prefer to see a new page created by an expert on this topic, to cover the subject with up-to-date information and currently available tools with less chance of being removed with no notice.

**Ticket closure or reference:**

Closes #4782
Closes #4957
Closes #5105

### CODE REVIEW

**Comment by PRMerger14** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
GitHub page link: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md

Microsoft Docs link: https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-tools?source=docs

**Comment by illfated** [comment]
Looking forward to hearing your decision on this subject. This page removal is a first for me, so I don't expect this request to be taken lightly or even considered acceptable within the nearest future.

**Comment by eross-msft** [comment]
@illfated I've forwarded your summation to the product group, so we'll see what they say. I may not get a response before the new year as people are starting to take their holiday vacation.

**Comment by illfated** [comment]
@JeroenTuinstra & @jbostoen : Feel free to view, comment & discuss my suggestion in the meanwhile.

**Comment by illfated** [comment]
@eross-msft Oh. I see. Thank you for the info update. I didn't realize that the holidays are considered so close, but I guess it is in the timeframe of reviewing difficult Pull Requests.

**Comment by illfated** [comment]
Nice. Thank you for the quick decision! 🙂

BTW, I assume there was a file conflict I was unaware of, which has been solved by synchronizing this PR with the master branch?

**Comment by eross-msft** [comment]
@illfated  Seems like everything worked okay. Thank you so much for all of your efforts with this one....

**Comment by illfated** [comment]
Thank you. 😄 Yeah, well, this is one of those typical lingering tickets I just could not let go until I could find an working and applicable solution.

**Pull request merged**
