### PR TITLE
Update for new version history

### PR DESCRIPTION
**Pull request by anandyadavMSFT**

### CODE REVIEW

**Comment by anandyadavMSFT** [comment]
@billmath can yo take a quick look and review the version history changes for language concerns? Otherwise, I am good for sign-off

**Comment by billmath** [comment]
#sign-off

**Comment by anandyadavMSFT** [comment]
@billmath This change has not been merged to the master I guess. Can someone please merge it to master. The update on the software went live yesterday and the doc is now in an incorrect state as per the latest release.

**Comment by billmath** [comment]
Thanks Patti!

**Pull request merged**
