### PR TITLE
Update fsutil-wim.md

### PR DESCRIPTION
**Pull request by snickler**
Updated WIM backed file example to use proper syntax

### CODE REVIEW

**Comment by PRMerger7** [comment]
@snickler : Thanks for your contribution! The author(s) have been notified to review your proposed change. @toklima

**Review by illfated — APPROVED** [review]
Looks correct to me, based on the description in the 'Parameters' table.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @toklima, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is in agreement with the team members.

**Comment by snickler** [comment]
@toklima - are you able to take a look at this? :)

**Pull request merged**
