### PR TITLE
Fix #5869 - Add link to schema docs

### LINKED ISSUE #5869: Missing link to Schema docs
In the first point of the "Active Directory also includes:" section there is a reference to docs about "Schema" but there is no link.

The link that should be there is:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc756876(v=ws.10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bb772ec-10a8-1c86-8af7-5e1d51912866
* Version Independent ID: 743875a3-e418-d81f-1a70-474a3471bfcb
* Content: [Active Directory Domain Services Overview](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

### PR DESCRIPTION
**Pull request by Mr-M33533K5**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Mr-M33533K5 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @iainfoulds

**Comment by Yetoo1** [comment]
This was resolved in https://github.com/MicrosoftDocs/windowsserverdocs/issues/5869 with https://github.com/MicrosoftDocs/windowsserverdocs/commit/0ccf9cc7b5730a3352878cf2f5c9f0b3f59f83e0. Should this be closed?

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Xelu86** [comment]
Closing this issue as it has been resolved

**Pull request closed without merging**
