### PR TITLE
Update ntfs-overview.md

### PR DESCRIPTION
**Pull request by DBArgenis**
Updated maximum volume sizes along with NTFS allocation unit sizes supported in Windows Server 2019 and Windows 10, version 1809

### CODE REVIEW

**Comment by PRMerger10** [comment]
@DBArgenis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@DBArgenis : "This branch has conflicts that must be resolved" -- are you able to solve the file conflict on your own, or do you prefer to close this PR and open a new one when you have updated your repository to match the current Windows Server Docs [`master branch`](https://github.com/MicrosoftDocs/windowsserverdocs/tree/master) content?

**Comment by illfated** [comment]
@DBArgenis : Are you still online and checking this repository?

**Comment by illfated** [comment]
Please have a look at the 3 changes made to the same file by the MS Docs team members, especially on September 30 this year:

Commit History: https://github.com/MicrosoftDocs/windowsserverdocs/commits/master/WindowsServerDocs/storage/file-server/ntfs-overview.md

In order of succession (2 minutes between commits to the master branch):

- 84b09825f913ad70e9fe7902c591542c47d29ab3
- 47756370c61f3007b6f22d3c32fb9e16e2176cee
- a1f31e5a355a58bbd5f656b60cac1db7e0fa83ea

**Comment by illfated** [comment]
@DBArgenis : Any chance you will return to this PR?

**Comment by illfated** [comment]
No activity nor any reply for 2 months. Closing.

#please-close

**Pull request closed without merging**
