### PR TITLE
Update reference to Print Spooler guidance

### PR DESCRIPTION
**Pull request by ocdtrekkie**
When you click the original link, it just dumps you on the Ask Performance Team blog home page, not to the correct article. After some searching, I believe I found the correct reference. This PR updates the link appropriately.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@ocdtrekkie : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nirb

**Comment by ocdtrekkie** [comment]
@huypub As an active merger in this repo, can I ask if these PRs are blocked on a user who hasn't made a public contribution in over two years on GitHub?

I apparently duped #5671 but I had no idea because the PRs are all backlogged.

**Comment by huypub** [comment]
@ocdtrekkie I am the wrong person for your question. Please check with Femila Anilkumar <femila@microsoft.com>.

**Comment by ocdtrekkie** [comment]
@huypub Thanks for pointing me in the right direction, thank you!

**Pull request closed without merging**
