### PR TITLE
Update vpn-deploy-client-vpn-connections.md

### PR DESCRIPTION
**Pull request by msarcletti**
Add documentation for the limitation that rasphone.pbk cannot reside in a redirected folder.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@msarcletti : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me. I am sort of used to the idea of capitalized environment variables (like %AppData%), but that is simply a cosmetic detail.

(Note to myself: This page could use a codestyle cleanup after this PR is merged.)

**Review by Teresa-Motiv — APPROVED** [review]

**Comment by Teresa-Motiv** [comment]
#label:"sign-off"

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @Teresa-MOTIV, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Teresa-Motiv** [comment]
I tried before, but hit Return at the wrong time and it changed to something else. So I tried the other way instead.

**Comment by illfated** [comment]
Thank you for the information. Maybe it would be appropriate to ask someone else to merge that PR. Maybe @denisebmsft knows who the correct person would be. ( I also wrote another comment in the other PR to ask her for a follow-up. )

**Comment by denisebmsft** [comment]
@illfated @Teresa-Motiv I found a contact for this repository and emailed him. Expect help very soon!

**Comment by PRMerger20** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
