### PR TITLE
Update supported SQL Server versions

### PR DESCRIPTION
**Pull request by andreiztm**
Discussed internally, to help make this future/past proof for when new versions get introduced and old ones go out of support.

### CODE REVIEW

**Comment by andreiztm** [comment]
#hold-off could we please pause this PR for a couple of weeks? We are still evaluating the impact with the Devs and PMs. Thank you.

**Comment by andreiztm** [comment]
#sign-off discussed this with the WSUS PM and all good to publish.

**Comment by andreiztm** [comment]
Thanks @illfated

**Comment by illfated** [comment]
#sign-off

**Comment by vpaulreed** [comment]
@illfated - Can you let me know when this PR will be published?

**Comment by illfated** [comment]
Oh man, thanks for having faith in me. I am an outsider just like you to the MS Docs team, so I can only test asking either the page author or one of the known server docs team members. But yeah, sure, I can ping you once this has been merged.

**Comment by illfated** [comment]
@eross-msft : Please, may I ask you to assign someone to handle this PR?

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
@vpaulreed : As you can see, this PR has now been merged. It may take anything between 1-2 days and a week before the change shows up on the public page on docs.microsoft.com - just note that it usually takes just a few days to migrate.

**Comment by andreiztm** [comment]
Thanks everyone for the help! @illfated @eross-msft

**Comment by illfated** [comment]
(ref. "SQL 2017" #653)

**Pull request merged**
