### PR TITLE
Update the answer to show clarity

### PR DESCRIPTION
**Pull request by juntakata**
The original sentence did not answer the question directly. I added clarity to the answer.

### CODE REVIEW

**Comment by Court72** [comment]
@robinharwood, @Xelu86

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
#assign-reviewer: @robinharwood

**Comment by Court72** [comment]
#assign-reviewer: @Xelu86

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close

**Pull request closed without merging**
