### PR TITLE
Please provide AVMA Keys for Windows Server 2022 LTSC

### PR DESCRIPTION
**Pull request by Karl-WE**
while the generic client KMS setup keys have made available https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys 
the AVMA are missing. I understand you might want to create new folder for 2022 (analogue to the version picker for other Server / SQL
yet as 2022 is RTM and available as trial and visualstudio etc. you should "prerelease" the AVMA keys @EldenChristensen 

Added LTSC and SAC tags, as many are still confused about this and cannot seperate them correctly even though you wisely named them Windows server, version and not Windows Server

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by inntran** [comment]
Windows Server 2022 Datacenter AVMA key: W3GNR-8DDXR-2TFRP-H8P33-DV9BG

**Comment by Karl-WE** [comment]
Thanks inntran, do you have a MSFT source for this?

**Comment by inntran** [comment]
Does it matter?
Beside this, I don’t see a clearly defined feedback mechanism, allowing information flowing backwards from documents to product.
In my opinion, pull requests to this repo should be limited to documentation itself, it’s not the way telling the product team what you think they should do.
Joining MSFT or talk to your account manager will be a better solution.

**Comment by inntran** [comment]
In case you wondered, I discovered this key from the publicly available installation media. I posted it here only to help you and others who need it, before Microsoft updating its documents.

**Comment by Karl-WE** [comment]
I appreciate your help a lot @inntran. I hope they will include it in the PR for consistency. The 2022 docs are not yet out but as said the 2019 kms page does include 2022. 
@lizap thanks for your review and signoff

**Comment by Karl-WE** [comment]
I can confirm the key works

**Comment by PRMerger9** [comment]
@Karl-WE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dknappettmsft** [comment]
Hi @Karl-WE, thanks for submitting this PR. In this instance we have published a separate page for Windows Server 2022 (https://docs.microsoft.com/en-us/windows-server/windows-server-2022/get-started/vm-activation), rather than adding it to the existing page for now. As a result, I'll close this PR.

**Comment by dknappettmsft** [comment]
#please-close

**Comment by Karl-WE** [comment]
@dknappettmsft makes sense! thank you!

**Pull request closed without merging**
