### PR TITLE
Add quotes to message containing spaces and commas

### PR DESCRIPTION
**Pull request by stenci**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@stenci : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Good & valid point. I approve.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@illfated: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
I know, I know. But this is currently the only way to signal that this PR is ready for final review & merge.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
