### PR TITLE
Typo: line 17, "Window 10" -> "Windows 10"

### PR DESCRIPTION
**Pull request by Foxigod**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Foxigod : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Review by IngridAtMicrosoft — APPROVED** [review]

**Comment by IngridAtMicrosoft** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@IngridAtMicrosoft: I'm sorry - only the author of this article, @maertendmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by IngridAtMicrosoft** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@IngridAtMicrosoft: I'm sorry - only the author of this article, @maertendmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by IngridAtMicrosoft** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@IngridAtMicrosoft: I'm sorry - only the author of this article, @maertendmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by IngridAtMicrosoft** [comment]
Duplicate issue. #please-close

**Pull request closed without merging**
