### PR TITLE
WAC SDK/BiitOps: new URLs

### LINKED ISSUE #3506: Page Not Found
The URL links above "BiitOps Product Page" and "free trial" Product the below error

Page not found
No umbraco document matches the url '/solutions/changes-for-wac'.
This page can be replaced with a custom 404. Check the documentation for "custom 404".

This page is intentionally left ugly ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec743534-9a53-a1c3-a1fc-afe6e71be0d8
* Version Independent ID: bada4428-35ac-8c98-4b2b-d30df62128ca
* Content: [Windows Admin Center SDK Case Study - BiitOps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/case-studies/biitops#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/case-studies/biitops.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/case-studies/biitops.md)
* Product: **windows-server**
* Technology: **extend**
* GitHub Login: @daniellee-msft
* Microsoft Alias: **jol**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Based on the report in issue ticket #3506 (**Page Not Found**), the URLs in this page now redirect to only one of the intended pages (the site has been restructured and redesigned).

Thanks to Peter Van Eunen (@PeterVanEunen) for reporting the issue.

New links:

- https://biitops.com/solutions (instead of "Products")
- https://biitops.com/solutions/biitops-changes (instead of 'changes-for-wac')

**Ticket closure or reference:**

Closes #3506

### CODE REVIEW

**Comment by PRMerger19** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
URL updates only. Quite short document.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @daniellee-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
