### PR TITLE
Update command to etl2pcap from pcapng

### PR DESCRIPTION
**Pull request by alanjmcf**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@alanjmcf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@alanjmcf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@alanjmcf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by femila** [comment]
@robinharwood - this needs to be assigned to someone on Windows Server team

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by robinharwood** [comment]
Hi @alanjmcf, thanks for your contribution. I've taken you suggestion and consolidated it with the [pktmon etl2pcap](https://learn.microsoft.com/windows-server/administration/windows-commands/pktmon-etl2pcap) article. You should see this live within the next working days. In the meantime I've closed this PR as I can't use these commits against the other article.

Replaced by MicrosoftDocs/windowsserverdocs-pr#4221 (you won't be able view this PR).

Thanks,

Robin

**Pull request closed without merging**
