### PR TITLE
Update upgrading-to-ad-fs-in-windows-server.md

### PR DESCRIPTION
**Pull request by rotraves-microsoft**
Adjusting the title to match the content.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by eross-msft** [comment]
@rotraves-microsoft  Please change the slashes to "and". The sentences should both say, "Windows Server 2016 and 2019". After you make that change, I will go ahead and publish. Thanks!

**Comment by PRMerger16** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by eross-msft** [comment]
@rotraves-microsoft  Did you mean to close this?

**Comment by rotraves-microsoft** [comment]
I've closed the previous one. Sorry but I'm not that expert with Github and I thought that I was doing something wrong.



--- Rodrigo Travessa ---

**Comment by eross-msft** [comment]
@rotraves-microsoft  Github is definitely tricky. It sounds like you still want this change to go through. I'm not sure which one you mean by "previous", but I will re-open and publish this one for you.

**Comment by illfated** [comment]
(ref. #5186 )

**Pull request merged**
