### PR TITLE
Update Configure-AD-FS-Browser-WIA.md

### PR DESCRIPTION
**Pull request by rotraves-microsoft**
Command lines are incorrect. This has been a support case generator.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
(ref. #4867, #4394, #3816 )

**Comment by illfated** [comment]
(possibly related? issue ticket #4363)

**Comment by rotraves-microsoft** [comment]
Yes, it is related #4363

**Comment by rotraves-microsoft** [comment]
Yes, it’s the same issue.



--- Rodrigo Travessa ---

**Review by illfated — APPROVED** [review]
Looks good to me. Resolves 3 open + 1 closed issue ticket.

**Rich diff view**, for readability (although sideways scrolling is needed):
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5098/files?short_path=33c5106#diff-33c5106c3bb6e9df1cbd31d05338ebaaba0414a4620c7e6274d2ef2a508cf72a

**Review by billmath — APPROVED** [review]

**Comment by billmath** [comment]
#sign-off

**Comment by illfated** [comment]
Thanks. Happy to see your updates.

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
