### PR TITLE
Windows Commands/ping: minor grammar update

### LINKED ISSUE #3996: verb case tweak
Hello-
First, thanks for this resource.
In several of the above parameter descriptions, if I understand their intent correctly, the construction "Specifies that xxx is/are used..." should be changed to "Specifies that xxx be used..." (imperative rather than indicative case).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb04dc8-7ab3-71e9-9773-41c080b40109
* Version Independent ID: 435a4517-0c3f-6af6-d75d-faed7282c86a
* Content: [ping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/ping.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ping.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As discussed in issue ticket #3996 (**verb case tweak**), the intentions in the descriptive text can be made more clear by adjusting the sentence grammar.

Thanks to @EricUniqueUsername for requesting to have the text updated.

**Changes proposed:**

- Remove a redundant and duplicate occurrence of the word "protocol" in the Note blob
- Reduce the number of times the word "that" is used, it is used too often as a filler word.
- Add "to be" when the text refers to a future use of specific parameter values
- Add explanation for Time To Live (TTL) at first use / occurrence
- Add capitalization to the "Type Of Service" description
- Modify "Request messages use" to "Request message uses" as denoted by article (the)
- Replace "that corresponds" with "corresponding" to focus on the relation
- (... <sub>this list may be expanded, depending on future comments</sub> ...)

Comments and constructive suggestions are more than welcome.

**Ticket closure or reference:**

Closes #3996

### CODE REVIEW

**Comment by PRMerger13** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- [X] **Rich diff view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4963/files?short_path=d7133d9#diff-d7133d9183e19990ef5c7f56febd93cd9e89a41edcc094e32cacab646de64fb8 (makes it easier to review some of the grammar changes)
- [X] **Regular source view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4963/files

**Comment by illfated** [comment]
Feel free to comment and make suggestions for additional changes, or possibly improvements over the ones I have already added in the text.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by EricUniqueUsername — CHANGES_REQUESTED** [review]
I'm going to try to edit this, but I'm not sure how to proceed. When I go to the three-dot menu, "edit file" is greyed out for me.

**Comment by illfated** [comment]
Oh. Right. While not being the author of this PR, you need to look at the left edge of the document and note the placement of the blue box with a + sign in it. That is the indication that you can add a comment to that specific line. There is also the experimental (but usually working) feature of adding a suggestion in the comment, by using the keyboard combination Ctrl + G, to duplicate the selected line and edit it to complete your suggestion.

**Comment by illfated** [comment]
You know, I see the reasoning behind the language choices, but from my IT perspective, making some of those changes, takes away some of the meaning, even if it means that the sentence becomes more grammatically accurate. I do worry that the regular IT administrators may find themselves more lost than informed by 100% accurate language.

**Comment by PRMerger13** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EricUniqueUsername** [comment]
@illfated : Trond, I want to assure you that no native speaker of English will be confused by the proper use of the subjunctive, even if they might not employ it themselves. And I might add that the IT world runs best on precise syntax.
Just so you know where I'm coming from, my changes don't arise from a personal style opinion; they are definitely correct. I foolishly studied languages and translation, instead of something that might have earned me a living, such as programming. ;) I also worked as a translator and and did revisions (proofreading/correction) of English translations.
Eric

**Comment by illfated** [comment]
Thanks. Been there, done that. Didn't get the T-shirt, though.

**Pull request merged**
