### PR TITLE
Update server-core-roles-and-services.md

### LINKED ISSUE #5079: "Role Services included in Server Core" incorrectly lists Remote Desktop Virtualization Host as included
The documentation is incorrect: Remote Desktop Virtualization Host is _not_ included in Server Core. Please see https://docs.microsoft.com/en-us/windows-server/get-started-19/removed-features-19#features-we-removed-in-this-release: "Remote Desktop Connection Broker and Remote Desktop Virtualization Host in a Server Core installation"
 
This is a frustrating and costly documentation error when finding this out after deploying a Server Core cluster. The rationale of consistency for removing the feature also makes no sense: 

> "Most Remote Desktop Services deployments have these roles co-located with the Remote Desktop Session Host (RDSH), which requires Server with Desktop Experience; to be consistent with RDSH we're changing these roles to also require Server with Desktop Experience."

RDVH has _guest VMs_ running a GUI, not the host itself. This is completely different from a host running RDSH, which of course does require a GUI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6103ae47-7634-9ca9-aa94-200cddcda251
* Version Independent ID: 53da51a4-cd45-d56a-4c78-80d84a2e9473
* Content: [Roles, Role Services, and Features included in Windows Server - Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-roles-and-services)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-roles-and-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-roles-and-services.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @pronichkin
* Microsoft Alias: **artemp**

### PR DESCRIPTION
**Pull request by KarkDenUheldige**
**Description:**

As reported in issue ticket #5079 (**"Role Services included in Server Core" incorrectly lists Remote Desktop Virtualization Host as included**), the roles [Remote Desktop Connection Broker] and [Remote Desktop Virtualization Host] have been removed from Windows Server 2019 Core and can no longer be accessed without installing the Desktop Experience.

Thanks to @ryanhelmer for noticing and reporting this issue.

**Changes proposed:**

- create a wrapped note saying " (Removed in 2019 Core)\* "
- add the removal note for both roles (RDCB + RDVH) in the table
- add an asterisk at the end of the short text to indicate a further footnote
- add footnote about the 2 roles removed in Windows Server 2019 Core

**Ticket closure or reference:**

Closes #5079

### CODE REVIEW

**Comment by PRMerger19** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- [X] **Standard source view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5100/files
- [X] **Rich Diff (layout) view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5100/files?short_path=f187933#diff-f187933cf589b769c7442a4ffaabacc0ae81cff52f1a8dafe9fc91c1742bb214

**Comment by PRMerger14** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Sorry, it was a difficult day yesterday. I wasn't paying attention enough and made some mistakes in my branch updates.

**Pull request closed without merging**
