### PR TITLE
Remove PS tuning files and add redirects

### PR DESCRIPTION
**Pull request by sdwheeler**
Migrated the PowerShell tuning articles to the PowerShell-Docs repo

- WindowsServerDocs/administration/performance-tuning/powershell/index.md
- WindowsServerDocs/administration/performance-tuning/powershell/module-authoring-considerations.md
- WindowsServerDocs/administration/performance-tuning/powershell/script-authoring-considerations.md

Added redirection to point to new location.

@abasko89-ms Please help get this PR merged to live.

### CODE REVIEW

**Comment by abasko89-ms** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@abasko89-ms: I'm sorry - only the author of this article, @lzybkr, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by abasko89-ms** [comment]
@sdwheeler 

Making changes in ServerDocs is little odd. You need to use the private repo (windowsserverdocs-pr) versus the public repo (windowsserverdocs) when making changes (this article overviews the process). When you are ready to merge changes, you can leave a comment “#sign-off”. This will merge the PR.

**Comment by PRMerger19** [comment]
@abasko89-ms: I'm sorry - only the author of this article, @lzybkr, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by sdwheeler** [comment]
Closing. Will resubmit in private repo.

**Pull request closed without merging**
