### PR TITLE
Update upgrade-storage-spaces-direct-to-windows-server-2019.md

### PR DESCRIPTION
**Pull request by KarkDenUheldige**
**Description:**
This PR is based on the PR content from #2640 by Dave Kawula (dkawula), with additional typo corrections and rephrasing of some unclear sentences.

PR main comment by Dave Kawula, dated March 28, 2019:

> There are missing steps to this process. We are doing one live today and there are some important steps missing.

Thanks to @dkawula for contributing the original content in the first place.

Thanks also to Karl Wester-Ebbinghaus (@Karl-WE) for valuable discussions and advice in the originating PR.

**Changes proposed:**

- add the steps 3.v., 3.viii, and 3.x. (3.5., 3.8., and 3.10. in the source) in the first procedure section named "Performing an in-place upgrade while VMs are running"
- make typo and PS cmdlet grammar corrections to the added content
- modify some of the sentence phrases for readability and clarity
- add link to the PowerShell Docs  Set-VMSwitchTeam cmdlet page
- "PowerShell command" -> 'PowerShell cmdlet' (+ whitespace)

**Whitespace change(s):**

- add editorial blank line between metadata and the page title (H1)
- reduce redundant double spacing to single in numbered lists (5 lines)
- add whitespace around the em dash in cmdlet — note

I have made an effort to keep the changes to a minimum, to avoid drawing focus to more of the page than the main changes (3 steps).

(For reference: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/upgrade-storage-spaces-direct-to-windows-server-2019.md)

**Ticket closure or reference:**
Ref.  #2640

### CODE REVIEW

**Comment by PRMerger18** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Just noticed that I forgot to use the exact same indent (number of blanks) for the steps 3.10. — 3.13. , making them main steps 4. — 7. instead. Have to update this in a new commit before this is ready for review & merge.

**Comment by PRMerger7** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Added the critical spacing and some more precise comments in the main PR comment.

**Review by illfated — COMMENTED** [review]
To shorten review of the source content page, use **Hide whitespace changes**:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5157/files?w=1

For easier review of the changes in grammar and phrasing, use the **Rich diff view**:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5157/files?diff=unified&w=1&short_path=1787f34

**Comment by illfated** [comment]
The phrasing in the added content might need improvements, but since I am not a topic expert, I have only been able to phrase the sentences according to the best of my knowledge from managing a Windows 2016 Server in a production environment in a small business scenario, in addition to have a general affinity for English grammar and technical content readability. Feel free to suggest improvements if you have the expertise to see that additional changes are needed for clarity, however small they may be.

**Comment by Karl-WE** [comment]
Thank you for kudos and finalizing this PR @illfated  👍🏻

**Comment by illfated** [comment]
@femila: Will you be looking into the open Pull Requests some time in the near future?

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @robhindman, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
I know, I added the comment according to a previous agreement, including the recommendation to ignore comments like the one above.

**Pull request closed without merging**
