### PR TITLE
Changed "Domains Controller" to "Domain Controller"

### PR DESCRIPTION
**Pull request by joeemt**

### CODE REVIEW

**Comment by illfated** [comment]
Why did you close this PR? Unless you re-open it, or someone else creates a PR to correct the typo, it is unlikely that the typo will be corrected.

**Comment by joeemt** [comment]
I misunderstood and thought this had been committed. Reopening for re-evaluation and commit.

**Comment by illfated** [comment]
OK, I apologize for any inconvenience I created by using the "approved these changes" feature to say that I think it looks good.

What we need to wait for, is the Merge where this change is merged into the source page for the related docs.microsoft.com page.
The [Approve] feature is only meant as an extra method of signalling that this content may be ready for merging or at least final approval by the document manager.
Also, there will be _green_ check marks when a Microsoft team member with merge capabilities approves the content, whereas all other users without merge capabilities will have black check marks shown when using the Github [Approve] feature/function.

A more direct method of showing the document author & Microsoft document owner/manager that you are ready for a final review and merge, is to use the text

`#sign-off`

in its own comment without anything else present in that comment.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
