### PR TITLE
important information about log-only mode

### PR DESCRIPTION
**Pull request by rdiazel**
I am adding important information based on internal SE's questions

### CODE REVIEW

**Comment by eross-msft** [comment]
@billmath  Please confirm if this text is okay to merge. Thanks!!

**Comment by rdiazel** [comment]
I see this is still pending since feb

**Comment by billmath** [comment]
Verifying with engineering.

**Comment by billmath** [comment]
Checking with engineering

**Comment by billmath** [comment]
I have feedback from engineering and this needs to be update with what I added above.  I have created a work item for this.  This PR can be closed.

#please-close

**Comment by eross-msft** [comment]
Closing pull request.

**Pull request closed without merging**
