### PR TITLE
Update Formating for Doc "Migrating the WSUS Database from WID to SQL"

### PR DESCRIPTION
**Pull request by aydeisen**
- Put PowerShell cmdlets into Markdown codeblocks
- Separate steps into separate subsections
- Separate notes and examples into Alert blocks
- Added PowerShell cmdlet to section on Removing the WID Role

### CODE REVIEW

**Comment by lizap** [comment]
Thanks for this! I'm going to check the format changes prior to merging (by test trickery on my end, nothing interesting), but as soon as that's finished, we'll get these changes merged and published. Thanks!

**Comment by lizap** [comment]
Update - I ended up pulling your file directly into our private repo to fix some formatting issues (mostly spacing after notes - if you don't have a hard carriage return, everything gets included in the note) and issues with the art references. That files DOES include your contributions, and you'll see your avatar in the list of contributors. I'll add a link here when the changes are live. Thanks so much for your help with this!

**Comment by aydeisen** [comment]
Thank you.  I'm not concerned.  This document needs a lot of work, and I'm happy to contribute where I can

**Comment by lizap** [comment]
Here's the updated version: https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration

Again, seriously thanks for your help with this one.

**Pull request closed without merging**
