### PR TITLE
Update guarded-fabric-initialize-hgs-tpm-mode-bastion.md

### LINKED ISSUE #5099: missing important parameter on Initialize-Cluster powershell command for installing to existing forest
The PowerShell for the Initialize-Cluster command IS MISSING AN IMPORTANT PARAMETER:
-ClusterName "MyHGSClusterName"

without this, a random cluster name (number suffix) is inserted, and you will get a cluster operation terminated / error occured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae25db7-fa78-b9bd-463c-a6debe7387f9
* Version Independent ID: 9384ad42-9e6a-ecd6-b07f-7baf55cbe4eb
* Content: [Initialize the HGS cluster using TPM mode in a bastion forest](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @rpsqrd
* Microsoft Alias: **ryanpu**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Reported in issue ticket #5099 (**missing important parameter on Initialize-Cluster powershell command for installing to existing forest**) :

> The PowerShell for the Initialize-Cluster command IS MISSING AN IMPORTANT PARAMETER:

```PowerShell
-ClusterName "MyHGSClusterName"
```
> without this, a random cluster name (number suffix) is inserted, and you will get a cluster operation terminated / error occured.

Thanks to Ryan 'Skip' Johnson (@k3for) for noticing and reporting this documentation issue.

**Proposed changes:**

- add `-ClusterName "MyHGSClusterName"` to the PowerShell `Initialize-HgsServer` command line
- hyphenate prestaged -> pre-staged ; based on dictionaries and observed usage

**Ticket closure or reference:**

Closes #5099

### CODE REVIEW

**Comment by PRMerger17** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Sorry, I made some mistakes while trying to sort out my branches. Yesterday was particularly difficult for me and I did not pay attention closely enough.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, @heidilohr, @eross-msft, @jasongerend, @MicrosoftGuyJFlo, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Side note: When merging, please consider **squashing** this as 1 commit due to my merge sync with master, which contains a lot of commits already present in the master branch.

**Comment by illfated** [comment]
Scratch that. There are now 92 files in this PR, which makes it unmergeable, because I was only updating 1 document page.

**Comment by illfated** [comment]
Going to create a new PR in a day or so. (Not really sure when.)

**Pull request closed without merging**
