### PR TITLE
Update system-requirements.md

### PR DESCRIPTION
**Pull request by RAJU2529**
in this article ,   windows 10  is missing   so i  added 
i saw below link  **https://www.microsoft.com/en-in/p/windows-server-essentials/dg7gmgf0dvsz?cid=msft_web_collection&activetab=pivot:techspecstab**.
**CPU socket** is misleading, so we should change to **CPU Type**
Normally in motherboard components socket is refers to  Placing of processors  , there are different type of sockets ,from intel side LGA 2011, LGA 775, LGA 1356  like these

### CODE REVIEW

**Comment by illfated** [comment]
Please notice that the document (EssentialsDocs/get-started/system-requirements.md) has been updated after you created this PR, in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/c2463f0fae90597a2121f440719ae4ee41cf2123
(file link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/c2463f0fae90597a2121f440719ae4ee41cf2123#diff-bf70da4170fabdf061bc05f7f9c96b6b):
```diff
@@ -40,7 +40,7 @@ manager: dongill
  
   For more information about the hardware requirements, see the [Windows Server Catalog](https://www.windowsservercatalog.com/).
  
-  All server hardware should meet the requirements established for the  Windows Server 2012 R2 Logo Program for Systems. For more information, see [Windows Logo Program](https://msdn.microsoft.com/windows/hardware/gg487403.aspx).
+  All server hardware should meet the requirements established for the  Windows Server 2012 R2 Logo Program for Systems. For more information, see [Windows Logo Program](/previous-versions/windows/hardware/hck/dn641155(v=vs.85)).
  
  > [!IMPORTANT]
  > Dynamic disks are not supported on Windows Server Essentials.
  @@ -49,6 +49,4 @@ manager: dongill
  
  -   [Install Windows Server Essentials](../install/Install-Windows-Server-Essentials.md)
  
- -   [System Requirements for Windows Server Essentials](system-requirements.md)
- 
- 
+ -   [System Requirements for Windows Server Essentials](system-requirements.md)
```
Will you be able to update your PR content by resolving the file conflict, based on the changes I have shown and linked above?

**Comment by RAJU2529** [comment]
there is no edit option, no save option, I don't know what to do in this case.

**Comment by illfated** [comment]
Hmm, ok. Thanks for checking anyway. Maybe I should just make a PR from my own repository to your PR branch in your repo.

**Comment by illfated** [comment]
There you go. Please merge my PR https://github.com/RAJU2529/windowsserverdocs/pull/1 into your file to resolve the file conflict.

**Comment by illfated** [comment]
OK, thanks for merging my PR, but it seems that your PR needs to be rebased on the updated master branch, because it does not seem to recognize that the changes are already in the target document. I will make another attempt to merge MicrosoftDocs:master into your PR branch and then create a PR to update your repository.

**Comment by illfated** [comment]
See my merge/update PR https://github.com/RAJU2529/windowsserverdocs/pull/2 .

**Comment by illfated** [comment]
Thankfully, that worked, I am happy that it did. Very well.

**Comment by illfated** [comment]
About your PR comment content:
> CPU socket is misleading, so we should change to CPU Type
> Normally in motherboard components socket is refers to Placing of processors , there are different type of sockets ,from intel side LGA 2011, LGA 775, LGA 1356 like these

I don't know the factual details, but this could be a method of differentiating from the AMD CPU brand, as well as noting various CPU categories like "AMD Ryzen", "intel Kaby Lake" and so on.

**Comment by illfated** [comment]
#sign-off

**Pull request merged**
