### PR TITLE
Update always-on-vpn-enhancements.md

### PR DESCRIPTION
**Pull request by PeterSmithRedmond**
The thrid-party plugin part of the table was incorrectly formatted and showed up as a new column instead of a new row,

### CODE REVIEW

**Comment by PRMerger20** [comment]
@PeterSmithRedmond : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Good find, well done. Thank you for creating this PR to resolve that incorrect table formatting.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@illfated: I'm sorry - only the author of this article, @Teresa-MOTIV, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My comment above is in accordance with an agreement with the team.

**Review by Teresa-Motiv — APPROVED** [review]

**Comment by Teresa-Motiv** [comment]
#sign-off

**Comment by sethmanheim** [comment]
Looks like someone fixed this already, as https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements looks fine. If that's not the case, please re-open. #please-close

**Pull request closed without merging**
