### PR TITLE
Update ad-fs-risk-assessment-model.md

### LINKED ISSUE #3249: "eg" isn't a word
You might mean "for example".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39982e20-024e-01a1-22bd-77ae25d58979
* Version Independent ID: 60db3fbe-72a7-706a-14b2-83f0d3a24ece
* Content: [Build Plug-ins with AD FS 2019 Risk Assessment Model](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-risk-assessment-model#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-risk-assessment-model.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-risk-assessment-model.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
From issue ticket #3249 (**"eg" isn't a word**) :
> You might mean "for example".

Thanks to Jordan Mills (@jordanmills) for reporting the missed grammar check.

**Changes proposed:**

- replace "For eg," with 'For example,'
- replace "eg," with 'for example:' (inserted clause)
- clientid, resourceid -> clientID, resourceID
- repair a broken [!NOTE] blob by correcting curly brace to square bracket
- add syntax highlighting "csharp" for the `ThreatDetectionModule.sln` script
- add missing MD PS code block around one command line inside a Note blob
- add missing definite article "the" a couple of places, where missing
- add syntax highlighting for bash and PowerShell code blocks
- add missing colon and period dots where missing (grammar)
- Microsoft code style: use 'check box', not "checkbox"

**Whitespace changes:**

- add 12 pairs of missing MD indent marker compatibility spacing
- reduce double blank line between metadata and page title to single
- add 1 blank line after each fenced code block (standard), where missing
- reduce spacing in numbered/lettered list from 4 to 1 space (12 occurrences)
- add script indents: 4 blank spaces (standard C# code style) where missing
- add spacing in the last table to avoid link breakage and use MD table standards
- add blank lines before and/or after linked images/models, for alignment control
- add missing editorial blank line after H3 headings (2 occurrences)
- add spacing and left/center/left formatting to the table

**Ticket closure or reference:**
Closes #3249

### CODE REVIEW

**Comment by PRMerger8** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- **Normal source view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5153/files
- **Hide whitespace changes:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5153/files?w=1 (does not hide blank line changes, unfortunately)
- **Rich diff view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5153/files?w=1&short_path=8e2d7c1 (might be useful for reviewing the grammar edits)

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@illfated: I'm sorry - only the author of this article, @billmath, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Comment by PRMerger16** [comment]
@eross-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
