### PR TITLE
remove EOL Ubuntu releases, update repository configuration

### PR DESCRIPTION
**Pull request by konstruktoid**
- Remove End-of-Life releases
- Change `curl` to `curl -sSL` so we only catch errors
- Use `curl -sSL ... | sudo tee` instead of unnecessary `cp`
- Basic linting

ref #4663 
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by illfated** [comment]
#sign-off

**Comment by eross-msft** [comment]
@victorcheng7 for review

**Comment by eross-msft** [comment]
@konstruktoid  This has been reviewed by the product team. If you would address the issues pointed out above, we can get this published...thank you for your efforts!!

**Comment by konstruktoid** [comment]
Address the issued pointed out by @kelleymh 
https://github.com/MicrosoftDocs/windowsserverdocs/blob/837a9a7919404f79ecfd89d59594589d84031d19/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md

**Pull request merged**
