### PR TITLE
Update OpenSSH_KeyManagement.md

### PR DESCRIPTION
**Pull request by soyfrien**
By default the ssh-agent service is disabled. I added a step to allowing it to be manually started

### CODE REVIEW

**Comment by PRMerger6** [comment]
@soyfrien : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me. I approve of this addition.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @maertendmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
