### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by BrianWasTaken**
Please, I just randomly went into my browser to search batch files up and when I was scrolling, I saw something like [Click [Bing](https://bing.com) that little left bracket. I don't really know If I should be opening a PR but i guess it is what it is.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@BrianWasTaken : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrianWasTaken** [comment]
No problem! :heart:

**Review by illfated — APPROVED** [review]
Good typo correction, thank you for contributing. 👍🏻

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@illfated: I'm sorry - only the author of this article, @jasongerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is in agreement with the team members.

**Pull request merged**
