### PR TITLE
Converted toc.yml from existing toc.md

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by v-hearya** [comment]
Hi @ManikaDhiman - As requested the TOC has been converted into YAML. Please review.

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ManikaDhiman: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@v-hearya: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
