### PR TITLE
Update guarded-fabric-obtain-certs.md

### PR DESCRIPTION
**Pull request by vcozier**
typos

### CODE REVIEW

**Comment by PRMerger17** [comment]
@vcozier : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Nice. Well spotted. Good job. Thank you submitting the corrections. 🙂

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @rpsqrd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by rpsqrd** [comment]
#sign-off

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
