### PR TITLE
Update virtual-machine-recs.md

### PR DESCRIPTION
**Pull request by cshea15**
updated the medium and heavy workload types. Light and Medium were showing the same specs. Most customers are running teams and setting their specs to the light workload but that is not enough to handle all their users. Happy to discuss more if needed.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@cshea15 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Rich Diff view, for easier layout reading & review:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5544/files?short_path=f629e2f#diff-f629e2f340623ad4afe5e7056672c52438f4cdbb83d4c6c3eb7924a754e45556

Looks good to me, although I presume this also needs approval of the document author or manager.

**Comment by cshea15** [comment]
Yes i would think the author or manager would need to approve this.

**Comment by cshea15** [comment]
@Heidilohr Can you review this merge?

**Pull request merged**
