### PR TITLE
Update Configure-AD-FS-Browser-WIA.md

### PR DESCRIPTION
**Pull request by rotraves-microsoft**
Adjusting also the description so it can match the cmdlet's. How can we change the wiasupport.png file? I can share an example.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks correct & good to me.

**Comment by illfated** [comment]
Oh. Right. You asked how to change the existing image. I presume you can edit the image from its current location:
- https://github.com/MicrosoftDocs/windowsserverdocs/tree/master/WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA (directory)
- https://github.com/MicrosoftDocs/windowsserverdocs/tree/master/WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA/wiasupport.PNG

Maybe you should make the change in your current repository fork, to make it part of your current PR:
- https://github.com/rotraves-microsoft/windowsserverdocs/blob/patch-7/WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA/wiasupport.PNG

Notice the uppercase filename extension .PNG, which causes the image not to show here on GitHub, only showing properly on the docs.microsoft.com site. (This is a common image file issue in the entire MicrosoftDocs repository, since many images have been uploaded from Windows computers.)

**Comment by rotraves-microsoft** [comment]
@illfated , it seems that I don't have enough permissions to do it directly. Do you mind? How can I send the image to you?

**Comment by PRMerger19** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rotraves-microsoft** [comment]
Got it. Available here: https://github.com/rotraves-microsoft/windowsserverdocs/blob/patch-7/WindowsServerDocs/identity/ad-fs/operations/media/wiasupport.PNG

**Comment by PRMerger20** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rotraves-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rotraves-microsoft** [comment]
Image is also updated here: •	https://github.com/rotraves-microsoft/windowsserverdocs/blob/patch-7/WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA/wiasupport.PNG

**Review by illfated — APPROVED** [review]
- Rich diff view, replaced image file (image 1): https://github.com/MicrosoftDocs/windowsserverdocs/pull/5102/files?short_path=967f396#diff-967f396ae311271aa8de3bd3917c54a8c79c66f22de6214ef9ee80e3e3a86361
- Rich diff view, image 2 (other directory): https://github.com/MicrosoftDocs/windowsserverdocs/pull/5102/files?short_path=1020bf1#diff-1020bf194df74664222288556ae465159084176c551ed19b328904c8507b988f
- Rich diff view, image file 3 (yet another directory): https://github.com/MicrosoftDocs/windowsserverdocs/pull/5102/files?short_path=faff2ab#diff-faff2abecd37c440eb0dde6cc1a42673fdabe3e64808e7c23786dbbce72eadd3

Looks good to me. I presume image 2 and 3 are for use in other documents.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger18** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by illfated** [comment]
interesting. That is different to what I have seen earlier, but I guess that script is under development.

**Comment by rotraves-microsoft** [comment]
Need any other interaction from my end?

**Comment by illfated** [comment]
Not that I know of. I presume your PR content is ready for final review & merge.

**Review by eross-msft — APPROVED** [review]

**Comment by illfated** [comment]
@rotraves-microsoft : Notice the following message I get when I remove & rebuild (clone) my GitHub fork from web to my Windows 10 computer:

```
"C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress "https://github.com/illfated/windowsserverdocs" "C:/github/illfated/windowsserverdocs"
Cloning into 'C:/github/illfated/windowsserverdocs'...
POST git-upload-pack (475 bytes)
remote: Enumerating objects: 196757, done.
remote: Total 196757 (delta 0), reused 0 (delta 0), pack-reused 196757R
Receiving objects: 100% (196757/196757), 826.29 MiB | 1.08 MiB/s, done.
Resolving deltas: 100% (146029/146029), done.
Updating files: 100% (5995/5995), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA/wiasupport.PNG'
  'WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA/wiasupport.png'
Done

Press Enter or Esc to close console...
```

Any chance that the file with uppercase extension (.PNG) is unneeded or not in use at the moment?

**Comment by illfated** [comment]
See also the master branch directory content:
- https://github.com/MicrosoftDocs/windowsserverdocs/tree/master/WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA

image

**Comment by rotraves-microsoft** [comment]
That image is duplicated. I've added both with different extension because I was having some issues making it work.

--- Rodrigo Travessa ---

**Comment by illfated** [comment]
OK, I see. So the files have to be like that.

@konstruktoid : Based on your ticket & conversion PR in Windows ITpro Docs, would you be able to look up these details, without taking too much of your time?

**Comment by konstruktoid** [comment]
I can't really answer if the files have to be like that because the repo is kind of messy regarding duplicates, renames and forgotten files.

But regarding `wiasupport` it seems to have been corrected, since only `wiasupport.png` is used in the documentation and no `wiasupport.PNG` exists.

`wiasupport.png` does however exist in two different versions.

```
$ git grep -E 'wiasupport\.png|wiasupport\.PNG'
WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md:![WIA Support](../operations/media/Configure-AD-FS-Browser-WIA/wiasupport.png)
[tabd@VBYTABD-MAC:~/Git/tabd_local/Github/windowsserverdocs]$ find . -name 'wiasupport*' -exec sha1sum {} \;
236cf20ce690f50743b94314c8a2bff2f9c389df  ./WindowsServerDocs/identity/ad-fs/operations/media/wiasupport.png
b7ba9647a7e279d5fcaf5647e84c660d9a25ac4a  ./WindowsServerDocs/identity/ad-fs/operations/media/Configure-AD-FS-Browser-WIA/wiasupport.png
```

605 unused files were found,  see https://gist.github.com/konstruktoid/e3d8cb38b73a51936362a5255e2fcbac
Found using:
```
$ for img in $(find . -name '*\.PNG' -o -name '*\.png' | sed 's/.*\///g'); do if ! git grep -q "${img}"; then echo "${img}"; fi; done
```

Duplicate files:
```
$ find . -type f -name '*.png' -o -name '*.PNG' -exec sha1sum {} \; > /tmp/pngfiles && grep "$(sort /tmp/pngfiles | awk '{print $1}' | uniq -d)" /tmp/pngfiles
45388fc26694cdb6a234441d8f70bb2500c5fb7e  ./WindowsServerDocs/identity/ad-fs/development/media/Enabling-OpenId-Connect-with-AD-FS-2016/AD_FS_OpenID_8.PNG
45388fc26694cdb6a234441d8f70bb2500c5fb7e  ./WindowsServerDocs/identity/ad-fs/development/media/Custom-Id-Tokens-in-AD-FS/AD_FS_OpenID_1.PNG
e9f67d6ab6b0ce69357013fde6539603daba156a  ./WindowsServerDocs/identity/ad-fs/troubleshooting/media/ad-fs-tshoot-logging/ADFS_Audit_1.PNG
e9f67d6ab6b0ce69357013fde6539603daba156a  ./WindowsServerDocs/identity/ad-fs/technical-reference/media/Auditing-Enhancements-to-AD-FS-in-Windows-Server-2016/ADFS_Audit_1.PNG
613e22e82c183801b87ea718061b994a65f01d53  ./WindowsServerDocs/manage/windows-admin-center/media/launch-use-2.PNG
613e22e82c183801b87ea718061b994a65f01d53  ./WindowsServerDocs/manage/windows-admin-center/media/understand-extensions/solutions-ui.PNG
06d8c48bb955fb5c9439079b6693656c713d592a  ./WindowsServerDocs/get-started/media/front-page-video.PNG
06d8c48bb955fb5c9439079b6693656c713d592a  ./WindowsServerDocs/media/front-page-video.PNG
```

For refrence: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8829

**Comment by illfated** [comment]
Wow. Nice. That is quite a useful tool to find obsolete content. I will have to get back to this when I have finished cleaning up some mess I made in my own branches yesterday.

**Pull request merged**
