### PR TITLE
Added Airlock Secure Access Hub

### PR DESCRIPTION
**Pull request by daniestermann**
Please add Airlock Secure Access Hub as a product supporting AD FS. Thanks!

### CODE REVIEW

**Comment by PRMerger20** [comment]
@daniestermann : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@billmath : I could be mistaken, but I would think that adding external URLs in Microsoft Docs documentation pages should go through the appropriate partner program channels.

Are you available to confirm either my assumption or this PR content?

**Comment by daniestermann** [comment]
> @billmath : I could be mistaken, but I would think that adding external URLs in Microsoft Docs documentation pages should go through the appropriate partner program channels.
> Are you available to confirm either my assumption or this PR content?

I am product marketer at Airlock and we just wanted to list our product here. I am not sure which is the correct way to do this. 
Can you guide us @billmath?

**Comment by sethmanheim** [comment]
@billmath Is it OK to add this?

**Comment by sethmanheim** [comment]
Unable to receive approval for this, so unfortunately need to close. Please work through different channels if you still want this to be added. cc @billmath

**Pull request closed without merging**
