### PR TITLE
Typo: line 122: 10,0000 instead of 10,000

### PR DESCRIPTION
**Pull request by powellamaranth**
Currently(typo)):
(seconds × 1,000 × 10,0000)

Correct:
(seconds × 1,000 × 10,000)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@powellamaranth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by powellamaranth** [comment]
Currenlty(last value 10,0000 instead of 10,000):
To get the SystemClockRate value, you can use the following command and convert it from seconds to clock ticks by using the formula of (seconds × 1,000 × 10,0000):

Should be:
To get the SystemClockRate value, you can use the following command and convert it from seconds to clock ticks by using the formula of (seconds × 1,000 × 10,000):

**Review by Teresa-Motiv — APPROVED** [review]

**Comment by Teresa-Motiv** [comment]
#sign-off

**Comment by Teresa-Motiv** [comment]
The related PR has merged the fix, so this PR is no longer needed.

**Comment by Teresa-Motiv** [comment]
#close

**Comment by PRMerger5** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
