### PR TITLE
Update Configure-AD-FS-Extranet-Smart-Lockout-Protection.md

### PR DESCRIPTION
**Pull request by vydixit**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@vydixit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @billmath, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on an agreement with the team.

**Pull request merged**
