### PR TITLE
Fix incorrect separators option

### PR DESCRIPTION
**Pull request by SIkebe**
Missing hyphen
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir#parameters
image

### CODE REVIEW

**Comment by PRMerger16** [comment]
@SIkebe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Very good catch. Thank you for contributing to improve the docs. 👍🏻

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on a previous agreement with the team.

**Comment by SIkebe** [comment]
@JasonGerend Hi! What's the current status on this PR? Are there anything I should do before merging?

**Pull request merged**
