### PR TITLE
Add the "See Also" section with links to WSL FAQ

### LINKED ISSUE #5023: need to say how to uninstall too
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
As a suggested solution based on issue ticket #5023 (**need to say how to uninstall too**), I propose to add a "See Also" section, containing the **FAQ** and **Windows Subsystem for Linux Documentation** page links.

Thanks to @ladylazy9x for requesting a more direct way to find out how to uninstall WSL .

**Changes proposed:**
- add the "See Also" section title (MarkDown H2 heading)
- add a link to [Frequently Asked Questions about Windows Subsystem for Linux](https://docs.microsoft.com/windows/wsl/faq)
    - add indented link to the FAQ [How do I uninstall a WSL Distribution?](https://docs.microsoft.com/windows/wsl/faq#how-do-i-uninstall-a-wsl-distribution)
- add a link to [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/windows/wsl/install-win10)
- add a link to [Windows Subsystem for Linux Documentation](https://docs.microsoft.com/windows/wsl/)

**Ticket closure or reference:**
Closes #5023

### CODE REVIEW

**Comment by PRMerger17** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
**Rich Diff view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5148/files?short_path=b7f879c (to get an idea of the visual result)

**Comment by eross-msft** [comment]
@illfated  I would like to go ahead an approve this, but the indented See also bullet goes against our template. If you could remove the indenting from the link, I can go ahead and publish.

**Comment by PRMerger6** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Very well. There you go, changes applied.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
