### PR TITLE
Incorrect parameter name

### PR DESCRIPTION
**Pull request by tksh164**
`-UseAnyNetworkMigration` parameter does not exist on Set-VMHost cmdlet.

### CODE REVIEW

**Comment by illfated** [comment]
Target page on docs,microsoft.com: 
- https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/cluster-sets

**Comment by illfated** [comment]
@tksh164 : Would it be OK for me to suggest a MarkDown code fence with syntax highlighting around that PowerShell cmdlet?

**Comment by tksh164** [comment]
Use fenced code block to only this PR's code block? Or all code blocks on this article? This article uses the indent style code block to the entire article currently.

**Comment by illfated** [comment]
Fair point, well spotted, I forgot to check the rest of the article to see the style used in the rest of the page.
There is 1 single occurrence of existing fence-style code block syntax highlighting for PowerShell:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/4117/files#diff-4ec17f65ccadf6c54efc5898ffe8f76fL194-L207

That is the type of MarkDown I was thinking of using.

On the other hand, maybe I should make a new PR after your current change has been applied, because your factual correction is more important than my suggestion of format & style corrections.

There are also a couple of other formatting issues in the page, so it is likely more practical if I make a new PR later to improve those.

**Comment by illfated** [comment]
Sorry, I forgot to check if the link will scroll to the linked & highlighted portion of the document. It does not do so automatically. Here is how it looks:

image

**Comment by tksh164** [comment]
I like the fenced code block with syntax highlighting too. I am going to make a new pull request for code block changes.

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
@JohnMarlin-MSFT : May we have a final review from you to confirm & validate the content?

cc: @EldenChristensen

**Comment by JohnMarlin-MSFT** [comment]
Yes, this was a typo
     -UseAnyNetworkMigration
Should be 
     -UseAnyNetworkForMigration

**Comment by eross-msft** [comment]
@illfated @JohnMarlin-MSFT @tksh164  Hey all, is this ready to go? If so, I can go ahead and merge...just put # sign-off, without the space between the two, into these comments and I'll go ahead and publish.

**Comment by illfated** [comment]
Sure, I have already added my #sign-off earlier, so I presume you would like to see the same comment from one of the others you @mentioned .

**Comment by JohnMarlin-MSFT** [comment]
#signoff

**Comment by eross-msft** [comment]
@illfated  No, yours is fine. I just wanted to make sure the conversation was done. I didn't want to jump in too soon. I'll go ahead and publish.  @JohnMarlin-MSFT  Thank you!

**Pull request merged**
