### PR TITLE
Correct incorrect reference to figure 5

### PR DESCRIPTION
**Pull request by KevinNicholas**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@KevinNicholas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Figure 4: Storage Access Keys (updated reference)
Figure 5: Cloud Witness endpoint URL links (old (incorrect) reference)

Looks like a good correction to me. 👍🏼

**Comment by PRMerger19** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
