### PR TITLE
"Container Networking documentation" 404 update

### LINKED ISSUE #5374: Link of Container Networking Documentation is broken
The first link titled `Container Networking documentation` on the first line of the section titled "[Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/networking/sdn/contact-sdn-team#microsoft-docs)" is broken.

The broken link URL: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking

### PR DESCRIPTION
**Pull request by KarkDenUheldige**
**Description:**

https://docs.microsoft.com/en-us/windows-server/networking/sdn/contact-sdn-team#microsoft-docs

As reported in issue ticket #5374 (**Link of Container Networking Documentation is broken**),
the first link named "Container Networking documentation" in the section returns a 404 error.

Thanks to S. Raza Syed (srazasyed) for noticing and reporting the issue.

The main reason is that there is no index.md / index.html / index.yml page in that directory.

**Proposed change:**

- Replace the existing incomplete link with /architecture.md (/virtualization/windowscontainers/container-networking/architecture)

**Whitespace corrections:**

- Add missing editorial blank line between H2/H3 headings and their following text.
- Add editorial blank line between the metadata section and the H1 title line.

**Ticket closure or reference:**

Closes #5374

### CODE REVIEW

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@illfated: I'm sorry - only the author of this article, @AnirbanPaul, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
I know. My sign-off comment is based on an agreement with the team.

**Comment by PRMerger13** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change. @AnirbanPaul

**Pull request closed without merging**
