### PR TITLE
VMConnect: add Server 2019, grammar & codestyle

### LINKED ISSUE #4051: Can the "Applies to" be updated to include Windows Server 2019
This page also applies to Server 2019.

Also, should Windows 8 removed?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc50ab2-5b70-2b78-5345-cb261071fcc0
* Version Independent ID: c081e16d-cf9d-f9a7-e86c-80a38e33d211
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/en-gb/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
From issue ticket #4051:
>> This page also applies to Server 2019. Also, should Windows 8 (be) removed?
>
> So far as I can see, this is not resolved, in that Server 2019 has not been added?

Thanks to @doctordns for reporting and keeping the issue ticket alive.

**Changes proposed:**

- Add "Windows Server 2019" in the "**Applies to:** " list/line.
- Improve English grammar by removing overused "that" in the introductory description.

**Codestyle & whitespace:**

- Add editorial blank line between metadata and the page title (H1)
- Add editorial blank line after H2 headings (3 occurrences)
- Add missing MarkDown indent marker compatibility spacing in "> Applies to:"
- Normalize bullet point list spacing, from 3 spaces to 1 (7 occurrences)
- Simplify capitalization to only the first letter in "Applies to:"
- Add missing colon in "Applies to:"
- Add **bold** format to "Applies to:"

**Ticket closure or reference:**

Closes #4051

### CODE REVIEW

**Comment by PRMerger10** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
**Hide whitespace changes** (to make the page review length shorter):
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5277/files?diff=unified&w=1

**Rich Diff view** (for easier review of the effective changes):
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5277/files?diff=unified&w=1&short_path=2406c5d#diff-2406c5d6574b22a908918bdf129cd66b76810913bce6519c81decde902f556b1

**Comment by illfated** [comment]
By the way, I am uncertain if the main change (adding Windows Server 2019 in the Applies to list) calls for an update to the `ms.date` article date. Please confirm.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@illfated: I'm sorry - only the author of this article, @BenjaminArmstrong, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know, but this is according to a previous agreement with the team.

**Review by BenjaminArmstrong — APPROVED** [review]
#sign-off

**Comment by PRMerger7** [comment]
@BenjaminArmstrong, you can only sign off in the main PR conversation, not in review comments.

**Comment by illfated** [comment]
Fair enough. I sort of triggered him to do so by using the same keyword in my own comment.

**Pull request merged**
