### PR TITLE
Typo correction: See slso >> See also

### LINKED ISSUE #5024: See slso => See also
Hi there,

The section at the very bottom of the page should be titled "See **a**lso" instead of "See **s**lso"

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beddb54-a9ed-b53e-c8e1-152069c2c5c4
* Version Independent ID: 8aa0fe83-1e7f-3636-2122-477afd35a657
* Content: [Extend a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

### PR DESCRIPTION
**Pull request by illfated**
1 letter typo correction.

Reported in issue ticket #5024 (**See slso => See also**).

Thanks to @mehmetberber for finding and reporting this.

Closes #5024

### CODE REVIEW

**Comment by PRMerger6** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
#sign-off

**Comment by PRMerger6** [comment]
@illfated, you can only sign off in the main PR conversation, not in review comments.

**Comment by PRMerger7** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
