### PR TITLE
#300

### PR DESCRIPTION
**Pull request by lol768**
See #300

### CODE REVIEW

**Comment by daveba** [comment]
@billmath please take a look at this and let me know if the proposed change is correct.

**Comment by billmath** [comment]
Checking with engineering

**Comment by lol768** [comment]
Thanks both, happy to clarify if any reasoning is unclear but I think the linked issue illustrates my reasoning

**Comment by daveba** [comment]
@billmath Any update here?

**Comment by billmath** [comment]
Following up on this one.

**Comment by lol768** [comment]
Any news, @billmath ?

**Comment by billmath** [comment]
@lol768 Still checking on this.  I have a meeting with engineering today, so I should know more.

**Comment by billmath** [comment]
@lol768 I spoke with engineering and there are some specific changes they want me to make.  Instead of relaying them, I am going to open a PR on my end and submit the changes.  You should see an update by next week.  At this point, we can close this pr.  Thanks!

#please-close

**Comment by lol768** [comment]
> You should see an update by next week. At this point, we can close this pr. Thanks!

Is there a PR open for this now?

**Pull request closed without merging**
