### PR TITLE
Typo "Azure blob storage"→"Azure Blob Storage"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/windows-server/failover-clustering/manage-cluster-quorum

### CODE REVIEW

**Comment by PRMerger20** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Correct casing for this feature. Good change. Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know, but this is currently the only reliable way to indicate that the PR is ready for final review & merge.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
