### PR TITLE
Update AD-Forest-Recovery-Resetting-the-krbtgt-password.md

### PR DESCRIPTION
**Pull request by HMR18**
> [!IMPORTANT]
> If you intent to reset the Key Distribution Center Service Account password twice. You must wait 10 hours between the password resets.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@HMR18 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Duplicate of #4992

**Comment by eross-msft** [comment]
@illfated  Is this a duplicate that should be closed? Or do the previous changes still need to be made here?

**Comment by eross-msft** [comment]
This is being addressed in another PR. Closing this one.

**Pull request closed without merging**
