### PR TITLE
Adding steps to toggle storage maintenance mode

### PR DESCRIPTION
**Pull request by cpuck**
This is to address feedback from Dell regarding an issue they have experienced in some support cases that is mitigated by putting the disks in storage maintenance mode.  This code change has gone into HCI and WS 2022 to be automated in those OSes.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@cpuck : Thanks for your contribution! The author(s) have been notified to review your proposed change. @eldenchristensen

**Review by illfated — APPROVED** [review]
This makes a lot of sense. Looks good to me.

**Comment by cpuck** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@cpuck: I'm sorry - only the author of this article, @eldenchristensen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Seeing that @EldenChristensen has not had any activity on GitHub since July 2018, I presume someone else needs to be assigned the task of making a final review & merge.

@JasonGerend or @eross-msft : Do any of you know who is available to be assigned this PR?

**Comment by khdownie** [comment]
I am available.

**Comment by illfated** [comment]
Very well, sounds good to me. I will leave it in your hands to complete the follow-up.

**Review by khdownie — APPROVED** [review]

**Comment by khdownie** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@khdownie: I'm sorry - only the author of this article, @eldenchristensen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by khdownie** [comment]
@illfated I'm getting the same error as Chris. These are simple changes -- maybe I should make them in a separate PR and delete this one. I think that if I make the changes, I should be able to sign off.

**Comment by illfated** [comment]
Fair enough, although I don't know the exact details regarding your connection to the MS Docs team, so I don't know if that will make much difference (unless you are a team member with merging rights, which should make it easier). Please note that I am not a team member, nor employed by Microsoft, so I am unable to provide much assistance besides commenting and asking the MS Docs Server team members to look into this PR (which everyone else also could do, if they know who would be the correct user to ask for a follow-up to this PR).

**Comment by khdownie** [comment]
@illfated @cpuck I was able to merge these changes in a separate PR, so this PR can be deleted. Changes should be live with the next publishing run.

**Pull request closed without merging**
