### PR TITLE
Document two ellipsis display options in use

### LINKED ISSUE #7331: More than one ellipsis display option in use
There is only one ellipsis display option in the docs here:

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key

There are at least two ellipsis display options in use:

- `…` examples:
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/typeperf
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/tracerpt
- `...` examples:
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/copy
  - command line `help` and `/?` output:
    - `help copy`
    - `typeperf /?`
    - `tracerpt /?`

### PR DESCRIPTION
**Pull request by crisman**
Fixes #7331

### CODE REVIEW

**Comment by crisman** [comment]
There might be a style guide somewhere that says which should be in use, I don't know. If we are going to keep any of the single character (`…`) usage in the online docs we should have both documented as historical and command line documentation uses the three character version (`...`).

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Xelu86** [comment]
Investigating this for `copy` command.

**Comment by Xelu86** [comment]
Issue is not with copy command help display.

**Comment by Xelu86** [comment]
Closing as issue is with typeperf.md

**Pull request closed without merging**
