### PR TITLE
Add description for acronym (VDL)

### PR DESCRIPTION
**Pull request by tksh164**
`VDL` is not a general acronym, I think. So, it is need original spelling.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@tksh164 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JohnCobb1** [comment]
Hi @tksh164 Good call to define this acronym on first mention. In this case, the format should be "valid data length (VDL)" per this Microsoft source: https://docs.microsoft.com/en-us/windows/win32/fileio/file-streams

Please update your PR with this change, and then we can get it published. Thanks

**Comment by PRMerger14** [comment]
@tksh164 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by tksh164** [comment]
@JohnCobb1 Thank you for your comment. Done the update my PR. Thanks.

**Pull request merged**
