### PR TITLE
steps 1-8 repeated

### PR DESCRIPTION
**Pull request by thabaum**
Information for steps 1-8 repeated

### CODE REVIEW

**Comment by illfated** [comment]
To see why the repeating part of the numbered list went undetected for so long, check out the numbered list (16 points) in
- https://docs.microsoft.com/windows-server-essentials/migrate/migrate-windows-small-business-server-2011-essentials-to-windows-server-essentials

and remember that even if a numbered list in MarkDown contains numbers out of order, MarkDown will ignore the given numbers and show consecutive numbers as long as the list continues uninterrupted.

**Comment by illfated** [comment]
See also: #4082

**Comment by illfated** [comment]
See also: #4084, #4085

**Comment by thabaum** [comment]
I hated having to think I had to do these steps twice as well as the numbering issue found with the numbered list 1-8 twice in same document made 1-16 appear to the users view .  Thank you for merging and as always happy to help.

**Comment by eross-msft** [comment]
@thabaum  Thank you for catching those!!

**Pull request merged**
