### PR TITLE
Update manage-hyper-v-scheduler-types.md

### PR DESCRIPTION
**Pull request by doctordns**
Two changes:
1. Capitalised the title properly.
2 Removed future tense in this article to aid in readability.

### CODE REVIEW

**Comment by eross-msft** [comment]
@doctordns  Reminder: Please remove the title changes, the name is Hyper-V hypervisor schedule types, with only Hyper-V capitalized. Changing from future tense to present tense is a great change and I'll merge the updates after the titles are changed. Thank you!!

**Comment by doctordns** [comment]
I do not understand the request. I changed the article's title to capitalise the first letter in the title. That is how articles are titled. Why would you want to make the title inconsistent?

**Comment by eross-msft** [comment]
@doctordns  Thank you for changing the title back. We've actually moved away from titles having all capitals and have moved instead to only the first letter being capitalized; unless it's a branded product name, in which case we follow the branding no matter where it is in the title. So in this case, the product name is "Hyper-V hypervisor scheduler type"..meaning that we go with our rules about the branding. Therefore, the title would be, "Managing Hyper-V hypervisor scheduler types". 

I'll go ahead and merge your changes.  Thanks again for your contribution, it's much appreciated!

**Comment by doctordns** [comment]
OK - if that's your standard, then great, especially going forward good to know.

**Pull request merged**
