### PR TITLE
Volume Shadow Copy Service: LUN explained

### LINKED ISSUE #4804: Undefined Acronym LUN
LUN did not immediately come to mind when reading this article where it is used 43 times.  It would help to say Logical Unit Number (LUN) the first time it is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d7bd11a-e693-26a0-d374-5cfb1d2335d3
* Version Independent ID: bc9a2fb3-fa85-4ec0-8e0f-6e7c4906262b
* Content: [Volume Shadow Copy Service](https://docs.microsoft.com/en-us/windows-server/storage/file-server/volume-shadow-copy-service)
* Content Source: [WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As requested in issue ticket #4804 (Undefined Acronym LUN), this suggestion to explain the acronym LUN at first use in this document is based on the fact that almost all of the other pages using the acronym LUN contains at least one full explanation of the initials in the acronym, whereas this page does not.

Thanks to @jlroynet for pointing out this documentation issue.

**Suggestion:** add an explanation to the first sentence using "LUN":

- You need a fast recovery from data loss by restoring data to the original LUN or to an entirely new LUN that replaces an original LUN that failed. [original]
- You need a fast recovery from data loss by restoring data to the original Logical Unit Number (LUN) or to an entirely new LUN that replaces an original LUN that failed. [suggestion]

**Ticket closure or reference:**

Closes #4804

### CODE REVIEW

**Comment by PRMerger16** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
Only added the suggested acronym explanation, no other changes in this page at this time.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
