### PR TITLE
Clarification in Drives section

### PR DESCRIPTION
**Pull request by tmmarshall**
Clarification in Drives section to statement in non supported bullet re applicability to any storage devices used for Storage Spaces Direct.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@tmmarshall : Thanks for your contribution! The author(s) have been notified to review your proposed change. @eldenchristensen

**Comment by tmmarshall** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@tmmarshall: I'm sorry - only the author of this article, @eldenchristensen, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by tmmarshall** [comment]
Making change in pr repo

**Pull request closed without merging**
