### PR TITLE
Fix documentation related to Connection Broker under RemoteGuard scenario

### PR DESCRIPTION
**Pull request by vineelko**
Fix documentation related to Connection Broker under RemoteGuard scenario

### CODE REVIEW

**Comment by ChristianMontoya** [comment]
Hmm...can we change it to something like?
   Remote Credential Guard might still work via Remote Desktop Connection Broker in a single-instance environment and the DNS name matches the computer name.

**Comment by vineelko** [comment]
> Hmm...can we change it to something like?
> Remote Credential Guard might still work via Remote Desktop Connection Broker in a single-instance environment and the DNS name matches the computer name.

Reworded the change to the documentation.

**Comment by ChristianMontoya** [comment]
@vineelko : Sorry, one more change. Can you change it so it says
   where the DNS name matches the computer name.

**Comment by ChristianMontoya** [comment]
@lizap : Content looks good to me now. Can you please review for style?

**Comment by lizap** [comment]
It's a bit contradictory as it is - it's only supported in X scenario, but might work in y scenario? Could we say something like this instead? 

If you have a Connection Broker in a single-instance environment, and the DNS name matches the computer name, you may be able to use Remote Credential Guard, although this is not supported.

**Comment by ChristianMontoya** [comment]
@lizap That works with me.

**Comment by vineelko** [comment]
@ChristianMontoya @lizap Updated it

**Comment by lizap** [comment]
Thanks! Merging now.

**Pull request merged**
