### PR TITLE
Fix casing error in readme doc

### PR DESCRIPTION
**Pull request by mkyukov**
Fixed a small letter casing typo in readme.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@mkyukov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Well spotted, good job. Thanks for the typo correction.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @spatnaik, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
