### PR TITLE
Deploy Always On VPN: Restore Larger image Link

### LINKED ISSUE #3178: image size very small
The diagram at the top that shows the workflow process for the different scenarios is very small and cannot be clicked or enlarged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae99a07-be14-63a1-d5bb-1e92f9cde0b7
* Version Independent ID: ed219e40-9a0e-794b-110d-d82418d456e7
* Content: [Deploy Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md)
* Product: **windows-server-threshold**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

### LINKED ISSUE #3474: Image in article is unreadable
The image listed below this section is unreadable :

The following diagram illustrates the workflow process for the different scenarios when deploying Always On VPN:

Can someone please update the image so it's readable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae99a07-be14-63a1-d5bb-1e92f9cde0b7
* Version Independent ID: ed219e40-9a0e-794b-110d-d82418d456e7
* Content: [Deploy Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As pointed out in the issue tickets #3178 (**image size very small**) and #3474 (**Image in article is unreadable**), the workflow process image is too small for the text content to be read (even opening the image in a new browser tab to enlarge it, the text is pixelated and blurry, so one can barely guess what the text says anyway).

2 years ago, in 2018, there used to be a working HTML link from that very image in this page to the larger version of the same image (always-on-vpn-deployment-workflow.png), but some time during the last 2 years, this link has disappeared. This PR is an attempt to restore it.

Thanks to @LeonB87 (Léon) and @tomdan-MSFT for posting the issue tickets to make us aware of this image readability issue.

**Changes proposed:**
- Restore HTML link via MarkDown, point the Small image (-sm) to Large
- Add MarkDown compatibility spacing to the [!IMPORTANT] blob markers

**Ticket closure or reference:**
Closes #3178
Closes #3474

Also thanks to @shortpatti for posting an update in the above 2 issues regarding her incorrect remaining name in the article metadata, as she no longer is part of the team.

### CODE REVIEW

**Comment by illfated** [comment]
To observe the effective image link change, use the Rich Text diff view:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/3943/files?short_path=2095b87#diff-2095b87b5419e5503b813d502f9c2926

Regular file view is still useful to see the textual changes:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/3943/files

**Comment by illfated** [comment]
The metadata of this page is in need of updating with the current owner & manager of this topic. @shortpatti left Microsoft 2 years ago, but her name still lingers alone in some of the old articles.

**Comment by illfated** [comment]
#sign-off

**Comment by eross-msft** [comment]
@illfated  I'm unable to see the image in preview or from your diff view link. Can you try again? I'm not comfortable merging content without being able to see the change.
As far as changing the author metadata, there is no current author. At this time these articles are mostly crowd-sourced, such as by you, or opportunistically updated/edited by the product team.

**Comment by illfated** [comment]
Very well, fair enough. Regarding the image, the only real change I made is to make the original small image ( `always-on-vpn-deployment-workflow-sm.png` ) hyperlinked to the larger image ( `always-on-vpn-deployment-workflow.png` ) so it is possible to open the larger image by clicking on the smaller one.

See the following examples below:
***
My web page when using Rich diff view (https://github.com/MicrosoftDocs/windowsserverdocs/pull/3943/files?short_path=2095b87#diff-2095b87b5419e5503b813d502f9c2926):

image

***
After clicking the image above, the larger image appears:

image

**Comment by illfated** [comment]
Looking at it again now, it seems like there should be a text saying something like "Click the image to display a larger view".

I could go back to the older versions of this page with HTML coding to see if there are any remnants of such text there.

**Comment by illfated** [comment]
F.Y.I. the large image is also published to the docs.microsoft.com pages, same as the thumbnail image in the original page:
- https://docs.microsoft.com/windows-server/remote/media/always-on-vpn/always-on-vpn-deployment-workflow.png
- https://docs.microsoft.com/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment

**Comment by illfated** [comment]
(Ref. #3886 )

**Comment by illfated** [comment]
@eross-msft : I hope I was able to alleviate your issue of not seeing the image or hyperlink capability. If there still are any outstanding issues, please let me know.

**Comment by illfated** [comment]
Thank you for the merge. I really hope this will be of some help for IT-Pro users of this document out there.

**Pull request merged**
