### PR TITLE
Update configure-ad-fs-and-azure-mfa.md

### PR DESCRIPTION
**Pull request by lbusoi**
removed 

- Your on-premises environment is [federated with Azure AD.](/azure/active-directory/hybrid/how-to-connect-install-custom#configuring-federation-with-ad-fs)

The domain does not necessarily need to be federated this can be used to offer azure MFA for on prem AD FS federated applications

### CODE REVIEW

**Comment by PRMerger8** [comment]
@lbusoi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by billmath** [comment]
Checking with engineering.

**Comment by Court72** [comment]
@robinharwood, @Xelu86

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close

**Pull request closed without merging**
