### PR TITLE
Update break.md

### PR DESCRIPTION
**Pull request by npocmaka**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@npocmaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JohnCobb1** [comment]
Hi @npocmaka Suggest the following edits to your note if accurate for your review:

>[!NOTE]
  ​>Because the break command has no effect it is often used to create empty files or delete the content of an existing file as in the following example:

```
rem -- cleans the content of the file --
break>log
```

**Comment by PRMerger14** [comment]
@npocmaka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by npocmaka** [comment]
> Hi @npocmaka Suggest the following edits to your note if accurate for your review:
> 
> > [!NOTE]
> > ​>Because the break command has no effect it is often used to create empty files or delete the content of an existing file as in the following example:
> 
> ```
> rem -- cleans the content of the file --
> break>log
> ```

Thanks. The PR has been updated.

**Comment by PRMerger3** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
