### PR TITLE
Fix: 'Windows NT backup' to 'Windows Server Backup'

### PR DESCRIPTION
**Pull request by ShoheiS0**
Windows NT Backup -> Windows Server Backup

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ShoheiS0 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Good correction. I am pretty sure "Windows NT Backup" has not been available since 2007, for Windows Server 2003 / Windows Vista. **Windows Server Backup** is the correct current name.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@illfated: I'm sorry - only the author of this article, @johnmarlin-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. This is currently the only way we can notify that the PR is ready for final review & merge.

**Review by JohnMarlin-MSFT — APPROVED** [review]
Yes, this is correct.  Its been a while since it was changed to Windows Server Backup and should be this way.

**Comment by illfated** [comment]
Thank you for the approval. May I also ask you to post a comment containing the keyword `#sign-off` to automatically replace the **[do-not-merge]** label with the label **[ready-to-merge]** ? 🙂

**Comment by JohnMarlin-MSFT** [comment]
#sign-off

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
