### PR TITLE
Update software-restriction-policies.md

### PR DESCRIPTION
**Pull request by jsuther1974**
Clarify SRP is deprecated and should not be used.

### CODE REVIEW

**Comment by jsuther1974** [comment]
@JasonGerend - Any chance we can get this clarification to SRP availability published soon?

**Comment by jborsecnik** [comment]
@Xelu86, @robinharwood, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jsuther1974** [comment]
@vinaypamnani-msft - Can you help get this PR unstuck?

**Comment by vinaypamnani-msft** [comment]
#sign-off

**Comment by vinaypamnani-msft** [comment]
@JasonGerend can you get this PR merged please?

**Pull request merged**
