### PR TITLE
Fixes #5345 - typo configuraion configuration

### LINKED ISSUE #5345: Minor typo in article - "configuraion" (actual) vs. "configuration" (expected)
This is just a minor typo I stumbled upon while trying to understand DAX.
I'll submit a PR in a few moments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb4898b-ae8a-9831-b779-205deb32693e
* Version Independent ID: 0d831015-986a-ad21-84b1-793e94adf19f
* Content: [Understand and deploy persistent memory](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-pmem)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-pmem.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-pmem.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @adagashe
* Microsoft Alias: **adagashe**

### PR DESCRIPTION
**Pull request by SphinxKnight**
A straightforward fix for a minor typo.
Let me know if there is anything to change to follow contribution guidelines.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@SphinxKnight : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me. Good typo correction.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@illfated: I'm sorry - only the author of this article, @adagashe, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My comment is based on an agreement with the MS Docs team.

**Comment by illfated** [comment]
(Ref. #5345 )

**Comment by sethmanheim** [comment]
@SphinxKnight The merge conflict stems from this file (deploy-pmem.md) having been deleted in the main branch. So I am closing this PR as the file in question no longer exists.

**Pull request closed without merging**
