### PR TITLE
Renamed some command parameters

### PR DESCRIPTION
**Pull request by managaok0314**
The customer asks me to correct the appropriate name of some parameters.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@managaok0314 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Yes, these are all descriptive placeholder names, so I agree with these suggestions.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@illfated: I'm sorry - only the author of this article, @kaushika-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know, but there is currently no other alternative to get attention for PRs ready for final review & merge.

**Pull request merged**
