### PR TITLE
Updated links

### PR DESCRIPTION
**Pull request by larsiwer**

### CODE REVIEW

**Comment by lizap** [comment]
HI, Lars - thanks for these fixes! To prevent a merge conflict, I'm going to hold your PR until after the morning publication. I fixed the very last link in this article in a different PR. Because we changed the files differently, the changes will collide if not published one at a time. Look for your changes to be live after our afternoon run later today. Thanks!

**Comment by larsiwer** [comment]
Sounds great - thank you Liza!

**Comment by lizap** [comment]
Hey, Lars - just a follow up - your changes are live: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-hyper-v-security-in-windows-server

Thanks!

**Comment by larsiwer** [comment]
Thanks a lot!

**Pull request merged**
