### PR TITLE
Dual-Parity is Archival and Backup Only

### PR DESCRIPTION
**Pull request by PhilipElder**
No VDI there. Performance not there for that kind of workload.

### CODE REVIEW

**Comment by PhilipElder** [comment]
Trond,

I’m sure Cosmos Damian will verify for you?

Philip Elder MCTS
Microsoft High Availability MVP<https://mvp.microsoft.com/en-us/PublicProfile/4024277>
E-mail: PhilipElder@mpecsinc.ca<mailto:PhilipElder@mpecsinc.ca>
Phone: (780) 458-2028
www.CommodityClusters.Com<http://www.commodityclusters.com/>
Blog Site<https://blog.mpecsinc.ca/>
Twitter: MPECSInc<https://www.twitter.com/MPECSInc>
Skype: MPECS Inc.

Please note: Although we may sometimes respond to email, text and phone calls instantly at all hours of the day, our regular business hours are 8:00 AM - 5:00 PM, Monday thru Friday.

**Comment by illfated** [comment]
@PhilipElder : Thank you for your reply and advice. I saw "cosmosdarwin" in the page metadata and thought that might be the original author, since I have trouble locating "Cosmos Damian" anywhere in all of GitHub (except for in this page), so I think I will reach out to @cosmosdarwin and see if that works.

@cosmosdarwin : Could you assist us in verifying the correctness of the content and approving this PR?

**Comment by PRMerger13** [comment]
@PhilipElder : Thanks for your contribution! The author(s) have been notified to review your proposed change. @cosmosdarwin

**Comment by illfated** [comment]
@PhilipElder : I do not know why this PR has not received any follow-up yet. As an external contributor, I don't know much about the internal activities within the MS Docs team, other than I have been informed that @femila will continue where @eross-msft left off, as far as ticket & PR responses go. It would be very helpful to know whether @cosmosdarwin has any interaction with this repository. Also not sure whether it would be helpful to ask if @JasonGerend or @daveba knows whether this PR should be handled by someone else.

**Comment by sethmanheim** [comment]
Please file a new PR if these changes are still valid. We cannot resolve the merge conflict.

**Pull request closed without merging**
