### PR TITLE
Windows Commands/fsutil: symlinkevaluation typo

### LINKED ISSUE #4133: switched
R2R, R2L

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0003865-ce9a-117a-f2ff-7eeed387c213
* Version Independent ID: 4506e308-992a-237a-4ad6-5acc552a75fe
* Content: [Fsutil behavior](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-behavior)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil-behavior.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil-behavior.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #4133 (**switched**), the description for the table entry `symlinkevaluation` shows R2R and R2L as values for the opposite lines in the last 2 of the 4 description lines. See also my previous attempt to resolve this issue on April 6, 2020, in PR #4134 .

Thanks to @alysdexia for reporting this issue.

**Proposed change:**

- Make the parameter values R2R and R2L switch places to match their descriptions.

**Ticket closure or reference:**

Closes #4133

### CODE REVIEW

**Comment by PRMerger17** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change. @toklima

**Review by illfated — COMMENTED** [review]
Due to the frequent use of HTML tags in this part of the table, any changes after <ul><li>**1** - Local to local symbolic links, `L2L:{0|1}`</li></ul>

will be invisible in Rich Diff view, so only normal source code view is useful here. Even the GitHub page does not show the content of this table cell beyond this first line (but all of them show up on the docs.microsoft.com page).

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @toklima, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
