### PR TITLE
Update customize-http-security-headers-ad-fs.md

### PR DESCRIPTION
**Pull request by 21gs**
minor typo

### CODE REVIEW

**Comment by Yetoo1** [comment]
It appears this was resolved by https://github.com/MicrosoftDocs/windowsserverdocs/commit/3cd1d0175a94f55b83a2231a2a8e1091e21615cc.

**Comment by Jak-MS** [comment]
checking for merge conflicts

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Xelu86** [comment]
Hey @21gs,

Thank you for your contribution and participation. Updates to this documentation have been made via https://github.com/MicrosoftDocs/windowsserverdocs/commit/3cd1d0175a94f55b83a2231a2a8e1091e21615cc. We will now be closing this request.

Thank you and have a most pleasant day.

**Pull request closed without merging**
