### PR TITLE
Diagnostics Hub Standard Collector service text

### LINKED ISSUE #4164: Microsoft (R) Diagnostics Hub Standard Collector
Service description for this service is actually service description for Local Session manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d867f27-5abb-be93-6bad-13eaa2e57ca6
* Version Independent ID: 8e8d603f-f93f-57f2-dec2-098433885624
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server#feedback)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server**
* Technology: **techgroup-security**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #4164 (**Microsoft (R) Diagnostics Hub Standard Collector**), the service description text for this particular service on this page is copy-pasted from the preceding service "Local Session manager".

Thanks to @rlappsupport for reporting this documentation issue.

**Changes proposed:**
- Replace the current service description text with the correct one:
  "Diagnostics Hub Standard Collector Service. When running, this service collects real time ETW events and processes them."
-  Correct its name to "diagnosticshub.standardcollector.service"
- Correct its Startup type to "Manual" according to factual standard
- Rename row names in accordance with actual services.msc names (Service name, Description, Startup type)
- Swap order for the "Description" and the "Service name" rows
- Whitespace & Layout changes:
    - Remove all redundant end-of-line (EOL) whitespace (blanks)
    - Remove redundant blank lines at end-of-file (EOF)
    - Reduce blank line spacing to max 2 blank lines (from 3 or 4)
    - Standardize table layout spacing and borders of first column
    - Standardize cell layout for the blank header row (readability)

I realize that this PR contains a lot of changes and that it may take more time than usual for MS Docs team members to review it. My motivation for making so many changes is for this documentation to be as useful and valuable as possible, for both myself and others, using Microsoft Windows Server 2016 in current production scenarios.

**Ticket closure or reference:**

Closes #4164

### CODE REVIEW

**Comment by eross-msft** [comment]
@illfated  I'm trying to find the product group member that can confirm the technical content changes. As soon as I get sign-off, I'll merge this.

**Comment by illfated** [comment]
Thank you very much for the positive feedback. That is quite all right by me.

**Comment by illfated** [comment]
@eross-msft : Any luck yet with the search for a product group member to confirm the technical content changes? I am guessing "No", but felt like asking, just in case.

**Comment by illfated** [comment]
#sign-off

**Comment by eross-msft** [comment]
@illfated  I did find the right person to ask, but haven't heard back yet. I'll poke him again to see if I can get a response.

**Comment by eross-msft** [comment]
@illfated  Got approval for these changes. Will merge your content now. Thank you!

**Comment by illfated** [comment]
Thank you for merging the PR, now I get to clean out my old local fork branches on my PC and make new ones. 👍

**Pull request merged**
