### PR TITLE
Update robocopy.md

### PR DESCRIPTION
**Pull request by bryandam**
The /IM parameter was not documented and works differently than the /it parameter.  If you _always_ want Robocopy to overwite files in the destination you must use all three (/im /is /it) and there's forum post after forum post of people not understanding why just /is /it skipping files.  The descriptions I've added/changed here match Robocopy's own help output.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@bryandam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me. I was unaware of the distinction and specificity difference between "modified files" and "tweaked files", but the parameters are `/im` and `/it` for a reason.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@illfated: I'm sorry - only the author of this article, @jasongerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by bryandam** [comment]
> I was unaware of the distinction and specificity difference between "modified files" and "tweaked files", but the parameters are `/im` and `/it` for a reason.

Yea, I'm still not entirely sure what the difference is but after 3 hours of trying to figure out why files weren't being copied I can confirm that a difference exists.  'Tweaked' could probably use some explaining.

**Comment by PRMerger10** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
