### PR TITLE
Revert ""browser" to replace "bowser" in the disable SMB1 via GPP section"

### PR DESCRIPTION
**Pull request by illfated**
Reverts MicrosoftDocs/windowsserverdocs#4927

"bowser" is the actual name of the SMB1 service.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Deland-Han

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @Deland-Han, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by eross-msft** [comment]
@illfated  I'll revert, thank you for the quick catch.

**Pull request merged**
