### PR TITLE
corrected word and made bold sentence

### PR DESCRIPTION
**Pull request by RAJU2529**
as per user report #5593, so i corrected word and made bold sentence

### CODE REVIEW

**Comment by PRMerger9** [comment]
@RAJU2529 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dknappettmsft** [comment]
Hi @RAJU2529, thanks for submitting this PR. I've had a look at the changes you made and to get published it will need to fit our content guidance. Please can you remove the ## heading you added to the line, and replace the capital O with lowercase?

GitHub is also showing a change in line 77, but I can't see any difference.  I'll treat that as an anomaly unless you meant to make another change.

If you can make these changes to this PR, I can get it approved :)

Thanks.

**Comment by RAJU2529** [comment]
@dknappettmsft, I can't remove, please assign @JohanFreelancer9 , to send suggested changes to commit

**Comment by dknappettmsft** [comment]
Hi @RAJU2529, I'm not able to assign someone else unfortunately, so in this case I've made the change. It should be visible later today.  Thanks again for flagging it.

#please-close

**Pull request closed without merging**
