### PR TITLE
ADDS/Azure CLI: Configure DNS & second DC promo

### LINKED ISSUE #4917: Configure DNS before configuring the second domain controller
I just tried this procedure. When promoting the second server, it fails with error message "an active directory domain controller for the domain <testdomain.com> could not be contacted".

The fix is to configure the DNS on the VNet first before configuring the second server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0097c-668e-1d37-22b0-89d0bf649f8a
* Version Independent ID: 49ccfef6-05bb-9c93-5a05-a2e2fe632b3c
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

### PR DESCRIPTION
**Pull request by illfated**
As reported in issue ticket #4917 (**Configure DNS before configuring the second domain controller**), promoting the second server fails with the error message "An active directory domain controller for the domain <testdomain.com> could not be contacted" when trying to promote the second DC before the **Configure DNS** step has been performed.

Based on this feedback, I propose to move the [Configure DNS] paragraph up to before the [Configure the second Domain Controller] section, as well as adapting the first sentence text accordingly, to match the new sequence.

Thanks to @K-Dela-R for discovering and reporting this live example issue.

Closes #4917

### CODE REVIEW

**Comment by PRMerger7** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change. @iainfoulds

**Review by illfated — COMMENTED** [review]
This PR content can be viewed correctly using the **Hide whitespace changes** feature: https://github.com/MicrosoftDocs/windowsserverdocs/pull/4920/files?diff=unified&w=1 (regular view indicates that more of the text has been restructured than what has actually been moved).

**Comment by illfated** [comment]
OK, fair enough. We may just want the document author's approval for this change, in case the wording needs to be rephrased.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Oh. I see. I thought the "sign-off" was meant just to clarify that the PR author has completed all known required tasks and that the PR is ready to be handed over.

**Comment by eross-msft** [comment]
@illfated  Please ignore all of these messages from PRMerger aliases. I had to turn on some automation for this repo to help with labeling, and the side-effect was that these now jump in. You can just ignore them and continue to work directly with me. If you run into any issues where they are blocking you, please let me know and I'll help you around them. Thanks!! Liz

**Comment by illfated** [comment]
Thank you for the extra information. I was unaware of this change and will now do my best to avoid using the "sign-off" comment unless requested to do so.

**Comment by eross-msft** [comment]
@illfated  Go ahead and use the sign off tag, it's fine. You'll just get the message that I have to do something, too. You using the tag actually helps me so I know you feel confident that the text is fine and ready to go.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
