### PR TITLE
added new screenshot and removed 1.`1 added 1.2

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #4627 , so i removed 1.1 , added 1.2  and a new screenshot

### CODE REVIEW

**Comment by PRMerger13** [comment]
@RAJU2529 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@RAJU2529 : Do you think you will be able to resolve the file conflict by adapting the changes in the PR file content?

If not, I feel like this would be a good opportunity to talk about creating a new PR and add the new image file (with a proper name) to the `./images/.` folder (subfolder of the directory where this page document is stored).

**Comment by RAJU2529** [comment]
@illfated . Thanks for your information, unfortunately, I  don't have proper  access to store pictures under the ./imges/ folder.

**Comment by illfated** [comment]
@RAJU2529 : Thank you for the feedback. I am fairly certain that is because you have looked at the wrong version of the folder, not in your own PR branch, but in your copy of the master branch. Let me take a look and see if I can link the folder you **do** have access to.

**Comment by illfated** [comment]
Oh. I see. The required image already exists:
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/images/tls-12-registry-setting.png

DTLS 1.2 disabled

**Comment by illfated** [comment]
Never mind, I was looking at the TLS images, not DTLS.

**Comment by illfated** [comment]
Oh well. I decided to clone your patch-7 PR branch, both to add your image correctly with a usable name, and also to update it so you can resolve the file conflict by merging the MS Docs master branch into your patch-7 branch.

**Comment by illfated** [comment]
Sorry, it appears to be invalid to make a PR to your PR branch, so I can't help you after all. I can only create a new PR from myself to Microsoft. What I can do, though, is to set you as co-author.

By the way: Please note that you have got 2 Pull Requests with the same content, for this file.

**Comment by illfated** [comment]
(ref. #4632, #4627, #4731, #4737 )

**Comment by illfated** [comment]
There you go. PR #4988 is available for viewing, comments and suggestions. Take care of yourself and those near you.

**Comment by PRMerger15** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@sethmanheim: I'm sorry - only the author of this article, @justinha, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
