### PR TITLE
HGS cluster/TPM mode: URL 404 correction

### LINKED ISSUE #3925: Link broken
&lt;&lt;validating your HGS configuration&gt;&gt; LINK at the end is broken, this links appears in each setup mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fcd846e-32f9-c5c1-8522-582baac6240e
* Version Independent ID: 97308239-844e-9432-3580-34cad539bdee
* Content: [Initialize the HGS cluster using TPM mode in a new dedicated forest (default)](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default.md)
* Product: **windows-server**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Not the same URL as reported in issue ticket #3925 (Link broken), but at least this URL is clearly in need of a change (technet) to point to an existing page.

3.  Run [Initialize-HgsServer]

**Change proposed:**

- Old URL: https://technet.microsoft.com/library/mt652185.aspx
- New URL: https://docs.microsoft.com/powershell/module/hgsserver/initialize-hgsserver

**Ticket closure or reference:**

Closes #3925

### CODE REVIEW

**Comment by PRMerger10** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
This is a required link update to keep all the URLs in the page working as expected.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@illfated: I'm sorry - only the author of this article, @rpsqrd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
