### PR TITLE
Clarify installation, fix typos, add warnings

### PR DESCRIPTION
**Pull request by riverar**
Fixed:
* Clarified installation language in Server Core section
* Added warnings in each section about 60 day cert expiration
* Fixed up all references to Honolulu to be explicit -- Project Honolulu
* Removed warning about PowerShell auto-complete, completely irrelevant to Project Honolulu
* Removed reference to Chrome, expanded IE to Internet Explorer in spots

Overall language is still iffy, but at least it's usable now.

### CODE REVIEW

**Comment by coreyp-at-msft** [comment]
Hi Rafael,

Sorry it's taken a while to get back to you on this. We needed to investigate some of your revisions. 

We are able to merge this PR with the exception of this:

_**Removed warning about PowerShell auto-complete, completely irrelevant to Project Honolulu**_
 
We have had multiple customers report this issue with 100% repro.

Please replace that warning in your PR, resubmit, and then we should be good to go.

Thanks,
Corey

**Comment by riverar** [comment]
Hey @coreyp-at-msft, I'm sure they reproduced it but so does typing gibberish, trying to left-click with the right mouse button, and not being able to type with the keyboard flipped on your desk.

Having warnings on a product page for general computing issues seems out of scope.

**Comment by jwwool** [comment]
@riverar I don't think that typing the first few letter of a file name and pressing [tab] to autocomplete is equivalent to 

> typing gibberish, trying to left-click with the right mouse button, and trying to type with the keyboard flipped on your desk

In most cases, the .\ added by PowerShell autocomplete does not effect the outcome of the command, so I also disagree that this is a "general computing issue"

**Comment by riverar** [comment]
I don't agree but will defer to Microsoft team guidance here. 👍

- Re-added warning (and moved the bottom one up a bit to prevent two warnings in a row)
- Threw in a few back ticks and fixed a typo

**Comment by lizap** [comment]
I'm merging now - will pull into private repo and publish this afternoon.

**Comment by riverar** [comment]
Hey @lizap, how are "contributors" identified on the docs site? I don't appear there. If this is purely for employees, what's the point?

**Pull request merged**
