### PR TITLE
Just fixing a Typo ;)

### PR DESCRIPTION
**Pull request by PhilippRenner**
changed the contoso.con domain to a contoso.com domain, as listed in the picture.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@PhilippRenner : Thanks for your contribution! The author(s) have been notified to review your proposed change. @iainfoulds

**Review by illfated — APPROVED** [review]
Very good. Thank you for the typo correction. Looked a bit suspect there. 😄

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. Just doing it to signal that this PR is ready for final review & merge.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
