### PR TITLE
Update How-to-Configure-Protected-Accounts.md

### PR DESCRIPTION
**Pull request by HerbertMauerer**
add note for Rid-500 Administrator

### CODE REVIEW

**Comment by Court72** [comment]
@robinharwood, @Xelu86

Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by HerbertMauerer** [comment]
this is not published yet. Is there an ETA?

**Review by HerbertMauerer — COMMENTED** [review]
looks great.

**Comment by robinharwood** [comment]
Looks good merging now. #sign-off

**Pull request merged**
