### PR TITLE
"browser" to replace "bowser" in the disable SMB1 via GPP section

### PR DESCRIPTION
**Pull request by chadduffey**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@chadduffey : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Deland-Han

**Review by eross-msft — APPROVED** [review]

**Comment by illfated** [comment]
@chadduffey : Have you actually researched this subject? Because I have seen several of these attempts to change the name **bowser** to "browser" without any real research done beforehand. See some of these search results:
- https://www.bing.com/search?q=Microsoft+%22bowser%22+SMB1+name+site%3Amicrosoft.com
- https://github.com/MicrosoftDocs/windowsserverdocs/search?q=bowser+is%3Aissue&type=Issues
- https://github.com/MicrosoftDocs/windowsserverdocs/search?q=bowser&type=code

If you imply that the word "bowser" is not correct, you need to go back to Windows NT and change things 20 years ago.

**Comment by illfated** [comment]
#please-revert

**Comment by illfated** [comment]
Please see my PR to revert this change.

**Comment by chadduffey** [comment]
you're right. please revert. thanks for the quick response.

**Pull request merged**
