### PR TITLE
Update vpn-deploy-nps.md

### PR DESCRIPTION
**Pull request by lloydsmart**
Looks like the "Next steps" description needs amending as the existing one describes step 4, not step 5.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@lloydsmart : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks like a good correction to me. My only uncertainty is whether the phrasing of this last sentence of the page could benefit from more details. I defer to the page author for that consideration.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@illfated: I'm sorry - only the author of this article, @Teresa-MOTIV, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
I know. I just added that comment (as previously agreed) to get some attention to this PR.

**Comment by Teresa-Motiv** [comment]
Looking at this today.

**Review by Teresa-Motiv — APPROVED** [review]

**Comment by Teresa-Motiv** [comment]
Note: I've apparently become the "author" of a large number of files that I've never seen before (such as this one), and they have issues. Please be patient--I'm working through them between my regular projects.

**Comment by illfated** [comment]
@Teresa-Motiv : Thank you for the insight. May I trouble you with signing off this PR as well, just like my "incorrect" comment above?

**Comment by Teresa-Motiv** [comment]
#sign-off

**Comment by Teresa-Motiv** [comment]
#label:"sign-off"

**Comment by illfated** [comment]
Nice keyword feature. TIL

**Comment by Teresa-Motiv** [comment]
@eross-msft 
Do you know anyone who can merge this article? It's been sitting for a while.

**Comment by eross-msft** [comment]
@Teresa-Motiv  I believe @JasonGerend should be merging these weekly, but I went ahead and did this one for you.

**Pull request merged**
