### PR TITLE
AD DS/Audit Policy: increase tables' readability

### LINKED ISSUE #3580: Yes/No Table
The Yes/No tables took me way too long to interpret what "Yes Yes", "Yes No", etc meant. Maybe reformat the table using vertical lines between the columns or simply add a slash "/" between the columns so that the headers read "Success / Failure" and then the column contents read out like "Yes / Yes", "Yes / No", etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6aec18-46fe-37f4-995f-a98a65678e1f
* Version Independent ID: 519ae984-bcff-ec57-f855-c926b09ccdf2
* Content: [Audit Policy Recommendations](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As requested in issue ticket #3580 (**Yes/No Table**), table formatting should be applied in the best interest of making its contents as easily readable as possible, e.g. by aligning the values underneath their respective column headers in such a way that the table values are read as clear and precise.

Thanks to @CrCoTx for requesting the improvement.

**Changes proposed:**

- Center the content in all the values columns (Yes/No/X)
- Encapsulate the double values (Yes Yes/No No) in code block fences
- Add missing MarkDown indent marker spacing in the Applies To: line

Encapsulating the Yes/No values in code backticks will make the 4 spaces, between the values in the same column, appear as monospaced whitespace, as well as the values being displayed in a monospaced font.

**Ticket closure or reference:**

Closes #3580

### CODE REVIEW

**Comment by PRMerger19** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- [X] **Rich diff:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4966/files?short_path=0c72e45#diff-0c72e45c5a12a4855ee11bf7e0c4979f6195e54ca3f7dea28e6595f3b4c3cf59 (useful to preview the table changes, although not an accurate representation of the HTML pages on docs.microsoft.com )

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by eross-msft** [comment]
@illfated @CrCoTx  I'm not the author of this article, but it looks weird that there are 2 entries in a single field with only a single column/row label. Can you clarify why something would be doubled, like No No? Thanks!!

**Comment by illfated** [comment]
Thanks for commenting about there being 2 values in each row. Actually, I do not know exactly why there are 2 values for each table field, but that is the same information as in the original document. You may very well reach out to someone who is knowledgeable in this topic to get the information verified. I will be happy to make additional changes if they are called for.

**Comment by eross-msft** [comment]
@illfated Unfortunately, the writer for this area just left the team, so I don't have his insight. But looking at the article, I think I now understand, at least partly. The column heading is 2 different things: "Windows Default" and then "Success | Failure" and the two entries are one for success and one for failure. I still don't understand what the success and failure labels mean, but at least I'm understanding why there are 2 entries. If you can add a pipe between the various Success | Failure and Yes | No responses, we'll call it good for now. Hopefully someone will come on board and be able to help us understand this better in the future.

**Comment by illfated** [comment]
Good call, I agree with your decision. That is also more in line with what the ticket author is looking for, to make it easier to visually align the values with the column headers. I was trying to find a way to make the Success/Failure part of the columns a separate header row, but it does not seem like MarkDown will agree to display a different number of columns below a top header, so I am thinking maybe it would be just as useful to add the main texts in each column title, something like this:

**Audit Policy**

| Audit Policy Category or Subcategory | Windows Default<p>Success | Windows Default<p>Failure | Baseline Recommendation<p>Success | Baseline Recommendation<p>Failure | Stronger Recommendation<p>Success | Stronger Recommendation<p>Failure |
|---|:--:|:--:|:--:|:--:|:--:|:--:|
| **Account Logon** |  |  |  |  |  |  |
| Audit Credential Validation | No  |  No | Yes  |  No | Yes  |  Yes |
| Audit Kerberos Authentication Service | | | | | Yes  |  Yes |
| Audit Kerberos Service Ticket Operations | | | | | Yes  |  Yes |
| Audit Other Account Logon Events | | | | | Yes  |  Yes |
| **Account Management** | | | | | | |
| Audit Application Group Management | | | | | | |
| Audit Computer Account Management | | | Yes  |  No | Yes  |  Yes |
| Audit Distribution Group Management | | | | | | |
| Audit Other Account Management Events | | | Yes  |  No | Yes  |  Yes |
| Audit Security Group Management | | | Yes  |  No | Yes  |  Yes |
| Audit User Account Management | Yes  |  No | Yes  |  No | Yes  |  Yes |
| **Detailed Tracking** | | | | | | |
| Audit DPAPI Activity | | | | | Yes  |  Yes |
| Audit Process Creation | | | Yes  |  No | Yes  |  Yes |
| Audit Process Termination | | | | | | |
| Audit RPC Events | | | | | | |
| **DS Access** | | | | | | |
| Audit Detailed Directory Service Replication | | | | | | |
| Audit Directory Service Access | | | | | | |
| Audit Directory Service Changes | | | | | | |
| Audit Directory Service Replication | | | | | | |
| **Logon and Logoff** | | | | | | |
| Audit Account Lockout | Yes  |  No | | | Yes  |  No |
| Audit User/Device Claims | | | | | | |
| Audit IPsec Extended Mode | | | | | | |
| Audit IPsec Main Mode | | | | | IF   |  IF |
| Audit IPsec Quick Mode | | | | | | |
| Audit Logoff | Yes  | No | Yes  |  No | Yes  |  No |
| Audit Logon <sup>1</sup> | Yes  |  Yes | Yes  |  Yes | Yes  |  Yes |
| Audit Network Policy Server | Yes  |  Yes | | | | |
| Audit Other Logon/Logoff Events | | | | | | |
| Audit Special Logon | Yes  |  No | Yes  |  No | Yes  |  Yes |
| **Object Access** | | | | | | |
| Audit Application Generated | | | | | | |
| Audit Certification Services | | | | | | |
| Audit Detailed File Share | | | | | | |
| Audit File Share | | | | | | |
| Audit File System | | | | | | |
| Audit Filtering Platform Connection | | | | | | |
| Audit Filtering Platform Packet Drop | | | | | | |
| Audit Handle Manipulation | | | | | | |
| Audit Kernel Object | | | | | | |
| Audit Other Object Access Events | | | | | | |
| Audit Registry | | | | | | |
| Audit Removable Storage | | | | | | |
| Audit SAM | | | | | | |
| Audit Central Access Policy Staging | | | | | | |
| **Policy Change** | | | | | | |
| Audit Audit Policy Change | Yes  |  No | Yes  |  Yes | Yes  |  Yes |
| Audit Authentication Policy Change | Yes  |  No | Yes  |  No | Yes  |  Yes |
| Audit Authorization Policy Change | | | | | | |
| Audit Filtering Platform Policy Change | | | | | | |
| Audit MPSSVC Rule-Level Policy Change | | | | | Yes | |
| Audit Other Policy Change Events | | | | | | |
| **Privilege Use** | | | | | | |
| Audit Non Sensitive Privilege Use | | | | | | |
| Audit Other Privilege Use Events | | | | | | |
| Audit Sensitive Privilege Use | | | | | | |
| **System** | | | | | | |
| Audit IPsec Driver | | | Yes  |  Yes | Yes  |  Yes |
| Audit Other System Events | Yes  |  Yes | | | | |
| Audit Security State Change | Yes  |  No | Yes  |  Yes | Yes  |  Yes |
| Audit Security System Extension | | | Yes  |  Yes | Yes  |  Yes |
| Audit System Integrity | Yes  |  Yes | Yes  |  Yes | Yes  |  Yes |
| **Global Object Access Auditing** | | | | | | |
| Audit IPsec Driver | | | | | | |
| Audit Other System Events | | | | | | |
| Audit Security State Change | | | | | | |
| Audit Security System Extension | | | | | | |
| Audit System Integrity | | | | | | |

<sup>1</sup> Beginning with Windows 10 version 1809, Audit Logon is enabled by default for both Success and Failure. In previous versions of Windows, only Success is enabled by default.

**Comment by eross-msft** [comment]
@illfated That seems to work. The other option would be to just make smaller tables, so the single columns would still work. Basically, create a new table at each bolded row. I honestly don't know how important this content is...whether it's worth trying to refactor the whole thing, or just going with your update and calling it good. The only concern I see is that as you scroll down the page, you lose column headers, so towards the bottom, it would just show yes and no....

**Comment by illfated** [comment]
Indeed. I agree. I wish there was a "freeze headers" feature like in Excel or Atlassian/Confluence, but we should definitely aim for a shorter tables by splitting them wherever practical and repeat the headers to keep it readable.

**Comment by illfated** [comment]
This is how it looks when I split the individual tables and add the heading rows for each group (shown in collapsible content):

<details>
<summary>Audit Policy in grouped tables</summary>

<br/>

**Audit Policy Tables Legend**

|**Notation**|**Recommendation**|
|:--:|---|
|YES|Enable in general scenarios|
|NO|Do **not** enable in general scenarios|
|IF|Enable if needed for a specific scenario, or if a role or feature for which auditing is desired is installed on the machine|
|DC|Enable on domain controllers|
|[Blank]|No recommendation|

**Windows 10, Windows 8, and Windows 7 Audit Settings Recommendations**

**Audit Policy**

| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Account Logon** |  |  |  |
| Audit Credential Validation | No    No | Yes    No | Yes    Yes |
| Audit Kerberos Authentication Service |  |  | Yes    Yes |
| Audit Kerberos Service Ticket Operations |  |  | Yes    Yes |
| Audit Other Account Logon Events |  |  | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Account Management** |  |  |  |
| Audit Application Group Management |  |  |  |
| Audit Computer Account Management |  | Yes    No | Yes    Yes |
| Audit Distribution Group Management |  |  |  |
| Audit Other Account Management Events |  | Yes    No | Yes    Yes |
| Audit Security Group Management |  | Yes    No | Yes    Yes |
| Audit User Account Management | Yes    No | Yes    No | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Detailed Tracking** |  |  |  |
| Audit DPAPI Activity |  |  | Yes    Yes |
| Audit Process Creation |  | Yes    No | Yes    Yes |
| Audit Process Termination |  |  |  |
| Audit RPC Events |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **DS Access** |  |  |  |
| Audit Detailed Directory Service Replication |  |  |  |
| Audit Directory Service Access |  |  |  |
| Audit Directory Service Changes |  |  |  |
| Audit Directory Service Replication |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Logon and Logoff** |  |  |  |
| Audit Account Lockout | Yes    No |  | Yes    No |
| Audit User/Device Claims |  |  |  |
| Audit IPsec Extended Mode |  |  |  |
| Audit IPsec Main Mode |  |  | IF     IF |
| Audit IPsec Quick Mode |  |  |  |
| Audit Logoff | Yes   No | Yes    No | Yes    No |
| Audit Logon <sup>1</sup> | Yes    Yes | Yes    Yes | Yes    Yes |
| Audit Network Policy Server | Yes    Yes |  |  |
| Audit Other Logon/Logoff Events |  |  |  |
| Audit Special Logon | Yes    No | Yes    No | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Object Access** |  |  |  |
| Audit Application Generated |  |  |  |
| Audit Certification Services |  |  |  |
| Audit Detailed File Share |  |  |  |
| Audit File Share |  |  |  |
| Audit File System |  |  |  |
| Audit Filtering Platform Connection |  |  |  |
| Audit Filtering Platform Packet Drop |  |  |  |
| Audit Handle Manipulation |  |  |  |
| Audit Kernel Object |  |  |  |
| Audit Other Object Access Events |  |  |  |
| Audit Registry |  |  |  |
| Audit Removable Storage |  |  |  |
| Audit SAM |  |  |  |
| Audit Central Access Policy Staging |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Policy Change** |  |  |  |
| Audit Audit Policy Change | Yes    No | Yes    Yes | Yes    Yes |
| Audit Authentication Policy Change | Yes    No | Yes    No | Yes    Yes |
| Audit Authorization Policy Change |  |  |  |
| Audit Filtering Platform Policy Change |  |  |  |
| Audit MPSSVC Rule-Level Policy Change |  |  | Yes |
| Audit Other Policy Change Events |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Privilege Use** |  |  |  |
| Audit Non Sensitive Privilege Use |  |  |  |
| Audit Other Privilege Use Events |  |  |  |
| Audit Sensitive Privilege Use |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **System** |  |  |  |
| Audit IPsec Driver |  | Yes    Yes | Yes    Yes |
| Audit Other System Events | Yes    Yes |  |  |
| Audit Security State Change | Yes    No | Yes    Yes | Yes    Yes |
| Audit Security System Extension |  | Yes    Yes | Yes    Yes |
| Audit System Integrity | Yes    Yes | Yes    Yes | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Global Object Access Auditing** |  |  |  |
| Audit IPsec Driver |  |  |  |
| Audit Other System Events |  |  |  |
| Audit Security State Change |  |  |  |
| Audit Security System Extension |  |  |  |
| Audit System Integrity |  |  |  |

<sup>1</sup> Beginning with Windows 10 version 1809, Audit Logon is enabled by default for both Success and Failure. In previous versions of Windows, only Success is enabled by default.


**Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, Windows Server 2008 R2, and Windows Server 2008 Audit Settings Recommendations**

| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Account Logon** |  |  |  |
| Audit Credential Validation | No    No | Yes    Yes | Yes    Yes |
| Audit Kerberos Authentication Service |  |  | Yes    Yes |
| Audit Kerberos Service Ticket Operations |  |  | Yes    Yes |
| Audit Other Account Logon Events |  |  | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Account Management** |  |  |  |
| Audit Application Group Management |  |  |  |
| Audit Computer Account Management |  | Yes    DC` | Yes    Yes |
| Audit Distribution Group Management |  |  |  |
| Audit Other Account Management Events |  | Yes    Yes | Yes    Yes |
| Audit Security Group Management |  | Yes    Yes | Yes    Yes |
| Audit User Account Management | Yes    No | Yes    Yes | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Detailed Tracking** |  |  |  |
| Audit DPAPI Activity |  |  | Yes    Yes |
| Audit Process Creation |  | Yes    No | Yes    Yes |
| Audit Process Termination |  |  |  |
| Audit RPC Events |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **DS Access** |  |  |  |
| Audit Detailed Directory Service Replication |  |  |  |
| Audit Directory Service Access |  | DC    DC | DC    DC |
| Audit Directory Service Changes |  | DC    DC | DC    DC |
| Audit Directory Service Replication |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Logon and Logoff** |  |  |  |
| Audit Account Lockout | Yes    No |  | Yes    No |
| Audit User/Device Claims |  |  |  |
| Audit IPsec Extended Mode |  |  |  |
| Audit IPsec Main Mode |  |  | IF     IF |
| Audit IPsec Quick Mode |  |  |  |
| Audit Logoff | Yes    No | Yes    No | Yes    No |
| Audit Logon | Yes    Yes | Yes    Yes | Yes    Yes |
| Audit Network Policy Server | Yes    Yes |  |  |
| Audit Other Logon/Logoff Events |  |  | Yes    Yes |
| Audit Special Logon | Yes    No | Yes    No | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Object Access** |  |  |  |
| Audit Application Generated |  |  |  |
| Audit Certification Services |  |  |  |
| Audit Detailed File Share |  |  |  |
| Audit File Share |  |  |  |
| Audit File System |  |  |  |
| Audit Filtering Platform Connection |  |  |  |
| Audit Filtering Platform Packet Drop |  |  |  |
| Audit Handle Manipulation |  |  |  |
| Audit Kernel Object |  |  |  |
| Audit Other Object Access Events |  |  |  |
| Audit Registry |  |  |  |
| Audit Removable Storage |  |  |  |
| Audit SAM |  |  |  |
| Audit Central Access Policy Staging |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Policy Change** |  |  |  |
| Audit Audit Policy Change | Yes    No | Yes    Yes | Yes    Yes |
| Audit Authentication Policy Change | Yes    No | Yes    No | Yes    Yes |
| Audit Authorization Policy Change |  |  |  |
| Audit Filtering Platform Policy Change |  |  |  |
| Audit MPSSVC Rule-Level Policy Change |  |  | Yes |
| Audit Other Policy Change Events |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Privilege Use** |  |  |  |
| Audit Non Sensitive Privilege Use |  |  |  |
| Audit Other Privilege Use Events |  |  |  |
| Audit Sensitive Privilege Use |  |  |  |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **System** |  |  |  |
| Audit IPsec Driver |  | Yes    Yes | Yes    Yes |
| Audit Other System Events | Yes    Yes |  |  |
| Audit Security State Change | Yes    No | Yes    Yes | Yes    Yes |
| Audit Security System Extension |  | Yes    Yes | Yes    Yes |
| Audit System Integrity | Yes    Yes | Yes    Yes | Yes    Yes |


| Audit Policy Category or Subcategory | Windows Default<p>Success    Failure | Baseline Recommendation<p>Success    Failure | Stronger Recommendation<p>Success    Failure |
|---|:--:|:--:|:--:|
| **Global Object Access Auditing** |  |  |  |
| Audit IPsec Driver |  |  |  |
| Audit Other System Events |  |  |  |
| Audit Security State Change |  |  |  |
| Audit Security System Extension |  |  |  |
| Audit System Integrity |  |  |  |


</details>

<br/>

I admit that this is a much easier edit, but I would still prefer to add some way to distance the words "Success Failure" and "Yes No" a bit more to make the value correlations more obvious. When looking back at the originating ticket, https://github.com/MicrosoftDocs/windowsserverdocs/issues/3580, I notice that the ticket author suggested a possible use of the slash character ( / ) as a divider between the values, if the added column spacing is not an option.

**Comment by eross-msft** [comment]
@illfated  We could go with `Success | Fail`, the ticks will make it so that the pipe shows up. And then do the same thing at each row, so `Yes | No` or whatever. Again, not ideal since it changes the formatting, but I think it will LOOK more clear.

**Comment by illfated** [comment]
Thanks. I agree. That seems to be the most practical solution for now (until someone wants to use graphics instead of text, I guess).

**Comment by PRMerger18** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
`*sigh*`... I don't know quite what to say. It appears to be the case that GitHub Flavored MarkDown (GFM) treats pipe characters in a table as cell dividers, regardless of code fence backticks.

**Comment by illfated** [comment]
Oh. Right. I may just as well add an escape character for each pipe character I want to display as a vertical pipe `|` instead of a cell divider. Derp.

**Comment by PRMerger6** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
The rich diff looks a bit odd at the beginning and the end, because of the sizeable difference between the old tables and the new small grouped subcategory tables. Anyway, this is the rich diff view + Hide whitespace changes:
https://github.com/MicrosoftDocs/windowsserverdocs/pull/4966/files?diff=split&w=1&short_path=0c72e45#diff-0c72e45c5a12a4855ee11bf7e0c4979f6195e54ca3f7dea28e6595f3b4c3cf59

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
@eross-msft, thanks for merging the PR. 🙂 I was half expecting a suggestion to add a pipe character to the table headers too, between Success & Failure, maybe something like this:

| Windows Default<br>Success \| Failure |
| :---: |

Looks OK too, simply because of the escape character just before the pipe character. Oh well. I will keep an eye out for someone to request this feature sometime in the future.

**Comment by eross-msft** [comment]
@illfated  I was actually going to go in and make that change myself this week. I didn't feel right asking you to make any more updates 😊

**Pull request merged**
