### PR TITLE
removed  windows  path

### PR DESCRIPTION
**Pull request by RAJU2529**
as per user report #5312 , so i   removed the invalid path and added the correct path.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@RAJU2529 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MicrosoftGuyJFlo — APPROVED** [review]

**Comment by MicrosoftGuyJFlo** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@MicrosoftGuyJFlo: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by RAJU2529** [comment]
@PRMerger14 . When this PR #5314  will merge.

**Comment by illfated** [comment]
@RAJU2529 : I am fairly certain that @PRMerger14 is only a bot and will not respond to regular comments from users, unless they contain special commands or macros. I will do what I can to add some focus to this.

**Review by illfated — APPROVED** [review]
Looks good to me. Correct removal of directory name `\Windows` when `%windir%` is specified already.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@illfated: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My comment is based on an agreement with the MS Docs team.

**Comment by MicrosoftGuyJFlo** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@MicrosoftGuyJFlo: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
