### PR TITLE
Removed unnecessary blanks.

### PR DESCRIPTION
**Pull request by junhasems**
Removed unnecessary blanks.
These blanks inhibit the creation of links.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@junhasems : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by robinharwood** [comment]
#assign:robinharwood

**Comment by robinharwood** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@robinharwood: I'm sorry - only the author of this article, @billmath, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by robinharwood** [comment]
Thank you for your contribution, the changes will be visible later today.

**Pull request merged**
