### PR TITLE
Update Best-Practices-Securing-AD-FS.md

### PR DESCRIPTION
**Pull request by CanDagdelenatMS**
Instead of "/adfs/ls/federationmetadata/2007-06/federationmetadata.xml" should be "/federationmetadata/2007-06/federationmetadata.xml".

### CODE REVIEW

**Comment by PRMerger7** [comment]
@CanDagdelenatMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Yetoo1** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/commit/f869fe5dd4682bd67a353eb94b66392001d69900 appears to resolve this.

**Comment by Court72** [comment]
@robinharwood, @Xelu86

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close

**Pull request closed without merging**
