### PR TITLE
Fix missing space between bolded text and regular text

### PR DESCRIPTION
**Pull request by mikecnr**
Step 7 has a missing space between the 'features' and 'page' words, possibly not spotted due to the bold markdown. Also has a full-stop instead of a comma.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@mikecnr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Nice typo & formatting corrections, thank you. Good job.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on a previous agreement with the team.

**Pull request merged**
