### PR TITLE
Deploy DHCP/PowerShell: convert technet links

### LINKED ISSUE #3133: Many links still pointing to Technet
The links for the two commands Set-DhcpServerv4DnsSetting Set-DhcpServerDnsCredential still go to Technet. The proper links are https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverv4dnssetting?view=win10-ps and 
https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverdnscredential?view=win10-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe047b9e-1cef-6930-1473-a3e1a2a3b5f7
* Version Independent ID: 86bb5d90-1e18-f0a6-f688-d20d502c51a4
* Content: [Deploy DHCP Using Windows PowerShell](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-deploy-wps#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-deploy-wps.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-deploy-wps.md)
* Product: **windows-server-threshold**
* Technology: **networking-dhcp**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As mentioned in issue ticket #3133 (**Many links still pointing to Technet**), most of these links can now be found in the [docs.microsoft.com](https://docs.microsoft.com/) directories instead, most of them in the [/powershell/](https://docs.microsoft.com/powershell/) subdirectory.

Thanks to Marc Laflamme (@MarcLafLigado) for pointing out this rather obvious need for the links to be updated, ticket opened half a year ago, on July 22, 2019.
A couple of links were even broken already (local MS error 404), but with suggested search results pointing to the new pages.

Thanks to @ingd for reminding us.

**Changes proposed:**
- convert [technet.microsoft.com](https://technet.microsoft.com/) links to [docs.microsoft.com](https://docs.microsoft.com/) links
- add MarkDown compatibility spacing for MD Note blob indents

**issue ticket closure or reference:**

Closes #3133

**Additional notes:**
https://technet.microsoft.com/ : "The site will be moving soon. This content will be permanently redirected."

### CODE REVIEW

**Comment by illfated** [comment]
cc: @eross-msft , @brianlic-msft , @shortpatti

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
Hide whitespace changes to show only changes in the links: https://github.com/MicrosoftDocs/windowsserverdocs/pull/3683/files?w=1
(Rich diff is less useful here, it only shows the actual change in the Core Network Guide link.)

**Comment by MarcLaf** [comment]
Thanks for fixing this!

**Comment by illfated** [comment]
My pleasure. It was easier than I thought, so long as I was able to find the correct links.

**Comment by illfated** [comment]
Ref. #3465

**Pull request merged**
