### PR TITLE
Code formatting fixes & missing code bracket

### PR DESCRIPTION
**Pull request by bartbilliet**
- Fixed misformatted description text 'Now you should be able to F12...' It was wrongly formatted as a code block. 
- Fixed code formatting (indents + csharp/powershell markdown)
- Fixed missing ending class bracket in the section 'Next, the presentation form'
- Removed the reference to 'add the items in Italic below', as none of the text below was marked in italic. Updated to "add the following". 
- Removed "PS C:\>" for consistency in the flow of the document, it is not required for the reader to specify the directory the PS command was executed in. 
- \<fsname\> was missing due to missing escape characters. Added the markdown escape characters around <>
- Removed number 6 in 'Prepare the test AD FS machine' which had no text

### CODE REVIEW

**Comment by billmath** [comment]
Checking with engineering

**Review by illfated — APPROVED** [review]
Looks quite good to me, I see no reason not to approve this.

- [X] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4751/files?diff=unified&w=1 (simplifies the review process quite a bit, enough to realize that this is mostly formatting improvements)
- [ ] Rich diff view: https://github.com/MicrosoftDocs/windowsserverdocs/pull/4751/files?short_path=95188fd#diff-dc9cbfe7ebe6334623e9fc312bf83693 (only useful for confirming the layout of page elements, it can be more muddling to the reader than helpful for the review process)

**Comment by illfated** [comment]
#sign-off

**Comment by billmath** [comment]
Yes. looks good.  Please merge.

#sign-off

**Pull request merged**
