### PR TITLE
Update pktmon.md

### PR DESCRIPTION
**Pull request by george-guirguis**
updating the syntax since the tool just got updated. We need to create new pages for pktmon status, and pktmon hex2pkt

### CODE REVIEW

**Comment by PRMerger12** [comment]
@george-guirguis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@illfated: I'm sorry - only the author of this article, @khdownie, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment above is in agreement with the team.

**Comment by PRMerger12** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
