### PR TITLE
Adds if/else logic on firewalls and removes cmdlet alias

### PR DESCRIPTION
**Pull request by srjennings**
Two changes proposed:

- Use if/else logic for the firewall, to reduce errors
- Removes `?` alias for `Where-Object` to allow novices to better discern what the command is doing.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@srjennings : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@srjennings : Not quite sure how you managed to do this, but it looks like you opened this PR with a file conflict already present in the moment it got created.

Could it be that you edited a file in your own local repository instead of the MicrosoftDocs/windowsserverdocs master branch, before creating this PR?

Never mind, not important. Would you be able to resolve the file conflict, though?

**Comment by PRMerger14** [comment]
@srjennings : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by srjennings** [comment]
Not sure how that happened, but I've resolved the conflicts.

**Comment by illfated** [comment]
Thanks. This is much closer in terms of getting the content merged.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@illfated: I'm sorry - only the author of this article, @maertendmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on a previous agreement with the team.

**Comment by PRMerger5** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
