### PR TITLE
Windows Admin Center: initial documentation for Azure Extended Network extension

### PR DESCRIPTION
**Pull request by illfated**
Continuation of Pull Request #3868 by Greg Cusanza (grcusanz)

Check page #3868 for info, previous recommendations in particular.

Thanks to Greg Cusanza for authoring the content, Jason Gerend for followup, suggestions and clarifications,
and last, but not least, Elizabeth Ross for assistance and goodwill.

Signed-off-by: illfated <illfated@users.noreply.github.com>

### CODE REVIEW

**Comment by PRMerger20** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
Please note that this content is as close as possible to the combined efforts of Greg Cusanz and Jason Gerend in the previous PR.

If any content checking got discontinued in the previous PR, please check from the last chapter (**Troubleshooting**) and down the rest of this page.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @grcusanz, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by valar0213** [comment]
> @illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change. 

Your welcome who am I speaking with?

**Review by eross-msft — APPROVED** [review]

**Comment by illfated** [comment]
😄 @valar0213 : Thank you for making me smile. You are replying to a scripted bot (I was sort of hoping you were aware of this).

**Pull request merged**
