### PR TITLE
TLG Multisite Test Lab: replace assetid:/// links

### LINKED ISSUE #5270: Links to referenced documents don't work
Various links to documents referenced within the page take the form of assetid:///6cbee1b5-f6f6-443f-8fa9-31cc5c05a0ee which are not resolvable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb3f5fb-6a88-cb57-78c0-963c78a394ca
* Version Independent ID: 55d980df-e89d-615c-d1d3-d4ac2c0589fa
* Content: [Steps for Configuring the Test Lab](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/tlg-multisite/steps-for-configuring-the-test-lab-4)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/tlg-multisite/Steps-for-Configuring-the-Test-Lab-4.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/tlg-multisite/Steps-for-Configuring-the-Test-Lab-4.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

From issue ticket #5270 (**Links to referenced documents don't work**):

> Various links to documents referenced within the page take the form of assetid:///6cbee1b5-f6f6-443f-8fa9-31cc5c05a0ee which are not resolvable.

Thanks to @mrghostwalker for noticing and reporting this issue.

**Changes proposed:**

- Replace unresolvable assetId:/// links with the actual filename links

**Codestyle & whitespace:**

- Add editorial blank line between metadata and the page title (H1)
- Normalize spacing after the dash in bullet point lists, from 3 spaces to 1 (14 occurrences)
- Add missing MarkDown indent marker compatibility spacing (before "Applies To:")
- Remove redundant whitespace (empty lines) at end-of-file (EOF)
- Reduce double blank space to single (5 occurrences)

**Ticket closure or reference:**

Closes #5270

### CODE REVIEW

**Comment by PRMerger17** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
Maybe a bit unfortunate, but GitHub may not align the changes correctly in regular source view or "Hide whitespace changes" (which only hides the "Applies to:" line).

- **Rich Diff view** (for easier view of the effective changes): https://github.com/MicrosoftDocs/windowsserverdocs/pull/5273/files?short_path=7f81aa9#diff-7f81aa9cce5e6938371835bc5a355f0bc774ec0a95fd53f9377a93e180c2cb65

**Comment by illfated** [comment]
By the way, I was contemplating the removal of spacing between the bullet point list lines, but the document page is quite short and I did not find that change to be required.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know, but I am doing it according to a previous agreement.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
