### PR TITLE
Update AD-Forest-Recovery-Resetting-the-krbtgt-password.md

### PR DESCRIPTION
**Pull request by HMR18**
+> [!NOTE]
+> When resetting the Key Distribution Center Service Account password twice, a 10 hour waiting period is required between resets.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@HMR18 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Please note: Try to avoid verbatim copy-paste information from GitHub source code pages. The copy-paste process adds unwanted plus signs ( + + ) as the first character on the line when you paste.

I recommend that you follow up on your previous PR (even though it is not a bad training exercise to repeat the PR creation process) by going back to one of your previous attempts.

We also need to go through  the process of selecting which PRs to close and which one to keep. You have currently got the following open PRs to resolve the exact same issue:
- #4992 
- #4993 
- #4995 
- #5008 (this one right here)

**Comment by eross-msft** [comment]
I accepted a previous PR for this same fix. Since this is now a merge conflict, I'm going to close it.

**Comment by HMR18** [comment]
I saw that it has added, thank you very much for your support and help.

**Pull request closed without merging**
