### PR TITLE
Update configure-ad-fs-and-azure-mfa.md

### PR DESCRIPTION
**Pull request by RENAA-MS**
Adding line 143 to explain that if we want to use Azure MFA as an additional option, we need to intentionally select it. The process described in the documentation will just enable it for the primary one. We got a few support tickets in Authentication pod due to the lack of this info.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@RENAA-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JohnCobb1** [comment]
Hi @RENAA-MS Thanks for your input on this. I've edited your content per Microsoft guidelines. Please update the PR with the following version, and then we'll get it published:

If you want to use Azure MFA as a secondary authentication method, on the **Edit Authentication Methods** box, select the **Multi-factor** tab (the **Additional** tab in AD FS 2019) and ensure that it is enabled. Otherwise you might receive error messages, such as "No valid strong authentication method found. Contact your administrator to configure and enable an appropriate strong authentication provider".

**Comment by RENAA-MS** [comment]
Hi @JohnCobb1 
Thanks for reviewing this.
Honestly it is my 1st time suggesting a change in our public doc. So not sure how to proceed on github :)
If you don't mind please ping me via Teams (renaa) so I can learn with you.

**Comment by RENAA-MS** [comment]
Hi @billmath , truly sorry but I still need an assistance about how to follow John's guidance above. It should be something easy but I am not good in this tool. I am pinging you over Teams to learn more.

**Comment by PRMerger19** [comment]
@RENAA-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RENAA-MS** [comment]
Wow, great assistance sir! I believe I did it correctly now. Let me know if anything else is required.
Glad to participate in this content :)

**Comment by billmath** [comment]
Looks good.  Thanks!

#sign-off

**Comment by RENAA-MS** [comment]
Should I click on "Close pull request" now?

**Comment by billmath** [comment]
No, once it is merged it will turn purple/violet and say merged.  If you close it, it won't get merged.  We are waiting on the approvers to merge it now.  That may take a little while (couple of hours).  The next publish is not until 3:30 PST, so they have time.

**Comment by RENAA-MS** [comment]
I will keep an eye on this. Thanks for everything!

**Comment by RENAA-MS** [comment]
Hi Bill! I believe we are almost close to 24hr but no merges yet. Do you believe it will happen today 3:30PST again?
Sorry for pushing you, I am trying to finish this topic before vacation. Best regards.

**Comment by IngridAtMicrosoft** [comment]
Not sure why the reviewers haven't picked up this PR, but I am merging it.

**Comment by RENAA-MS** [comment]
Thanks a lot @IngridAtMicrosoft , @billmath and @JohnCobb1 .
I learned a lot from you all. Take care :)

**Comment by billmath** [comment]
Okay, looks like it was merged and it is now live.

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa#configure-the-ad-fs-farm

**Pull request merged**
