### PR TITLE
Update ad-ca-vpn-connectivity-windows10.md

### PR DESCRIPTION
**Pull request by SanDeo-MSFT**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@SanDeo-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Teresa-MOTIV

**Comment by MicrosoftGuyJFlo** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@MicrosoftGuyJFlo: I'm sorry - only the author of this article, @Teresa-MOTIV, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MicrosoftGuyJFlo** [comment]
@SanDeo-MSFT #please-close

**Pull request closed without merging**
