### PR TITLE
Update Configure-AD-FS-Extranet-Smart-Lockout-Protection.md

### PR DESCRIPTION
**Pull request by gagz02**
Update above changes on the doc as it's a bit confusing and contradicting.
Thanks

### CODE REVIEW

**Comment by PRMerger18** [comment]
@gagz02 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks good to me, makes sense to reference related adjectives instead of seemingly unrelated ones.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@illfated: I'm sorry - only the author of this article, @billmath, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on an agreement with the team.

**Comment by robinharwood** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your pull request in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made, although there have been further updates with subsequent releases which supersede the updates in your pull request. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by robinharwood** [comment]
#assign=robinharwood

**Comment by PRMerger10** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: =robinharwood

**Pull request closed without merging**
