### PR TITLE
Fixed link to blogpost - fixes #5670

### LINKED ISSUE #5670: Fix Link to Print Spooler Blogpost in Disabling System Services Security Guidelines
The link in the print spooler section should point to https://techcommunity.microsoft.com/t5/ask-the-performance-team/disabling-unnecessary-services-a-word-to-the-wise/ba-p/373444, but the automatic website porting stuff you guys have messed this—once again—up, so I had to figure this out via archive.org. Please fix. (I might even send a pull request if I get around to it…) #PrintNightmare

(btw.: the original author of that blog post wasn't Craig Marcho as the current page claims, the original author is the late Suhail "CC" Hameed, who unfortunately passed on in 2011.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d867f27-5abb-be93-6bad-13eaa2e57ca6
* Version Independent ID: 8e8d603f-f93f-57f2-dec2-098433885624
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server#print-spooler)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

### PR DESCRIPTION
**Pull request by no-identd**
Fixes https://github.com/MicrosoftDocs/windowsserverdocs/issues/5670 (can't fix #PrintNightmare tho)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@no-identd : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nirb

**Comment by PRMerger20** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change. @nirb

**Comment by sethmanheim** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@sethmanheim: I'm sorry - only the author of this article, @nirb, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
