### PR TITLE
intel CPU/Hyper-V VM: use case corrections

### LINKED ISSUE #4790: Multiple incorrect and missing requirement descriptions
Those should be corrected:
- The virtual machine generation must be 9.1 or higher. Otherwise, `Set-VMProcessor` command fails with the below message
```
Cannot modify processor setting 'EnablePerfmonIpt' without first upgrading the virtual machine version.
(Current version: 9.0. Needs version: 9.1).
```
- `An Intel processor that supports IPT and the PT2GPA feature.` needs clarification or can even be incorrect. 

PT2GPA is not a term used in the Intel Software Developers Manual, and needs clarification. I doubt this is incorrect information, as I was able to enable PT for a VM running on Coffee Lake processors. 

- PT cannot be enabled alone, and the description should clarify this

The below example gives and impression that PT can be enabled without enabling other performance monitoring features. 
`Set-VMProcessor MyVMName -Perfmon @("ipt")` 

This fails like this
```
> Set-VMProcessor "Win10 20H1" -Perfmon @("ipt")
Set-VMProcessor : Failed to modify device 'Processor'.
'Win10 20H1' failed to modify device 'Processor'. (Virtual machine ID
085DFF33-5CC4-4CB9-9681-4C28C8A44A79)
```

Instead, the page should instruct to run `Set-VMProcessor MyVMName -Perfmon @("pmu", "lbr", "pebs", "ipt")`  to enable PT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d511241-f09a-63d9-e95b-99a52d93a14c
* Version Independent ID: c5897e9d-b827-04be-f894-59acf1474cf7
* Content: [Enable Intel Performance Monitoring Hardware in a Hyper-V Virtual Machine](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/performance-monitoring-hardware)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Performance-Monitoring-Hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Performance-Monitoring-Hardware.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @ifeomaufondu-ms
* Microsoft Alias: **ifufondu**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #4790 (**Multiple incorrect and missing requirement descriptions**), the updates proposed in this PR are mostly a direct copy from the PR attempted by @ifeomaufondu-ms in their PR #4825.

Thanks to Satoshi Tanda (@tandasat) for reporting the issue(s) and to @ifeomaufondu-ms for the vetted PR content.

**Changes proposed:**

- Add footnote about PT2GPA and Intel PT in the Intel SDM.
- Add extra bullet point for "PMU needs to be enabled".
- Remove "Enable all components except IPT" cmdlet, unusable.
- Add Note blob for VM gen. 9.1 / 9.3 requirements.
- Update "Enable IPT" cmdlet to include required 2nd parameter.
- Update "Enable all components" cmdlet to include all 4 parameters.
- Update last Note blob to include missing requirement.
- Update ms.date to Wednesday November 11, 2020

**Whitespace changes:**

- added editorial blank line between metadata & page title
- added editorial blank line before the last Note blob
- added 2 readability line breaks in the last Note blob
- added 2 missing period dots to the original PR content
- added missing NewLine at end-of-page/end-of-file

**Ticket closure or reference:**

Closes #4790
Ref. closed PR #4825

### CODE REVIEW

**Comment by PRMerger17** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- [X] **Normal source file view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4984/files
- [X] **Rich diff view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4984/files?short_path=27db199#diff-27db199117aee5917bf44f140fddddc4414e22aa8afbca5cfb2a136bc3f69fb9

("Hide whitespace changes" is not any different to normal source view, because there are no independent whitespace change besides extra blank lines)

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @ifeomaufondu-ms, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger6** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@illfated: I'm sorry - only the author of this article, @ifeomaufondu-ms, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ifeomaufondu-ms — APPROVED** [review]

**Comment by illfated** [comment]
Thank you very much for the approval. May I also ask you to post a comment containing only "#sign-off" (without quotations) to update the PR labels? 🙂

**Comment by ifeomaufondu-ms** [comment]
sign-off

**Comment by illfated** [comment]
Sorry for being unclear. See [my comment above](https://github.com/MicrosoftDocs/windowsserverdocs/pull/4984#issuecomment-736083780), containing the # hashtag as well, as part of the comment:

image

**Comment by PRMerger14** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Sorry, it was a difficult day yesterday. I wasn't paying attention well enough and made some mistakes in my branch updates.

**Comment by tandasat** [comment]
@illfated @ifeomaufondu-ms Can you complete review and push it, please?

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @ifeomaufondu-ms, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
I know. My sign-off comment is in agreement with the MS Docs team, to give this PR a bit more attention from its assignee(s).

**Comment by illfated** [comment]
@tandasat : Thank you for bringing this PR back to my attention, I have been wondering whether I would need to create a new PR and abandon this one.

@ifeomaufondu-ms : May I ask you to sign off this PR again, due to my erroneous closing (and reopening) back in December 2020?

**Review by ifeomaufondu-ms — APPROVED** [review]

**Review by ifeomaufondu-ms — APPROVED** [review]
#sign-off

**Comment by PRMerger16** [comment]
@ifeomaufondu-ms, you can only sign off in the main PR conversation, not in review comments.

**Comment by illfated** [comment]
@ifeomaufondu-ms : Sorry about that detail. May I ask you to post a regular comment, here in the comment thread, containing the keyword #sign-off ?

Doing so will replace the PR label **[do-not-merge]** with the label **[ready-to-merge]**.

Thank you very much for your time.

**Comment by PRMerger18** [comment]
@illfated: I'm sorry - only the author of this article, @ifeomaufondu-ms, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. I only did so to make sure I was being clear about the keyword usage. Thank you.

**Comment by ifeomaufondu-ms** [comment]
#sign-off

**Comment by tandasat** [comment]
@illfated Can you tell me when will this be merged and publicized? Obviously I am not in a rush etc, but do not wish that this improvement is forgotten indefinitely.

**Comment by illfated** [comment]
@tandasat: Good question, wish I knew. Sometimes, there simply is not enough people around to do the jobs we need to be done. This is the case for the Microsoft Docs Windows Server team. They have got way too much to do, I don't think they will ever get as close as we would like to the bottom of this pile of issue tickets and Pull Requests. All we can do is hope that it won't take another year before this gets looked at.

@ifeomaufondu-ms , @JasonGerend , @eross-msft , @jaimeo , @billmath , @Justinha , @khdownie :
Do any of you know if it will be possible to continue using this Pull Request, or should I close this one to open a new one with identical content?

**Comment by JasonGerend** [comment]
Sorry for the delay - this is merged now. Thanks again for your contributions!

**Comment by illfated** [comment]
Thank you for returning. Happy to see you again. 🙂

**Pull request merged**
