### PR TITLE
Fixes #4819

### LINKED ISSUE #4819: How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows
This page (**_How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows_**) is using a mix of Dashes "-" (0x2d) and EnDashes "–" (0xE2,0x80,0x93) for PowerShell arguments. EnDash returns incorrect results when it is copy-pasted in PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#summary)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

### PR DESCRIPTION
**Pull request by exchange12rocks**
By replacing EnDashes in PowerShell commands with regular dashes.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@exchange12rocks : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
(ref. #4819 )

**Review by illfated — APPROVED** [review]
Good job, well spotted (or detected in testing). Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@illfated: I'm sorry - only the author of this article, @Deland-Han, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. I just added that comment to give this PR slightly more attention.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
