### PR TITLE
Remove "End user experience section"

### PR DESCRIPTION
**Pull request by JeremyTBradshaw**
This section provides no information of any use to the reader.  It just arbitrarily lists some information and says nothing about the associated user experience.

### CODE REVIEW

**Comment by illfated** [comment]
@billmath : May we have your view on this suggested text removal?

**Comment by billmath** [comment]
#sign-off

**Comment by eross-msft** [comment]
@JeremyTBradshaw  Did you mean to close this pull request? It was approved by the writer, but I can't merge anything because you closed it. If you can reopen this pull request, I can go ahead and do the merge. Thanks!

**Comment by illfated** [comment]
@eross-msft : Looks like the author has removed their entire windowsserverdocs fork, thereby removing any and all branches attached to that fork.

The only way to recreate the PR would be for any other user to replicate the changes in their own repo and open a new PR.

**Comment by illfated** [comment]
Then again, the change is fairly simple, simple removal of a coherent dozen lines.

**Comment by eross-msft** [comment]
@illfated  I noticed that, too. I'm guessing it's that the contributor thought the process ended with the "sign off" text. Unfortunately, I don't think it can be resurrected even on the contributor's side...I think it would have to be created new again. If the contributor doesn't respond and recreate the pull request, would you want to do it for them? Thanks!

**Comment by illfated** [comment]
Sure, not a problem. Should only take a dozen minutes.

**Comment by JeremyTBradshaw** [comment]
@eross-msft @illfated Woops! Very sorry about the prematurely closure.  I was cleaning up my forks after another PR of mine was merged earlier.  Will try not to repeat this again.

**Comment by eross-msft** [comment]
@JeremyTBradshaw   It definitely happens. Thank you so much for taking the time to make the change in the first place!

**Pull request closed without merging**
