### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by SCG82**
As written, this example will display:
```bat
Program had return code 1
Program had return code 0
Done!
```
if the value of ERRORLEVEL is 1.

### CODE REVIEW

**Comment by illfated** [comment]
Fair point, good job finding this missing piece of logic.
I would like to suggest modifying the message text as well, to improve the English grammar and coherence with actual error level reporting elsewhere in Windows software:
- The program returned error level 1
- The program returned error level 0

Do you find this to be a practical solution?

**Comment by SCG82** [comment]
> Fair point, good job finding this missing piece of logic.
> I would like to suggest modifying the message text as well, to improve the English grammar and coherence with actual error level reporting elsewhere in Windows software:
> 
> * The program returned error level 1
> * The program returned error level 0
> 
> Do you find this to be a practical solution?

done

**Comment by illfated** [comment]
😃 Nice, good job. Thank you. 👍

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
(ref. #3755 **Error in example** )

**Pull request merged**
