### PR TITLE
web-client-whatsnew.md: Corrects a broken link

### PR DESCRIPTION
**Pull request by exchange12rocks**
The new link to Remote Desktop Web Client documentation is https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-web

### CODE REVIEW

**Comment by PRMerger9** [comment]
@exchange12rocks : Thanks for your contribution! The author(s) have been notified to review your proposed change. @heidilohr

**Comment by illfated** [comment]
This seems to be about the GitHub repository and how the URLs are supposed to translate to the public pages on docs.microsoft.com.
I don't understand how the old and suggested new URL is supposed to traverse from the repository https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/ to https://github.com/MicrosoftDocs/azure-docs/blob/master/ , because the structures seem incompatible in a directory traversal context, unless there is an internal and different method of handling the traversal than what we are able to do by clicking the links in our browser.

It is difficult to understand how the link traversal is supposed to work, because here on GitHub, the actual URL for the document page **Connect to Windows Virtual Desktop with the web client** is this:
- https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-desktop/connect-web.md

On docs.microsoft.com, however, the URL is:
- https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-web

I do understand that it seems correct to change the GitHub link according to what is previously used, as it seems that the docs.microsoft.com site does not have a directory named /azure-docs/, only /azure/, but I find it difficult to understand how the relative links work, seeing that when viewing the page https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/web-client-whatsnew.md here on GitHub and clicking the current link [Connect to Windows Virtual Desktop with the web client] leads to https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/azure-docs/articles/virtual-desktop/connect-web.md (404 - "This is not the web page you are looking for.") Testing your suggested link https://github.com/exchange12rocks/windowsserverdocs/blob/patch-3/azure/virtual-desktop/connect-web.md does not lead to any page (404) and the corresponding result if this PR were to be merged, https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/azure/virtual-desktop/connect-web.md (also 404, because there is no root directory named /azure/ in the /MicrosoftDocs/windowsserverdocs/ repository), I am wondering if it would be better to use either the direct docs.microsoft.com link or the full github.com/MicrosoftDocs/azure-docs/ URL to point directly to the page.

Any thoughts about this, or have you managed to find out how the relative link traversal works when translated to docs.microsoft.com URLs?

**Comment by PRMerger10** [comment]
@exchange12rocks : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@exchange12rocks : Any suggestions about the directory traversal handling by the links, or have you tested that the change you propose is a working solution?

**Review by Heidilohr — APPROVED** [review]

**Review by illfated — APPROVED** [review]

**Pull request merged**
