### PR TITLE
Command Extensions: extra note and adjustments

### LINKED ISSUE #4305: Really?
"Enables the command extensions... " For real?  How about explaining what command extensions are or even a link (anchor) to what command extensions are.  This is beyond absurd.  Whoever wrote this must have intended to be aleck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c1319ea-20fb-948f-dc98-622d106439ca
* Version Independent ID: d8e5fe91-62d8-1565-f625-dbde41df0dec
* Content: [setlocal](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/setlocal.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/setlocal.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by KarkDenUheldige**
**Description:**

This concludes my previous attempt to update the document page `setlocal.md`, PR #4461

As discussed in issue ticket #4305 , this provides a more complete description for Command Extensions.

**Proposed change:**
- Add a bullet point entry in the **Remarks** section, describing practical details when using Command Extensions.

**Additional changes:**
- CamelCase capitalization for improved readability
- capitalization of NUL (entity name standard)
- "batch program" => 'batch script' (commonality)
- Parameters table: center first column, add spacing

Closes #4305

#sign-off

### CODE REVIEW

**Comment by PRMerger18** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Content: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal
Content Source: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/setlocal.md

**Review by illfated — COMMENTED** [review]
**Rich diff view**, for easier overview of the layout of the changes:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5409/files?short_path=136c38f

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on an agreement with the MS Docs team.

**Pull request closed without merging**
