### PR TITLE
Failover Clustering/CSV: URL update & CSV variable

### LINKED ISSUE #3950: %SystemDisk% does not exist
I think %SystemDisk% in the above is an error, and should be corrected to %SystemDrive% (%SystemDrive%\ClusterStorage).
The system variables can be viewed in PowerShell with this command "Get-ChildItem env:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b417d33d-000d-5ae8-2525-663849e5e62a
* Version Independent ID: 16ccda8e-9d73-053f-4b67-20eaeac524bf
* Content: [Use Cluster Shared Volumes in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/failover-cluster-csvs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/failover-cluster-csvs.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #3950 (**%SystemDisk% does not exist**), the correct environment variable name is %SystemDrive% in a normal Windows Server OS.

Thanks to @HenningSR for noticing and reporting this issue.

**Changes proposed:**

- Replace the incorrect variable name %SystemDisk% with %SystemDrive%
- Update 3 outdated blogs.technet.com URLs to techcommunity.microsoft.com
- Add hyphen in "multisubnet" to use the more common variant multi-subnet
- Change "behaviour" to 'behavior', following American English standards
- Remove one phrase "that are", functioning as filler words, from a sentence

**Whitespace changes:**

- Add editorial blank line between the information header and the page title
- Add missing MarkDown indent marker compatibility spacing where recommended

**Ticket closure or reference:**

Closes #3950

### CODE REVIEW

**Comment by PRMerger7** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- [X] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4972/files?diff=unified&w=1 (to view the effective changes to the page)

- [X] **Rich diff view + Hide whitespace changes:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4972/files?diff=unified&w=1&short_path=0e0583a#diff-0e0583aa68603a0640699dce73bfa4f10a528e9ab0e01d0c7e317543fcdbd8b0 (necessary to combine both settings if you want to read the rich diff without seeing more text marked as changed than anticipated)

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
