### PR TITLE
Remove typo in sdn-security-top.md

### PR DESCRIPTION
**Pull request by stuntguy3000**
Removes an obvious typo in this page.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@stuntguy3000 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @AnirbanPaul

**Comment by illfated** [comment]
For some unknown reason (maybe by accident), added in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/8c2a3fe3127c933e4f542e50d14599a62f73c587 (direct file link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/8c2a3fe3127c933e4f542e50d14599a62f73c587#diff-3cc5c1aa8e4240f1b48ffa90d65402dc2a6653a53f4afc6f7d133d3877c1361c).

**Comment by illfated** [comment]
Trailing whitespace removed in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/d4cb450ff4e49d5c3f47b69d56c7950bd1d08bb6 (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/d4cb450ff4e49d5c3f47b69d56c7950bd1d08bb6#diff-3cc5c1aa8e4240f1b48ffa90d65402dc2a6653a53f4afc6f7d133d3877c1361c).

**Review by illfated — APPROVED** [review]
Removal of 4 double quotation marks at end-of-file. Looks good to me.

**Comment by illfated** [comment]
Should be ready for final review and #sign-off from the current document author.

**Comment by PRMerger13** [comment]
@illfated: I'm sorry - only the author of this article, @AnirbanPaul, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. I just tried to make it more obvious (for everyone else) that the comment text `#sign-off` is usable by the author to update the status of this PR.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
