### PR TITLE
Upgrade Domain Controllers: update 2 URLs

### LINKED ISSUE #3373: Broken link
In the Deprecated features section, the KB link to Disable the NoLMHash policy is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a169cc6-7051-17c0-2220-898cac8b65e4
* Version Independent ID: d793f335-3401-31b1-2f73-38255612613d
* Content: [Upgrade Domain Controllers to Windows Server 2012 R2 and Windows Server 2012](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers-to-windows-server-2012-r2-and-windows-server-2012#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Upgrade-Domain-Controllers-to-Windows-Server-2012-R2-and-Windows-Server-2012.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Upgrade-Domain-Controllers-to-Windows-Server-2012-R2-and-Windows-Server-2012.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #3373 (**Broken link**), the KB link to "Disable the NoLMHash policy" in the Deprecated features section is broken. The target page has been removed from the Microsoft Support pages.

Thanks to Mike Lazarus (@GLComputing) for reporting the issue.

While browsing the page for whitespace issues, random other issues, and typos, I also found a broken link with the following text: For more information about why the Windows engineering team implemented these changes, see Minimizing restarts after automatic updating in Windows Update. - URL https://blogs.msdn.com/b/b8/archive/2011/11/14/minimizing-restarts-after-automatic-updating-in-windows-update.aspx

The page title text I found useful to place there instead: How to reduce your chances of being prompted to restart your computer.
URL: https://docs.microsoft.com/troubleshoot/windows-server/deployment/why-prompted-restart-computer#how-to-reduce-your-chances-of-being-prompted-to-restart-your-computer

**Changes proposed:**

- replace the link and text "in KB article 946405." with the text "in the page How to prevent Windows from storing a LAN manager hash of your password in Active Directory and local SAM databases." and the URL https://docs.microsoft.com/troubleshoot/windows-server/windows-security/prevent-windows-store-lm-hash-password
- replace the link and text "see Minimizing restarts after automatic updating in Windows Update." and the URL https://docs.microsoft.com/troubleshoot/windows-server/deployment/why-prompted-restart-computer#how-to-reduce-your-chances-of-being-prompted-to-restart-your-computer

**Whitespace & Codestyle improvements:**

- added editorial blank line between the metadata and the page title
- added missing MD indent marker compatibility spacing for the "Applies To:" line
- added blank line between a H2 header and its section text (codestyle)
- replaced period dot with a colon character at the end of 2 lines (preceding descriptors)
- added missing dashes and spaces in a MarkDown table header (MD standard codestyle)
- added missing NewLine at end-of-page/end-of-file (codestyle)

**Ticket closure or reference:** 

Closes #3373

### CODE REVIEW

**Comment by PRMerger18** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
**Rich diff view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4989/files?short_path=315704a#diff-315704a177efa9a4e0d41998732b0db38d9a069e1f02c4a0ec2a63ad3394abdc
**Normal source view:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/4989/files?short_path=315704a

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@illfated: I'm sorry - only the author of this article, @iainfoulds, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
