### PR TITLE
updated gpo configuration

### PR DESCRIPTION
**Pull request by DevOpsStyle**
Hello all,

worked on NTP Server configuration on Customer Active Directory. After the configuration the customer has looking for the value on Registry Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\W32Time\Parameters -> NtpServer.

According with the documentation, with the type value set to NT5DS the syncronization will be performed with DC hierarchy, so the NTPServer value will not be considerated.

Thank you

### CODE REVIEW

**Comment by PRMerger20** [comment]
@DevOpsStyle : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by v-tappelgate — CHANGES_REQUESTED** [review]
Please update the text as follows to meet docs style standards:

If you configure a GPO to set the NTP server to your domain controller, the policy does not overwrite the Registry value of **NTPServer**. The policy sets the default **Value Type** to **NT5DS**. This value means that the NTP server synchronizes according to the domain hierarchy. This is the default configuration for domain-joined computers. To view your NTP configuration, open a Command Prompt window and run `w32tm /query /configuration`.

**Comment by DevOpsStyle** [comment]
> Please update the text as follows to meet docs style standards:
> 
> If you configure a GPO to set the NTP server to your domain controller, the policy does not overwrite the Registry value of **NTPServer**. The policy sets the default **Value Type** to **NT5DS**. This value means that the NTP server synchronizes according to the domain hierarchy. This is the default configuration for domain-joined computers. To view your NTP configuration, open a Command Prompt window and run `w32tm /query /configuration`.

Hello @v-tappelgate, applied your suggestions.

Can you review again please?

Thank you

**Review by v-tappelgate — CHANGES_REQUESTED** [review]
Closer, but the required character formats (bold and inline code) are still missing. They are part of the style guide requirements:

**Comment by DevOpsStyle** [comment]
@v-tappelgate is now ok?

**Review by v-tappelgate — CHANGES_REQUESTED** [review]
First two sentences: 

`If you configure a GPO to set the NTP server to your domain controller, the policy does not overwrite the Registry value of **NTPServer**. The policy sets the default **Value Type** to **NT5DS**. `

**Review by v-tappelgate — APPROVED** [review]

**Comment by DevOpsStyle** [comment]
@v-tappelgate Thanks for the time spent to me. For the merge is needed the '#sign-off' message?

**Comment by v-tappelgate** [comment]
#sign-off

**Comment by DevOpsStyle** [comment]
Hello @v-tappelgate , sorry for the bother. There is something i have to do for merge and close the PR? I asking because i see is still open.

Thank you

**Comment by DevOpsStyle** [comment]
Hello, What I have to do for close this PR?

**Comment by DevOpsStyle** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@Xelu86, @robinharwood, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86

**Comment by v-tappelgate** [comment]
#sign-off

**Comment by v-tappelgate** [comment]
There may be an issue with merging this because although i'm listed as the author, I may not have sufficient permissions on the repo for my sign-off to do any good.

**Comment by Jak-MS** [comment]
@v-tappelgate - all PRs in this repo are reviewed by @robinharwood or @Xelu86 . One of them will merge this. thanks.

**Comment by Xelu86** [comment]
Hey All,

Thank you DevOpsStyle for the information. This note was applied to this doc back in 09/22 and this thread wasn't closed. Additional rewrites occurred since & this note was also rewritten. More updates to W32Time will be pushed later this week. We'll now be closing this thread.

Thanks to all involved and have a most pleasant day.

**Pull request closed without merging**
