### PR TITLE
Proman tls

### PR DESCRIPTION
**Pull request by pierreroman**
updated documents to insert references to the TLS 1.3 standard and fixes some references that only covered server 2012

### CODE REVIEW

**Comment by PRMerger10** [comment]
@pierreroman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by IngridAtMicrosoft — APPROVED** [review]

**Comment by IngridAtMicrosoft** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@IngridAtMicrosoft: I'm sorry - only the author of this article, @JasonGerend, @justinha, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by pierreroman** [comment]
closing this PR and re-submitting changes to the private repo

**Pull request closed without merging**
