### PR TITLE
Update AD-FS-Rapid-Restore-Tool.md

### PR DESCRIPTION
**Pull request by illfated**
Whitespace & MarkDown codestyle standards improvement.

Changes proposed:

- add editorial blank lines after H2/H3/H4 headings
- add editorial blank line before the page title H1 heading
- normalize number of repeating blank lines
- add missing MD indent marker compatibility spacing
  (1 blank space - 8 note blob lines)
- use all caps in the CMD environment variable `%LOCALAPPDATA%`

No particular ticket or PR reference.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
- [X] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windowsserverdocs/pull/5061/files?diff=unified&w=1 (reduces the review page length somewhat)

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@illfated: I'm sorry - only the author of this article, @billmath, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
