### PR TITLE
Append details to the page

### PR DESCRIPTION
**Pull request by vamsivellanki**
You can always check the current port through PowerShell too with below commands:

Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber"
Ex:
PortNumber   : 3389
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal
               Server\WinStations\RDP-Tcp
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal
               Server\WinStations
PSChildName  : RDP-Tcp
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry

You can change RDP port by executing PowerShell commands too as example shown below by adding new RDP port as 3390
Add New RDP Port in Registry:
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" -Value 3390
New-NetFirewallRule -DisplayName 'RDPPORTLatest' -Profile 'Public' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3390

### CODE REVIEW

**Comment by illfated** [comment]
Please note that unless you use MarkDown code block fencing, the text added to the page will not be shown as aligned as it is in the source file view here on GitHub. Any line breaks and additional spacing will be suppressed in the web page view. If you want to see how it may be displayed in the target page, use the Rich Diff view in your PR:

- https://github.com/MicrosoftDocs/windowsserverdocs/pull/4799/files?short_path=a5b6195#diff-a5b619570de0114a80d09a624eeee154

Feel free to ask if you would like some help with MarkDown code block fence formatting.

**Comment by illfated** [comment]
Unfortunately, it is too tricky for me to add MarkDown code block suggestions for text modifications which can be merged directly by the PR owner, so I will instead post it here in this comment box:

***

You can also check the current port through PowerShell with the following command:

```PowerShell
Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber"
```

Output:
```
PortNumber   : 3389

PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp

PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations

PSChildName  : RDP-Tcp

PSDrive      : HKLM

PSProvider   : Microsoft.PowerShell.Core\Registry
```


You can change RDP port by executing PowerShell commands as shown in the example below, by adding a new RDP port as 3390.

Add New RDP Port in Registry:

```PowerShell
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" -Value 3390

New-NetFirewallRule -DisplayName 'RDPPORTLatest' -Profile 'Public' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3390
```

**Comment by PRMerger12** [comment]
@vamsivellanki : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@vamsivellanki : Would you consider using MarkDown code block fencing, with additional code syntax highlighting where applicable (like **```powershell** for the cmdlets) ?

**Comment by vamsivellanki** [comment]
I have created new pull request now with modified changes, you may close this.
https://github.com/MicrosoftDocs/windowsserverdocs/pull/5052

**Comment by illfated** [comment]
#please-close

**Pull request closed without merging**
