### PR TITLE
Multiple CSS cases around this documentation bug

### PR DESCRIPTION
**Pull request by raluthra**
Suggesting a change as per https://identitydivision.visualstudio.com/Hybrid%20Identity/_workitems/edit/627281.

### CODE REVIEW

**Comment by raluthra** [comment]
Thanks

**Comment by raluthra** [comment]
#sign-off

**Comment by raluthra** [comment]
@billmath , could you please help incorporate this change to the public doc? Thank you! 👍

**Comment by billmath** [comment]
#sign-off

**Comment by daveba** [comment]
Manual merge performed due to merge conflict.  Will now close this pr.

**Pull request closed without merging**
