### PR TITLE
Update tpmtool.md

### PR DESCRIPTION
**Pull request by RonaldAi**
With Windows 11 we introduced a new command (optionalcommands) that installs another tool as feature on demand. Added documentation for that new command

### CODE REVIEW

**Comment by PRMerger17** [comment]
@RonaldAi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JohnCobb1** [comment]
Hi @ashleytqy Can you please review Ronald's update, and sign off on it if no further change is needed. Thanks

**Review by ashleytqy — APPROVED** [review]
Sorry for the late response -- LGTM!

**Comment by JohnCobb1** [comment]
No problem @ashleytqy. Thanks for the fast response! Just need your sign off as the article owner to resolve this PR.  Just comment (hashtag)sign-off to complete it.

**Comment by ashleytqy** [comment]
#sign-off

**Comment by RonaldAi** [comment]
Also, Ashley (@ashleytqy ) who was in my team moved to a different team. Can we change the ownership of this page such that I (or somebody else from my team) can sign off on changes? Thanks,

**Pull request closed without merging**
