### PR TITLE
Listing miniorange as ADFS MFA Vendor

### PR DESCRIPTION
**Pull request by maheshxecurify**
Hello,

We have many customers who are already using miniOrange MFA services for ADFS. It would be great for both of us and beneficial for our mutual customers to get solutions easily if you list miniOrange MFA to your ADFS MFA page.

About miniOrange:
miniOrange is a cloud and on-premise based Identity and Access Management (IAM) solution provider.
miniOrange also makes provision for web-based security solutions for Single Sign-On, 15+ ways for Multi-Factor Authentication (MFA), User Provisioning, Identity Brokering, Social Login, etc.

Thank you!

### CODE REVIEW

**Comment by PRMerger7** [comment]
@maheshxecurify : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maheshxecurify** [comment]
Hi Bill,

Just checking in to see if you go time to go through the PR.

It would be great if you can merge the PR for listing miniOrange as MFA vendor for ADFS asap.

Let me know if you have any questions or concerns!

Thank you in advance!

**Comment by Yetoo1** [comment]
This, https://github.com/MicrosoftDocs/windowsserverdocs/pull/6632, and https://github.com/MicrosoftDocs/windowsserverdocs/pull/6710 are different variations of listing miniOrange as an ADFS MFA vendor. The latter two have been triaged and had someone pinged to review changes.

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86

@robinharwood @Xelu86 @billmath 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close

**Pull request closed without merging**
