### PR TITLE
Update Audit-Policy-Recommendations.md

### PR DESCRIPTION
**Pull request by Mysonemo**
Adding Windows Server 2016

### CODE REVIEW

**Comment by lizap** [comment]
@billmath and @MicrosoftGuyJFlo - please take a look at this proposed changes. Thanks!

**Comment by MicrosoftGuyJFlo** [comment]
#sign-off

**Comment by MicrosoftGuyJFlo** [comment]
Looks good!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lizap** [comment]
Thanks, all! This will go live on Thursday, May 24.

**Pull request merged**
