### PR TITLE
Update Configure-Additional-Authentication-Methods-for-AD-FS.md

### PR DESCRIPTION
**Pull request by rohanpinto**

### CODE REVIEW

**Review by naman-agrawal-1kosmos — APPROVED** [review]

**Review by vaibhav-1kosmos — APPROVED** [review]

**Review by rishabh-1kosmos — APPROVED** [review]

**Review by pk19111992 — APPROVED** [review]

**Review by muditmart — APPROVED** [review]

**Review by aditripa — APPROVED** [review]

**Comment by eross-msft** [comment]
@billmath  I don't believe we allow 3rd party links or content in our documentation, but Bill is our AD-FS writer and he would be in a better position to say whether I'm correct. Thanks for taking the time to make the change!

**Comment by rohanpinto** [comment]
All the integration links on that page are 3rd party links and all I did was added our integration doc link to the list

Rohan

**Comment by billmath** [comment]
Checking with engineering

**Comment by billmath** [comment]
Hi @rohanpinto 

Unfortunately I haven't heard back from engineering yet.  So, I am going to go ahead and create a work item to track this.
For now, I am going to go ahead and close the PR and I will re-open it once I have heard back.

Thanks!

Bill

#please-close

**Comment by rohanpinto** [comment]
Sure No worries Bill,

The pull request is a simple one. All it has is us listed as one of the
providers that ADFS can integrate with as additional authenticators and a
link to the documentation and a description of the offering like all the
other 19 providers listed on this page :
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs

In my opinion this was one of the simplest pull requests I've ever made.
Would appreciate it if you could merge/approve it.

regards
Rohan
#pleasemerge

Rohan Pinto
cell: (647) 293-3484
rohan@rohanpinto.com

**Comment by rohanpinto** [comment]
Any Update on the requested changes to be merged ?


Rohan Pinto
cell: (647) 293-3484
rohan@rohanpinto.com

**Pull request closed without merging**
