### PR TITLE
Update storage-qos-overview.md

### PR DESCRIPTION
**Pull request by no2601**
Due to customer requests.

### CODE REVIEW

**Comment by illfated** [comment]
Rich diff, for easier overview of the effective changes (1 sentence added in 2 places):
https://github.com/MicrosoftDocs/windowsserverdocs/pull/3753/files?short_path=d6a3fcc#diff-d6a3fccd9e5686b25aec2888dc121009

**Comment by PRMerger13** [comment]
@no2601 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
@no2601 : Will you be able to update this PR by adding the page changes to your PR content, and resolve the file conflict?

> **This branch has conflicts that must be resolved**
>
> **Conflicting files**
> WindowsServerDocs/storage/storage-qos/storage-qos-overview.md

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@illfated: I'm sorry - only the author of this article, @kumudd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. But please note that this PR has been hanging around for a year without any feedback from the author or team members.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@illfated: I'm sorry - only the author of this article, @kumudd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by KumudD** [comment]
#reassign : eross-msft

**Comment by KumudD** [comment]
@eross-msft Please can you review and address this PR. Thanks!

**Comment by eross-msft** [comment]
@illfated @KumudD  The branch conflict looks like it's a conflict of complete versions of the file. I have no idea which one is right. What I'd like to do is close this PR without merging. Then, Trond, if you could re-add your updates, I can push them through. I'm just worried if I try to do anything with these conflicts, I might make things way worse.

**Comment by illfated** [comment]
That is fine with me. I was about to suggest providing a PR myself yesterday, but I was too tired. I am ready to do it now, though. 🙂

**Comment by eross-msft** [comment]
@illfated Thank you!!!

**Comment by illfated** [comment]
There you go. PR #5249 is ready for review, comments & suggestions.

**Pull request closed without merging**
