### PR TITLE
Windows Commands/fsutil: param. description typo

### LINKED ISSUE #4133: switched
R2R, R2L

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0003865-ce9a-117a-f2ff-7eeed387c213
* Version Independent ID: 4506e308-992a-237a-4ad6-5acc552a75fe
* Content: [Fsutil behavior](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-behavior)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil-behavior.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil-behavior.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

As reported in issue ticket #4133 (**switched**), the parameter option names R2R and R2L are switched:
```
3. Remote to local symbolic links, R2R:{0|1}
4. Remote to remote symbolic links, R2L:{0|1}
```
This PR resolves the issue by switching them back.

Thanks to @alysdexia for reporting this issue.

**Proposed change:**
- Make the option names R2R and R2L switch places.

**Ticket closure or reference:**

Closes #4133

### CODE REVIEW

**Comment by illfated** [comment]
Single change, switched the placing of the option names: R2R `<->` R2L

**Comment by illfated** [comment]
#sign-off

**Comment by eross-msft** [comment]
@illfated, please see comment in Windows commands/bitsadmin: multi-page corrections #4138.

**Comment by illfated** [comment]
Thank you for keeping me updated. Wish you all the best for that major operation. Good luck and have fun. 😉

**Pull request closed without merging**
