### PR TITLE
Update cipher.md

### PR DESCRIPTION
**Pull request by michha**
Added the **_suspected_** overwriting method.
From using the command it outputs first zeros, then ones and at last random numbers.
If someone from the product team could have a look at the code and confirm my assumption please.

If I should add the algorithm (0, 1, random) instead of mentioning the DoD name I could make an additional change.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@michha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Looks OK to me, but it needs review and confirmation from the product team, as suggested by the PR author.

**Comment by MicrosoftGuyJFlo** [comment]
As published in the product that is not listed. If the PG wants to update the command then it will update in the product help file.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Pull request closed without merging**
