### PR TITLE
Rename .gitattributes to .gitattributes3

### PR DESCRIPTION
**Pull request by montycarlos**

### CODE REVIEW

**Comment by montycarlos** [comment]
Acces

**Comment by montycarlos** [comment]
> _No se proporcionó descripción._

**Comment by montycarlos** [comment]
@0x7FFFFFFFFFFFFFFF

**Comment by montycarlos** [comment]
wifi-pink

**Comment by montycarlos** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/pull/7022#issuecomment-1412534222

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by robinharwood** [comment]
Hi @montycarlos, closing this PR for the moment as repository root files cannot be changed here.

Thanks, #please-close

**Pull request closed without merging**
