### PR TITLE
Add new page for netsh mbn commands

### PR DESCRIPTION
**Pull request by apdutta**

### CODE REVIEW

**Comment by illfated** [comment]
Looks quite impressive. Would it be OK if I suggest a 1 character correction to the same sentence, repeated many times on this completely new page?

```diff
- Interface name. It is one of the interface name shown by "netsh mbn show interfaces" command.
+ Interface name. It is one of the interface names shown by "netsh mbn show interfaces" command.
```
```
name -> names
```
(38 occurrences)

I understand it very well if you find this suggestion tedious and discouraging, so I will immediately withdraw my suggestion if it breaks your schedule to have this new page published. (Someone else ended up withdrawing their PR because I suggested too many typo/grammar corrections.)

**Comment by billlattimer** [comment]
@apdutta, good work!

A few notes: 

- The 'diagnose' command doesn't appear with help on Windows 10. 
- There are some mild formatting issues in terms of extra spaces/blank lines, etc. that may cause build warnings. 
- It might be worth adding a TIP at the top noting how to get help on the command. netsh -> command -> ?

**Comment by apdutta** [comment]
> @apdutta, good work!
> A few notes:
> 
> The 'diagnose' command doesn't appear with help on Windows 10.
> There are some mild formatting issues in terms of extra spaces/blank lines, etc. that may cause build warnings.
> It might be worth adding a TIP at the top noting how to get help on the command. netsh -> command -> ?

@billlattimer Thank you for the review. The diagnose command is a new addition that will be available in Iron. How do we handle documentation for these features?

**Comment by apdutta** [comment]
@illfated Thanks for catching the error! I have updated the occurrences.

**Comment by illfated** [comment]
👍 Nice, very good. Thank you! 😃

I know this might seem too cosmetic to many users, but may I also suggest making it a habit to always include "MarkDown indent marker compatibility spacing" between the indent markers and any following text, for the Note (Tip) blob? (see example below) -- this is considered default MarkDown codestyle (whereas MD indent markers without spacing is often dubbed "lazy style").

```diff
- >[!TIP]
- >You can get help on the netsh mbn command by using 
- >
+ > [!TIP]
+ > You can get help on the netsh mbn command by using 
+ >
```

**Comment by illfated** [comment]
#sign-off

**Comment by apdutta** [comment]
Thanks @illfated! Do you know how I can merge this change?

**Comment by eross-msft** [comment]
@dcuomo  Can you please review this content and let me know if it's okay to merge? Or add a different reviewer? Thanks!!

**Comment by dcuomo** [comment]
I don't actually know who should review this (or owns netsh)

**Comment by eross-msft** [comment]
@dcuomo  Okay, thanks! I'll keep hunting around for a reviewer. @apdutta I see you're an employee, do you work with a PM that can validate/review your updates? As a side note, as an employee you should actually be working in the windowsserverdocs-pr repo, but for this one it's fine.

**Comment by apdutta** [comment]
@eross-msft Thanks for the feedback. I wasn't aware that there was a separate repo that was to be used. Will definitely keep in mind next time. 

I have sent this PR to my manager and a PM on my team to review but I don't think they have access to this repo yet as I can't find them in the reviewers search.

**Comment by illfated** [comment]
Fair enough. If they are users on GitHub, it should still be OK to notify them by adding their 
@username in a comment, asking them to approve by commenting here or even use the
[Review changes] -> (•) Approve -> [Submit review] feature in the [[Files changed]](https://github.com/MicrosoftDocs/windowsserverdocs/pull/3935/files) page.

**Comment by jefsong** [comment]
Hi Apu - Thanks for driving this changes, I went through the diffs and your changes look good. No concerns from my side. Jeffrey Song

**Comment by apdutta** [comment]
@eross-msft @illfated Jeffrey Song is a PM on my team and has approved the changes. Could you help merge this change?

**Comment by eross-msft** [comment]
@apdutta Since it's approved, I'll go ahead and merge now. Thanks!

**Pull request merged**
