### PR TITLE
Typos, whitespace, and MarkDown formatting

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

During the review of PR #5036 to update this file, I noticed some signs of incorrect formatting and whitespace issues.

**Changes proposed:**

- typo corrections for "muliple" and "brower"
- replace double pairs of MD backticks with proper MD code blocks to keep intended line breaks
- remove an unwanted apostrophe (') between the "Applies to:" line and the first text paragraph
- add missing MD indent marker compatibility spacing for all Note/Tip blobs and "Applies to:"

**Ticket or PR closure or reference:**

Ref. #5036

### CODE REVIEW

**Comment by PRMerger13** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change. @AnirbanPaul

**Review by illfated — COMMENTED** [review]
You may want to use **Hide whitespace changes** (https://github.com/MicrosoftDocs/windowsserverdocs/pull/5045/files?diff=unified&w=1) to simplify the review process.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @AnirbanPaul, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
