### PR TITLE
Update perform-in-place-upgrade.md

### PR DESCRIPTION
**Pull request by XXLMandalorian013**
I was looking into an in-place server OS upgrade as well as an Azure Entra/AD Connect upgrade for a client and noticed, to my knowledge, the Perform an in-place upgrade of Windows Server doc or its link to Windows Server 2022 and Microsoft server applications compatibility doc does not state that, 

"If you need to upgrade the operating system of your Microsoft Entra Connect server, do not use an in-place upgrade of the OS (Operating System). Instead, prepare a new server with the desired operating system and perform a swing migration." 

I placed the note where I thought it should be and look forward to hearing back!

https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-upgrade-previous-version#upgrading-the-server-operating-system

https://learn.microsoft.com/en-us/windows-server/get-started/perform-in-place-upgrade

https://learn.microsoft.com/en-us/windows-server/get-started/application-compatibility-windows-server-2022

### CODE REVIEW

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by XXLMandalorian013** [comment]
Still needs merged?

**Comment by Xelu86** [comment]
Hey @XXLMandalorian013, good find & thank you for bringing this to our attention. We have modified your contribution to lead users to the [Microsoft Entra Connect: Upgrade from a previous version to the latest](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-upgrade-previous-version) page.

This way, they can use either the [Swing migration](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-upgrade-previous-version#swing-migration) guidelines or use the [MS Entra Evaluation Sync Wizard](https://setup.microsoft.com/entra/add-or-sync-users-to-microsoft-entra-id) for what need suits users best.

Merging shortly.

**Comment by XXLMandalorian013** [comment]
Just happy to help!

**Pull request merged**
