### PR TITLE
Update Configure-User-Certificate-Authentication.md

### PR DESCRIPTION
**Pull request by SanDeo-MSFT**

### CODE REVIEW

**Comment by eross-msft** [comment]
@billmath Please confirm if this text is okay to merge. Thanks!!

**Comment by SanDeo-MSFT** [comment]
+ @Samuel Devasahayam<mailto:samueld@microsoft.com>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by illfated** [comment]
@SanDeo-MSFT : I think you meant to ping @samueldeva instead of "samuel" = Samuel Stauffer.

**Comment by SanDeo-MSFT** [comment]
yes

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
