### PR TITLE
Update upgrade-storage-spaces-direct-to-windows-server-2019.md

### PR DESCRIPTION
**Pull request by dkawula**
There are missing steps to this process.   We are doing one live today and there are some important steps missing.

### CODE REVIEW

**Comment by daveba** [comment]
@JasonGerend Please review and if you agree with the changes, please sign off so I can merge.  Thanks!

**Comment by JasonGerend** [comment]
@RobHindman - can you confirm? Thank you!

**Comment by daveba** [comment]
@JasonGerend @RobHindman Any update here?

**Comment by eross-msft** [comment]
@JasonGerend @RobHindman Any update here?

**Comment by illfated** [comment]
@dkawula : Will you be able to resolve the merge conflict in this PR, or do you prefer to close this and start a new one, based on the current layout of the document page?

**Comment by Karl-WE** [comment]
@illfated @dkawula could I assist to resolve the conflict?

**Comment by illfated** [comment]
Feel free to do so. I am uncertain whether @dkawula will reply any time soon, seeing that there has been no new comment (except for yours) since May 2020.

**Comment by Karl-WE** [comment]
@illfated seems I am not allowed to
"You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork Karl-WE/windowsserverdocs, so you can send a pull request."

"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests."

**Comment by illfated** [comment]
Yes, I'm not sure why I thought you could change anything, because that is usually only available to the PR author and MS Docs team members with merge rights to the MS Docs repository.

**Comment by eross-msft** [comment]
@illfated and @Karl-WE  I can fix the conflict, but I'm not sure what's supposed to be there, there are several conflicts involved. Since this is an older PR and the original contributor hasn't been on since the original contribution, can I close this PR and have you open a new one with only the right content, based on the latest version of the files?

**Comment by illfated** [comment]
Sounds good to me. @Karl-WE : Would you like to create a new PR for this content?

**Comment by Karl-WE** [comment]
@eross-msft I think this would make sense.

**Comment by illfated** [comment]
@Karl-WE : Any ETA on when you plan to start your version of this PR?

**Comment by Karl-WE** [comment]
Hi no ETA yet @illfated my backlog grows atm.

**Comment by illfated** [comment]
@Karl-WE : Sorry for pinging you again, I just thought I should mention that the changes in this PR seem quite simple and easy to transpose to the current version of the document. I have no trouble opening a PR and just ask for you to review it, if that is OK with you. What do you think? Do you have ideas for extending this PR content?

**Comment by Karl-WE** [comment]
@illfated I am sorry, not yet. Perhaps I was too quick with my offer to solve this. This weekend is again packed with stuff, but I assure you I would do that. If you find time please go ahead. I will appreciate it to have one off my list at the moment.

**Comment by illfated** [comment]
Thank you. Will cooperate.

**Comment by illfated** [comment]
Wow. Sorry for the 1 month long delay. I seem to have gone about this the wrong way, trying to use comparing tools instead of just taking the PR change and pasting it in a separate notepad window, then finding the right section in the current document. Oh well, no use crying over spilled milk. Time to get a awake and sober review of the current document.

**Comment by illfated** [comment]
(For reference: the master branch file link is https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/upgrade-storage-spaces-direct-to-windows-server-2019.md .)

**Comment by illfated** [comment]
There you go (finally). PR #5157 is ready for review, comments, and suggestions. Maybe we could discuss whether to close this PR (#2640) before or after my PR (#5157) is merged.

**Comment by Karl-WE** [comment]
@illfated  @RobHindman another conflict?

**Comment by illfated** [comment]
Not really. The Pull Request on this page (#2640 ) is mostly unchanged since November 2020. I believe we should focus on my PR #5157 since I am able to follow up on that one myself. That PR does not have any file conflict issues (yet).

There could be a delay in getting a final review & merge for my PR #5157 now that Elizabeth Ross (eross-msft) is leaving this repository to work in a different department, but I have been assured that a very capable person (@femila ) will be taking over after E. Ross.

**Comment by Karl-WE** [comment]
welcome @femila . Thanks for the update @illfated

**Comment by PRMerger14** [comment]
@dkawula : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by illfated** [comment]
Please note my replacement PR #5157 which supersedes this PR. I am still considering if this PR should be closed and further discussions redirected to #5157 .

**Pull request closed without merging**
