### PR TITLE
Update required permissions for file share hosting redirected folders

### PR DESCRIPTION
**Pull request by qpskcn1**
Update required permissions for the file share hosting redirected folders
Add `Traverse folder / execute file`permission to Security group of users needing to put data on share`.

### CODE REVIEW

**Comment by JasonGerend** [comment]
@jeffpatt24 - can you confirm?

**Comment by qpskcn1** [comment]
Hi Jason,

Sorry, I just saw the message.
Yes, it works only if I add `Traverse folder / execute file`.
And I believe this permission was listed in previous documentation
[https://support.microsoft.com/en-us/help/274443/how-to-dynamically-create-security-enhanced-redirected-folders-by-usin](https://support.microsoft.com/en-us/help/274443/how-to-dynamically-create-security-enhanced-redirected-folders-by-usin)

**Comment by daveba** [comment]
@JasonGerend Where are we with this one.  If you agree with the changes, please sign off so I can merge.  Thanks!

**Comment by JasonGerend** [comment]
I'm looking at all these now. Update shortly
________________________________

**Comment by JasonGerend** [comment]
I pinged the PM again just now - we're just trying to make sure this is correct before updating the content.

**Comment by daveba** [comment]
@JasonGerend Any update here?

**Comment by illfated** [comment]
It has been quite a while without any update in this PR. Any chance of getting updated feedback from the PM here?
Also: the `Traverse folder / execute file` permission is akin to the Unix folder permission `chmod +x` giving normal access to the folder via the `cd` (change directory) command.
I don't see any good reason why this folder permission should not be added to a user or group who already has confirmed read+write access to the folder.

**Comment by eross-msft** [comment]
@jasongerend  Following up to see if there are any updates for this PR. Thanks!

**Comment by illfated** [comment]
Line 176 needs updating (typo correction, **adminisitrators** `->` **administrators** in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/943e73e22896e724b53963f21438a9278feaeacd) to resolve the file conflict:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/2158/files#diff-973bcb05ab92c6cc772ad7ec13eb26cbR176

**Comment by eross-msft** [comment]
@jasongerend Any updates?

**Comment by eross-msft** [comment]
@JasonGerend Any updates?

**Comment by eross-msft** [comment]
Closed by mistake, sorry. Re-opening for review

**Comment by illfated** [comment]
@qpskcn1 : Any chance you will be able to resolve the merge file conflict?

**Comment by qpskcn1** [comment]
@illfated It's been a while. I can take a look at it. Did you guys change from HTML table syntax to Markdown?

**Comment by illfated** [comment]
Thank you for replying. Also, I am not a member of the MS Docs team, I am merely a regular external user, but with a sound interest in GitHub, grammar and editing.

Well, MarkDown is the preferred format in most of the documentation, but some of the MS Docs managers still find HTML a bit superior in use, at least when it comes to table handling.

From my point of view, MarkDown makes it easier to read when editing the source and is also easier to use for simple text tables. HTML can still be useful in those tables too, like when you need to add line breaks inside a cell using `<br>` tags and similar, since MarkDown does not necessarily read standard line breaks/newlines in text inside individual MarkDown table cells. So for tables with a need for lots of formatting, HTML may still be quite useful, but I would say that MarkDown is preferred for normal, simple text tables.

**Comment by illfated** [comment]
Nice. Thank you for updating the PR source. Good job.

**Review by illfated — APPROVED** [review]
Looks good to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @JasonGerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Please see my PR #5181 for a new and comprehensively documented attempt to correct this same document.

Please also note: I will add a closing comment for this PR (#2158) in my PR #5181.

**Comment by illfated** [comment]
(ref. issue ticket #4249 )

**Pull request closed without merging**
