### PR TITLE
Clarify scheduled task's cadence for SSDs

### PR DESCRIPTION
**Pull request by ChandKV**
Also remove the incorrect comment about schedule task for SSDs
and VHDs on SSDs.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ChandKV : Thanks for your contribution! The author(s) have been notified to review your proposed change. @eross-msft

**Review by illfated — APPROVED** [review]
Looks straight-forward and OK to me.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @eross-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
