### PR TITLE
Force linebreaks before images

### PR DESCRIPTION
**Pull request by HelderMagalhaes**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@HelderMagalhaes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — APPROVED** [review]
Seems reasonable and correct to me. This looks particularly useful in cases where animated GIF images are used.

Rich Diff view, for easier layout view:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5557/files?short_path=9a379d3#diff-9a379d3caa3ea7f29a7ce250d4c1f72369cfabec074d090c91998300313079d6

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@illfated: I'm sorry - only the author of this article, @wmgries, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. My sign-off comment is based on a previous agreement with the team.

**Comment by wmgries** [comment]
#sign-off

**Comment by wmgries** [comment]
This was taking too long to close after I signed-off so I cherry-picked this commit into my personal fork, made a PR into our private fork of windowsserverdocs, and then merged it in. Therefore, this change has made it to production. Thanks for helping out with the formatting - you should be able to see your contribution in public now.

#please-close

**Pull request closed without merging**
