### PR TITLE
Update Demoting-Domain-Controllers-and-Domains--Level-200-.md

### PR DESCRIPTION
**Pull request by SreeVoleti**
Changed the word expose to enable.
Removed the word simply from the instruction.

### CODE REVIEW

**Comment by daveba** [comment]
@MicrosoftGuyJFlo, please review and if you agree with the changes, please sign-off so I can merge.

**Comment by MicrosoftGuyJFlo** [comment]
@SreeVoleti Please fix the double space that was created when you deleted the word simply and then I will approve.

**Comment by MicrosoftGuyJFlo** [comment]
#sign-off

**Comment by MicrosoftGuyJFlo** [comment]
@eross-msft

**Pull request merged**
