### PR TITLE
Update Ubuntu Hyper-V document

### PR DESCRIPTION
**Pull request by szarkos**
- Add information about Ubuntu 18.04 and 18.10
 - Update grid to show Window Server 2019 support
 - Update notes to include new Azure-tuned kernel (linux-azure) and remove references to HWE kernel
 - Remove EOL Ubuntu versions

### CODE REVIEW

**Comment by szarkos** [comment]
@shortpatti

**Comment by szarkos** [comment]
@lizap

**Comment by shirgall** [comment]
@wssc-pra Please ad d"ready-to-merge" label. I have reviewed this change and it's good.

**Comment by Zipor** [comment]
Ready-to-merge

**Comment by shirgall** [comment]
Fixes https://github.com/MicrosoftDocs/windowsserverdocs/issues/1856

**Comment by shirgall** [comment]
Fixes https://github.com/MicrosoftDocs/windowsserverdocs/issues/1625

**Pull request merged**
