### PR TITLE
Update manage-tls.md

### PR DESCRIPTION
**Pull request by WAftring**
Add call outs that an empty cipher suite list will prevent TLS from leveraging any cipher suite.

### CODE REVIEW

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by WAftring** [comment]
@robinharwood @Xelu86 anything needed from my end on this?

**Comment by robinharwood** [comment]
Hi @WAftring - when you say "prevent any TLS cipher suites from being leveraged". Do you mean the TLS negotiation will fail completely, isn't initiated, or will it fall back to either SSL or unencrypted?

**Comment by WAftring** [comment]
> Hi @WAftring - when you say "prevent any TLS cipher suites from being leveraged". Do you mean the TLS negotiation will fail completely, isn't initiated, or will it fall back to either SSL or unencrypted?

It means that schannel will be unable to leverage TLS.

**Pull request closed without merging**
