### PR TITLE
Spelling correction in rdp-general-troubleshooting.md

### PR DESCRIPTION
**Pull request by hdaugherty**
Corrected the word start on line 28, it was misspelled as starty.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@hdaugherty : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ItzLevvie — APPROVED** [review]
LGTM.

**Review by illfated — APPROVED** [review]
Good catch. Thank you for correcting the typo.

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@illfated: I'm sorry - only the author of this article, @kaushika-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by eross-msft — APPROVED** [review]

**Pull request merged**
