### PR TITLE
Added /elevate to start command

### LINKED ISSUE #3520: Start command missing docs for /elevate
The `start` command, in the docs, seems to leave out `/elevate` from its list of flags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f381cec-d200-7862-a0c3-afeeb617c279
* Version Independent ID: 08873192-45b4-fc90-aa47-c8780d2a395f
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by BrandonDyer64**
fixes #3520 

This command flag was missing from the documentation.

### CODE REVIEW

**Comment by BrandonDyer64** [comment]
@illfated Is there any progress on getting this merged?

**Comment by illfated** [comment]
@BrandonDyer64 : Thank you for thinking highly of me and that I would be involved here or a possible Microsoft employee (I am not employed with Microsoft or any affiliates).

Please use the phrase `#sign-off` alone and on its own in your next comment, to signal to the document author (@coreyp-at-msft) & doc manager @DonGill that your PR is ready for final review.

See my next comment for an example of how to report your PR as ready for review by the Microsoft Docs team members.

**Comment by illfated** [comment]
#sign-off

**Comment by BrandonDyer64** [comment]
Oh, thanks!

**Comment by BrandonDyer64** [comment]
#sign-off

**Pull request merged**
