### PR TITLE
Note about high performance IPsec connections

### PR DESCRIPTION
**Pull request by ManikaDhiman**

### CODE REVIEW

**Comment by American-Dipper** [comment]
@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by AnirbanPaul** [comment]
#sign-off

**Comment by Jak-MS** [comment]
#assign: @robinharwood, @Xelu86 

@robinharwood @Xelu86 
Can you review the proposed changes? 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by robinharwood** [comment]
Looks good to me, thanks @ManikaDhiman.

@Jak-MS #sign-off

**Pull request merged**
