### PR TITLE
Storage QoS: "This setting affects all VMs"

### PR DESCRIPTION
**Pull request by illfated**
**Description:**

Adding the following 2 sentences (one of them in parentheses):

- "This setting affects all virtual machines. (The virtual machines created on local volumes are also affected.)"

Thanks to @no2601 for providing the information in the original PR.

**Changes proposed:**

- Add information from PR #3753 about changes in the storage input/output operations per second (IOPS) settings affecting all VMs on the server.

**Codestyle & whitespace:**

- Add editorial blank line between metadata and the page title (H1).
- Normalize spacing after the dash in bullet point lists, from 3 spaces to 1 (25 occurrences).
- Consistency: insert missing editorial blank lines before & after H2/H3/H4 headings.
- Consistency: correction of the casing in "IOPs" to IOPS (I/O Per Second), this is not about the plural of IOP. (70 occurrences)
- Add spacing between 8 and KB, before the first insert.

**Ticket closure or reference:**
Ref. #3753

### CODE REVIEW

**Comment by PRMerger18** [comment]
@illfated : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by illfated — COMMENTED** [review]
To shorten the review page length somewhat, use the **Hide whitespace changes** feature:
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5249/files?diff=unified&w=1

**Rich diff view:**
- https://github.com/MicrosoftDocs/windowsserverdocs/pull/5249/files?diff=unified&w=1&short_path=0a63778#diff-0a6377826e07c1aaf898d85ec2599eca6098fe58aa826eb2d4cc426160dd5fdf

**Comment by illfated** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@illfated: I'm sorry - only the author of this article, @kumudd, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by illfated** [comment]
Yes, I know. We have agreed to keep doing this anyway.

**Comment by illfated** [comment]
@eross-msft : I know you are on your way out, but would it be possible to suggest adding a task to the list when merging, that either the author or the merger replaces the **[do-not-merge]** label with the **[ready-to-merge]** label by commenting `#sign-off` , or maybe even ask the GitHub dev team to add a script line to apply it automatically when merging a PR?

Maybe I am overzealous about this, but I think it would look cleaner to have the label changed when a PR is closed in a successful merge.

**Comment by eross-msft** [comment]
@illfated Thank you for pointing this out. I believe there might be a process change coming, whereby this label would change to ready to merge with the sign-off. But I'm not sure. Normally, contributing to the public repo involves more people and more process, which I bypassed to make it easier/faster for people to contribute. Now that this repo isn't my home anymore, the new manager might feel there's a better way to do this :)

**Comment by illfated** [comment]
Well, it currently works (as I have seen in just a couple of PRs) when the author adds the comment `#sign-off`, but it might not do so if the merging team member is not also the author (I don't know yet). I may raise the question again later, when the new manager is ready and established. 🙂

**Pull request merged**
