### PR TITLE
US 1637896 - Loc content review and fix.

### PR DESCRIPTION
**Pull request by v-thpra**
[User Story 1637896](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1637896): Content Update - Localization fix: Windows Server Docs - M44486 Content review

Line 54: Filled in missing words and clarified the meaning of this section.

### CODE REVIEW

**Comment by v-thpra** [comment]
#sign-off

**Comment by v-thpra** [comment]
@illfated It looks like this has passed reviews. Can it be merged?  The Loc team is wondering about the status and would like to get these changes in. Thanks!

**Comment by illfated** [comment]
Thank you for mentioning me, I wish I were able to oblige in this matter. I am merely an external user and contributor to this repository and the Windows IT Pro docs.

@lizap : As the document author, will you be able to follow up on this PR for final review? Or should we wait for the doc manager @DonGill to handle this?

**Comment by v-thpra** [comment]
#sign-off

**Comment by illfated** [comment]
@Heidilohr : Do you know if there are anyone else available to follow up on this typo & grammar improvement solution, besides the already mentioned document author and the manager? Or would it be useful to assign this issue ticket to the relevant person for final review & merge?

**Comment by v-thpra** [comment]
@ItzLevvie @illfated @Heidilohr @DonGill It looks like this change has passed two reviews. If there are no suggested changes, the Localization team would like to get this merged. Thanks!

**Comment by illfated** [comment]
@v-thpra : Please note that both ItzLevvie and I are ordinary users (not employed by MS), so we need to be patient for reviews by the document author & the manager employed by Microsoft.

I acknowledge the fact that it seems confusing that ItzLevvie and I have added our non-affiliated approvals. We have acted in good faith, offering our free time and general knowledge to suggest that the PR content is good enough for final review by either the document author or the team manager for this section of the repository. I apologize for the confusion it has brought you in this case.

**Comment by v-thpra** [comment]
@illfated Thanks for explaining that, and thank you very much for your review and your efforts on this PR to help me find the correct person to sign-off on it.

**Comment by Heidilohr** [comment]
#sign-off

**Comment by Heidilohr** [comment]
@v-thpra Something seems to be up with GitHub at the moment, so I'm going to ask the admin to merge this for you. The pull request should send you a notification when it merges.

**Comment by v-thpra** [comment]
@Heidilohr Thank you!

**Comment by illfated** [comment]
I could be wrong, but seeing that the users with write access to the repository have shown green tick marks when approving in previous cases, it looks as if none of us users here have merge access for this PR.

(As previously stated, I could very well be mistaken about this detail.)

**Comment by eross-msft** [comment]
@illfated  @v-thpra  I believe the reason you can't see the merge button is because you are in the public repo. But I could be mistaken if this is typically where you make your changes. I'm going to go ahead and merge your changes now.

**Comment by illfated** [comment]
Fair enough, thank you for your reply. I was mostly concerned about MS Docs team members without merge access, because it is obvious that the PR author and I don't have access. A simple example would be mapalko, who is a document author of several articles, but he does not have merge access. When he approves an article, his approval tick mark is black, just like the 3 here in this PR. This is in contrast to those who do have merge access, where you will see a **green** approval tick mark when approving a PR where you do have merge access.

That is as condensed as I can make it, to point out why Heidi Lohr commented about not being able to merge this PR.

**Comment by eross-msft** [comment]
@illfated  We actually don't allow merge permissions to people outside of specific writing or administrative groups. While the writers/admins typically don't edit content for people that are seen as subject matter experts or in self-serve status, we do still take a look to make sure nothing breaks our builds before merging. If you need a review quicker than you're seeing it, I suggest the following: 1) Create your content in the private repo (if you're a Microsoft employee), 2) Add windowsservercontent as a reviewer (this notifies the writers), and 3) Add # sign-off (without the space after the #) in the comments. This will change the article status and tell us it's ready for final review and publish if everything looks okay. If you can't work in the private repo, you can @ mention the windowsservercontent group and it should still notify the writers that you're ready for a review.

**Comment by illfated** [comment]
Thank you for your detailed answer, appreciated. Useful details, I will keep those in mind.

**Pull request merged**
